### ISSUE TITLE
Fetch data on reconnect

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#1517]
> One thing I've noticed is that if I have my inbox open, and then close my computer or leave for a few hours, and then return to the tab, the inbox is stale (i'm guessing because the socket connection closed so i wasn't getting new subscription data). It would be awesome if on reconnect it would run the query again and automatically update the inbox view so i don't have to refresh anyways :)

From #1515

**Comment by brianlovin** [comment]
We did this for most views in `src/hooks/useConnectionRestored.js`
