### ISSUE TITLE
RSS Feed ingestion

### ISSUE THREAD

**Issue by superbryntendo** [withspectrum/spectrum#1744]
We should allow content creators to automate content with RSS

Should have queue/approval process with controls to select between (Don't post <> Post after Manual Approval <> Post automatically)

Should handle embeds for podcast feeds (maybe through a podcatcher client like PocketCasts instead of through a host like Simplecast?).

**Comment by brianlovin** [comment]
We never got too far in exploring this, but I think right now the feeling is that we'd rather promote organic personal threads than automating this process from outside services.
