### ISSUE TITLE
Pasting a long link into chat input in iOS Safari hides send button

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#1746]
<img width="418" alt="screen shot 2017-10-26 at 5 17 00 pm" src="https://user-images.githubusercontent.com/7525670/32061304-8c9a4790-ba71-11e7-951f-ea1d602dbd57.png">

**Comment by mxstbr** [comment]
Awesome, thanks so much for trying to reproduce—seems like it was indeed fixed! Closing

**Comment by ryota-murakami** [comment]
@tadasant thank you for report!
looks so good😀
