### ISSUE TITLE
DM badge doesn't always show up

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#1806]
People are missing DM notifications because of it. https://spectrum.chat/?t=33c486ed-a27f-4bc6-bac9-018454209234

**Comment by mknepprath** [comment]
Can confirm this issue - I don't see any indicator that I've received a DM. Was about to add a new issue, but saw that this existed! 👍

**Comment by brianlovin** [comment]
I'm already seeing improvements with this in #2866 - going to close for now
