### ISSUE TITLE
Do some image resizing on the server before storing in s3

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#1871]
Ideally we don't let 16mb photos hit our server - let's do *some* processing to trim these down before they hit s3, then let imgix do the rest 

https://spectrum.chat/thread/69872cca-3876-4864-ac6c-9a086f9de06b

**Comment by brianlovin** [comment]
Thanks for the info here as well @ovflowd! We are currently serving images through Imgix, who do some compression on their end as well. But we definitely should have some kind of worker that receives jobs about image uploads and can properly compress/resize/filter them (e.g. we could add in some image detection for adult themed images and flag those to moderators).

**Comment by brianlovin** [comment]
We use `redis` + https://github.com/OptimalBits/bull for jobs - see `shared/bull/queues` for how this is set up. I can't think of an existing worker where image processing makes sense for jobs to go, so we could just spin up a new worker specifically for processing images.

**Comment by ovflowd** [comment]
@brianlovin so you're using Amazon ElastiCache (For spectrum.chat).  I will give a look on the  `bull` repo. Yep, I also think a new worker for Image processing would be the best.

The complicated thing is the adult image detection. And also the part where moderators evaluate if it's adult content or not. But maybe it could be already too late when we notify the moderator.

The  "malicious content" from the image could already impacted the user base.

Maybe for this one, we should use automatic image deletion?

This library for Node: https://www.npmjs.com/package/nudity-filter uses [Sightengine](https://sightengine.com/docs/nsfw-detection-model) that has a free tier, but actually it's paid as far I remember.

**Comment by brianlovin** [comment]
@ovflowd we are not using ElastiCache. Right now we're leveraging ZEIT's CDN caching (powered by CloudFlare https://zeit.co/blog/now-cdn)

We don't need to worry about malicious image detection right now, was just suggesting that we could architect with future processing flows in mind :)

**Comment by ovflowd** [comment]
Zeit Caching it's cool, I didn't knew it was being powered by CloudFlare.

**Comment by brianlovin** [comment]
This isn't high priority any more since we enforce upload size limits in the backend and serve resized images via imgix
