### ISSUE TITLE
Add tooltip to message code toggle

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#1918]
https://spectrum.chat/spectrum/hugs-n-bugs?thread=41bcaf20-0045-400d-bbcc-5fd1ad65fcde

**Comment by mknepprath** [comment]
<img width="140" alt="screenshot 2018-04-05 00 59 13" src="https://user-images.githubusercontent.com/1000280/38349411-92169ad8-386c-11e8-8531-e97da83616a3.png">

Tooltip shows up for me - but the z-index issue in messages is still there.

**Comment by mxstbr** [comment]
Now the code message toggle is gone entirely, so this is obsolete.
