### ISSUE TITLE
Denormalize member counts

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#1955]
After clicking around the app for a while and looking at the queries that took the longest overall, this is what I'm left with:

![screen shot 2017-11-08 at 2 43 41 pm](https://user-images.githubusercontent.com/7525670/32552171-52abde46-c493-11e7-9ea7-614854d16396.png)

`.count()` is slow af. We should look into denormalizing that (as much of a pain as that is) to speed up loading of community pages etc.

**Comment by brianlovin** [comment]
We did it!
