### ISSUE TITLE
pasting issues in post editor

### ISSUE THREAD

**Issue by uberbryn** [withspectrum/spectrum#2080]
~~Pasting code from Dropbox Paper into a code block in Spectrum puts each line side-by-side. This was fixed by pasting it in Atom first.~~ Fixed

~~Pasted underscores are converted to Markdown and bold some of the code.~~ Fixed

When pasting large chunks of text, the sidebar gets disconnected from the cursor. Usually at the top of the current paragraph.

When pressing enter inside a heading, it moves the cursor outside the heading, but doesn't take the text after the cursor with it.

**Comment by mxstbr** [comment]
These were all fixed!

**Comment by brianlovin** [comment]
Only thing I'd add to this is that pasting code is pretty busted right now - it creates a new code block for each line being pasted in.
