### ISSUE TITLE
Nicer SSR error page

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2150]
<img width="345" alt="screen shot 2017-12-05 at 8 40 26 pm" src="https://user-images.githubusercontent.com/7525670/33627038-954f4b06-d9fc-11e7-8a47-f7caad2598c2.png">

This is the `.catch` after SSRing throwing an error.

**Comment by M-ZubairAhmed** [comment]
can i take a pick at this one ?

**Comment by mxstbr** [comment]
@M-ZubairAhmed sure! :100:

**Comment by brianlovin** [comment]
I think this was closed in https://github.com/withspectrum/spectrum/pull/4407 cc @mxstbr
