### ISSUE TITLE
Improve rep feedback for users

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2184]
As we discussed yesterday, we should introduce some more rep positive reinforcement for users. Some ideas from yesterday plus some more I had just now:

- [ ] Add rep increase/decrease to daily/weekly digest
- [ ] Add total rep + explanation dropdown on click to navbar
- [ ] Email on significant rep reached ("Congrats on 1000/10000/100000 rep in x community/total!")
- [ ] Show rep explanation on user page (inspired by StackOverflow)

Any more ideas? What are quick wins here? For reference on StackOverflow:

  <img width="1114" alt="screen shot 2017-12-09 at 12 34 19 pm" src="https://user-images.githubusercontent.com/7525670/33795209-a38535bc-dcdd-11e7-87b4-beba94159069.png">

**Comment by uberbryn** [comment]
I don't see this as a "big thing" in our roadmap. Nice to have, but unlikely to move any metrics IMO.

**Comment by mxstbr** [comment]
Rep is an amazing feature that helps understand the context of a conversation, on top of which it actually works pretty well as its implemented today—it's just not exposed meaningfully anywhere. It should be a core part of Spectrum, but feels like an afterthought right now, which is why I put it in the roadmap.

**Comment by mxstbr** [comment]
Case in point: https://spectrum.chat/thread/f330ebec-fe37-4a61-8983-8a3ab693cb8a

**Comment by brianlovin** [comment]
Agree that a day or two of work here could bring a lot of clarity to the features and make it feel useful and rewarding to people, versus right now being just an abstract number in the UI that people have to guess about. Not sure how to prioritize this still, but would love to keep it on the roadmap as well.

**Comment by uberbryn** [comment]
We discussed this during team standup and agreed that this fits into Moderation UI. Moving to a subtask of https://github.com/withspectrum/spectrum/issues/2451 which is already on the roadmap.
