### ISSUE TITLE
[Mobile v1] Splash page

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2329]
> Splitting up #1803 into multiple sub-issues to track against

We need a splash page you land on when you first install the Spectrum app. Some sub-todos:

- [ ] Login buttons

**Comment by mxstbr** [comment]
The homepage now has the sign in links and one can sign in/out, but it's missing GitHub and it's totally unstyled.

A PR adding styling similar to the web version (https://spectrum.chat/login) would be much appreciated! :pray:

**Comment by ryota-murakami** [comment]
@mxstbr sure, i'd like to take it:smiley:
i'm mid-level Web React/ReactNative dev & usually useing styled-components:nail_care:

**Comment by mxstbr** [comment]
Sure @ryota-murakami, all yours! The code for this screen is in `mobile/components/Login`, and the styling should afterwards look mostly like it does on the web today:

<img width="465" alt="screen shot 2018-04-11 at 17 02 39" src="https://user-images.githubusercontent.com/7525670/38625187-2f0a4078-3daa-11e8-8c94-def619e898e9.png">

**Comment by mxstbr** [comment]
@ryota-murakami let me know when you have a work in progress!

**Comment by ryota-murakami** [comment]
@mxstbr i'm afraid i couldn't complete the work immediately.

current progress is.. i just added github button, but nothing any styling.(actually i'v inactive the work for a while, during weekend:sweat_smile:)
![img_0858](https://user-images.githubusercontent.com/5501268/38821565-d5fc72f4-41db-11e8-8cbe-1adce7697353.PNG)

I would like to work this week with responsibility:bow:

i just created WIP PR https://github.com/withspectrum/spectrum/pull/2880

**Comment by ryota-murakami** [comment]
@mxstbr hello! this PR https://github.com/withspectrum/spectrum/pull/2880 is merge currently, but issue message's ckeckbox still empty.
is there any related task? i'd handle it if it is possile.

i'm looking forward to the mobile app:grinning:

**Comment by mxstbr** [comment]
No, this is perfect! Thanks so much for tackling this!

**Comment by ryota-murakami** [comment]
@mxstbr thank you:smile:
