### ISSUE TITLE
[Mobile v1] Thread feeds

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2330]
- [x] Feature request

> Splitting up #1803 into multiple sub-issues to track against

Once you're signed into Spectrum on mobile you should see your everything thread feed, and all the community and channels views will also mostly just show thread feeds, so we need to have some reusable thread components.

- [x] Thread card
  - [x] Basic implementation (done by @ArturKlajnerok) 
  - [x] Make sure all possible states are covered
  - [x] Fix padding and colors (@brianlovin)
  - [x] Overlay participant heads on top of each other (like we do on the website!)
- [x] Subscribe to new threads
- [x] Pull to refresh
- [x] Infinite scrolling thread feed (#2333)

**Comment by mxstbr** [comment]
The ThreadCard kind of exists now, but it's not very nice and it's missing a ton of information:

<img width="539" alt="screen shot 2018-04-11 at 14 06 21" src="https://user-images.githubusercontent.com/7525670/38615883-7ed478ca-3d92-11e8-83d7-17cc1971f15d.png">

PRs improving the styling and aligning the information presented with the web version would be much appreciated! :pray:

**Comment by ArturKlajnerok** [comment]
Hi @mxstbr, I can take a look at this one.

**Comment by mxstbr** [comment]
Thanks to @ArturKlajnerok in #2869 we're much closer already! 😍😍😍 

![](https://user-images.githubusercontent.com/1889095/38781710-d0685990-40e9-11e8-918b-f3af33c2cd7e.png)

Remaining todos:

- [ ] Make sure all possible states are covered
- [ ] Fix padding and colors (@brianlovin)
- [ ] Overlay participant heads on top of each other (like we do on the website)

**Comment by TheMightyPenguin** [comment]
Hey @mxstbr 😄 ! Has someone taken the `overlay participant heads` task? I'd like to give it a go!

**Comment by TheMightyPenguin** [comment]
@mxstbr Great 😃 I'll start working on it then

**Comment by TheMightyPenguin** [comment]
Hi there @mxstbr! I just got into this (sorry for the delay, haven't had much time lately), currently running the app in an iOS emulator (running expo, api, and iOS emulator), and even tho I've seeded the database and can see the threads in the Web app, I get this in the mobile app:
![image](https://user-images.githubusercontent.com/11748696/39655396-fd5698ac-4fbe-11e8-9bb0-eac28a242475.png)

Is there any extra step I'm missing here to get it working? The problem seens to be in `ThreadFeed.js` and `threadConnection` being null.

Thanks in advance!

**Comment by mxstbr** [comment]
@TheMightyPenguin that's very weird 🤔 If you open the web app does it show any threads on your home view?

**Comment by ryota-murakami** [comment]
@mxstbr hello! i'm interested `Make sure all possible states are covered` task, could i take this?(i don't know `all possible states` though:sweat_smile:)

**Comment by mxstbr** [comment]
@ryota-murakami yeah that'd be great! I'm not sure if all of them are covered right now, ideally you take a look at the threadFeedCard component in the web version (`src/components/threadFeedCard` I think) and make sure all the states we render there are also covered in the mobile version.

**Comment by TheMightyPenguin** [comment]
Hey @mxstbr Yes I can see threads on my home view, I got it working tho by doing the following on the web app:

1. Create a community
2. Create a thread on that community

Then once I started the mobile app again I was able to see the threads :+1:

**Comment by ryota-murakami** [comment]
@mxstbr i see, i'll compare it!

**Comment by mxstbr** [comment]
This is pretty much done apart from #3150 which will land soon, so I'll close this!

**Comment by ryota-murakami** [comment]
thanks, I'd like to help mobile ship followed by desktop🙌📱
