### ISSUE TITLE
[Mobile v1] Thread view

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2331]
> Splitting up #1803 into multiple sub-issues to track against

We definitely need to have a thread view and a way to respond to threads.

- [x] Thread content renderer (#2300) 
- [x] Bubbles
- [x] Share `sortAndGroupMessages`
- [x] Create reusable `<Messages />` component which takes a `data.messageConnection` prop. (same API as the `<ThreadFeed />` component which takes a `data.threadConnection` prop)
- [x] Share draftjs utils
- [x] Native message renderer
  - [x] Mentions decorator
  - [x] Links decorator
  - [x] Text message renderer
- [ ] Infinitely load messages with smart pagination
- [x] Message replies
- [x] Reactions
- [x] Chat input
  - [x] Mobile text input
  - [x] Parse plain text as markdown to DraftJS content in the API (done in #2836)

**Comment by alejandronanez** [comment]
Hey @mxstbr, is this issue up to date? I see that https://github.com/withspectrum/spectrum/issues/2332,  https://github.com/withspectrum/spectrum/issues/2330, https://github.com/withspectrum/spectrum/issues/2329 have an ongoing conversation but this is being quiet for a while.

What's a good place to start working on the `Thread View`? If you think it's ok to work on any other part of the issues mentioned above that would be great too :)

PS. What about moving this into its own project? I guess you've already thought about this but it's worth asking :)

**Comment by mxstbr** [comment]
@alejandronanez yeah this is all still up to date, those things are still missing! Any help appreciated :pray:

**Comment by alejandronanez** [comment]
OK @mxstbr!

I'll take a look at the mobile version tomorrow and see what's up! The `Reactions` task looks good like a good starting point.

Thanks,
