### ISSUE TITLE
[Mobile v1] Notifications

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2332]
> Splitting up #1803 into multiple sub-issues to track against

People need to be able to see their notifications and get them as push notifications in real-time.

- [x] Push notifications (#2366)
- [ ] Handle push notifications from the mobile ReactNative code
- [x] Notification view
  - [x] All notification types
  - [x] Infinite scrolling list (#2366)

**Comment by mxstbr** [comment]
@homanp moved from #1803 

> Ah, ok. Misunderstood then. Again I would be glad to help you out with that as well. Do you have any specific documentation on how you want to handle the notifications?

If you're talking about rendering them in the notifications tab, they should really just look like they do on the website. If you're talking about handling them while the app is open, I really don't know! Maybe it should show a dropdown with the content that can be clicked on and links to the relevant content?

<details>
  <summary>Click to see screenshots of some notification types on the website</summary>

<img width="664" alt="screen shot 2018-04-11 at 14 45 40" src="https://user-images.githubusercontent.com/7525670/38617351-15962e6c-3d97-11e8-9b6c-64549293c9d2.png">
<img width="670" alt="screen shot 2018-04-11 at 14 45 28" src="https://user-images.githubusercontent.com/7525670/38617352-15b6cc44-3d97-11e8-8716-9736ae5ef4df.png">

</details>

**Comment by homanp** [comment]
@mxstbr ok got it.

**Comment by homanp** [comment]
@mxstbr I was referring to when a the app is open and the push notif arrives. Not the actual notification view. Do you have a design for that as well on web?

**Comment by mxstbr** [comment]
Oh sorry, I misunderstood—yes, those mockups look great for the dropdown! 😍

**Comment by homanp** [comment]
Ok, cool. I'll give a try to see how it works out. Do you guys primarily communicate on Github for this project or do you have a Slack channel or similar?

**Comment by mxstbr** [comment]
A Slack channel? I hope you mean a Spectrum community :wink:, and yes we do: https://spectrum.chat/spectrum/open

**Comment by homanp** [comment]
Haha, yeah sorry! Thx 😄

**Comment by brianlovin** [comment]
cc @uberbryn for any design feedback on those in-app notif dropdowns :)

**Comment by homanp** [comment]
Copy that :)

**Comment by uberbryn** [comment]
I'd prefer to do a toast similar to Twitter with a spectrum purple bg, white text, and a white icon.

There's a few reasons I think this is the right approach:

1. it's as close to the notifications icon as possible
2. it takes up minimal space while using other functions of the app
3. it's high contrast against the background, *and* has good color contrast (AA) with the text

The one obvious issue here is that the icons will need some adjustment to fit this context better.

![image](https://user-images.githubusercontent.com/4926824/38697150-0b51e98c-3e46-11e8-91be-a726bf7bece1.png)

Inside the Notifications view, I think we'll use the existing notifications design for now (though that could also use an update)

**Comment by uberbryn** [comment]
This seems like it'd probably be a good candidate for addition to the README. Perhaps as a Figma file 🤔.

I'll see what I can come up with!

**Comment by mxstbr** [comment]
That would make for a great doc! `docs/design/readme.md` maybe?

**Comment by homanp** [comment]
@uberbryn yeah  a README would definitely help. So we go with Twitter-ish Toast notification bar?!

**Comment by mxstbr** [comment]
Yep, that'd be great @homanp!

**Comment by homanp** [comment]
Cool, going for it then 😄

**Comment by homanp** [comment]
@mxstbr @brianlovin  so I implemented everything for a device to start receiving notifs. I have some questions though: 

1. Are you guys saving the `ExponentPushToken ` somewhere? If not this needs to be saved in order to send notifications to a specific device. 

2. Have you got any examples of the payload you will be sending as push notifs to the client?

Thanks!

**Comment by mxstbr** [comment]
@homanp 

1. Yes, the backend is already pushing notifications out if you register with a token
2. Yes, in the `expoPushSubscriptions` table!
3. Let me dig in, one second
