### ISSUE TITLE
Slider Composer

### ISSUE THREAD

**Issue by superbryntendo** [withspectrum/spectrum#2406]
We need a global button for composing and the profile composers are kinda janky now since they're designed to be cards, but we're no longer using cards...

Let's make the composer open in the slider outside of the inbox view and use a global/local model, similar to Twitter's where:
- If you hit the "global" button (theirs is in the navbar), it populates the dropdowns normally
- If you hit the "local" button (on a user's profile), it populates the dropdowns with your current location

I think this would end up being a nicer experience on mobile as well since the slider is nicer than the composer there. Would also be possible to open in a new compose window perhaps in Electron.

**Comment by brianlovin** [comment]
We did this #4575 !
