### ISSUE TITLE
Thread composer is barely usable on mobile

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2492]
@mogsie just pinged me about this regression on alpha.

Before: ![](https://spectrum.imgix.net/threads/187d03aa-283c-49b4-ad6a-d735f2a1b9fa/Screenshot_20180306-202933.png.0.5408373798633948)

After: ![](https://spectrum.imgix.net/threads/187d03aa-283c-49b4-ad6a-d735f2a1b9fa/Screenshot_20180306-201243.png.0.043197086918179695)

Notice how the navbar makes it so you can basically see nothing of what you're typing.

**Comment by brianlovin** [comment]
I think this will be partially helped if we move community/channel selection to a second step

**Comment by uberbryn** [comment]
We could also maybe hide the chrome most of the time and have it slide in when scrolling up a la Safari's browser chrome?

**Comment by brianlovin** [comment]
We could save 48dp by removing the titlebar and having a floating 'back arrow' in the top left corner. Could save another ~16dp by not having top/bottom padding on the community and channel selectors, and just making them basically half-width dropdowns flush at the top. And save another 48dp by removing the bottom navigation tab bar when viewing the composer.

**Comment by brianlovin** [comment]
Huge improvements in the last couple weeks, and #4629 will wrap it up
