### ISSUE TITLE
Truncate link attachments

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2572]
<img width="429" alt="screenshot 2018-03-13 10 17 25" src="https://user-images.githubusercontent.com/1923260/37358225-c5dddccc-26a7-11e8-9d73-2d12f6d3eb6a.png">

**Comment by dev-drprasad** [comment]
@mxstbr @brianlovin Is this issue still pending ? can i work on this ? If yes, i would go with adding `ellipsis` at the end.

![screen shot 2018-04-05 at 11 08 32 pm](https://user-images.githubusercontent.com/22687681/38382085-740df224-3926-11e8-9557-cbeb4c988a5a.png)

**Comment by brianlovin** [comment]
Yep, that would be ideal! It's just a finicky css thing I think. And maybe we can get that link icon centered with the text, too :P
