### ISSUE TITLE
When cancelling a post, no thread is selected.

### ISSUE THREAD

**Issue by uberbryn** [withspectrum/spectrum#2595]
![image](https://user-images.githubusercontent.com/4926824/37550657-3e95f110-294e-11e8-9761-99550f615c88.png)

**Comment by denichodev** [comment]
Should this select the last thread selected, or the first one? @mxstbr

**Comment by mxstbr** [comment]
Good question, probably the last one selected?

**Comment by brianlovin** [comment]
Agreed - previous one selected would make the most sense, but is harder to do than just selecting the first in the list

**Comment by denichodev** [comment]
Should be fixed by https://github.com/withspectrum/spectrum/pull/2736

**Comment by brianlovin** [comment]
🎉🎉🎉
