### ISSUE TITLE
Unsent message shows up in all chat inputs

### ISSUE THREAD

**Issue by uberbryn** [withspectrum/spectrum#2610]
I typed a message into the DM input and opened a new tab to look at a different thread and the message popped up in the new thread too.

**Comment by cutjavascript** [comment]
@mxstbr , if message is attached to the key of thread id, would it not occupy lots of space in local storage, for each new tab would have its own text. Could it be optimised?

**Comment by brianlovin** [comment]
@cutjavascript yeah we should have some way of expiring those over time; but definitely agree that this is actually becoming quite an annoying bug to have the chat input persist across all threads, especially persisting into DMs

**Comment by brianlovin** [comment]
Closing in favor of #2723
