### ISSUE TITLE
Mention typeahead

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2649]
We need typeahead that shows suggestions of folks to mention.

**Comment by cutjavascript** [comment]
Can you give a suggestion, or preference of what you would like it to function like.

Where do we want it ?

Are we planning on using -> http://twitter.github.io/typeahead.js/examples/

**Comment by mxstbr** [comment]
We should probably just use the DraftJS mention plugin, since that has everything we need out of the box.

**Comment by satyarohith** [comment]
@mxstbr How can we get users data of a specific community? so we can store them in an array and use those to suggest.
I'm messing with this feature but not there yet, I will do PR once I get there. :)

**Comment by mxstbr** [comment]
I think the first version of this should just suggest any user on Spectrum, which should allow you to use the existing `search` query: 

https://github.com/withspectrum/spectrum/blob/alpha/shared/graphql/queries/search/searchUsers.js

We can look at more specific filtering (only community members, prefer thread participants, etc) later!

**Comment by rubenmoya** [comment]
I'd love to give this a try!

**Comment by mxstbr** [comment]
@rubenmoya coordinate with @satyarohith!

**Comment by satyarohith** [comment]
@rubenmoya Please go ahead!! I failed to retrieve data from the server but I was able to integrate Draftjs mention typeahead plugin. Sorry for not updating the status, I am completely busy with my exams.
I will join you guys sooner, Once again I'm extremely sorry for not updating status.

**Comment by rubenmoya** [comment]
Don't worry @satyarohith, I'll give it a try, good luck with your exams!

**Comment by AlexMunoz** [comment]
...  can i take this issue ?

**Comment by brianlovin** [comment]
@AlexMunoz for sure ✨

**Comment by AlexMunoz** [comment]
i'm back ... i'm trying to get the users, but if i use the querie that @mxstbr suggest, algolia credentials are needed ... or am i wrong?

**Comment by brianlovin** [comment]
Ah...yikes. That's frustrating, not sure how to best help another dev work on this without exposing our algolia creds (which we definitely shouldn't do :P)

It's a pain to do, but a workaround here would be to just fake a search result payload in the api resolver for testing purposes.

**Comment by dan-weaver** [comment]
Is anyone else working on this still? Not promising anything but would like to see where I can get but don't wanna start if it's still being worked on.

In regards to the search functionality. Doesn't seem to be something that couldn't be stubbed out well enough.  Maybe a couple utilities for doing so could be part of this PR.

**Comment by AlexMunoz** [comment]
I've something but it needs time... @dan-weaver go for it! 👍

**Comment by brianlovin** [comment]
Shipped!
