### ISSUE TITLE
Fallback Android composer

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2680]
Just making an issue to make this official: given that our chat input and thread composers break pretty significantly on certain versions of android mobile, let's provide a fallback in some way so that users can type markdown on the frontend and we parse it into draft on the server.

Maybe quick win is to do this only on the chat input so we don't have to worry about all the thread composer edge cases, thread editing, etc.

**Comment by brianlovin** [comment]
@mxstbr if all your tests are looking good on alpha, feel free to close this :)

**Comment by mxstbr** [comment]
Looking great, just some small styling fixes to come. Let's still keep this open for the main composer.
