### ISSUE TITLE
Dynamically create meta images for threads

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2682]
Imgix has [a neat text API](https://docs.imgix.com/apis/url/typesetting-endpoint/~text) that lets one generate an image from some text. We should use this and set the `twitter:image` meta tag on thread views to an image of the thread title + maybe the number of messages in the thread.

For example, click this link: http://assets.imgix.net/~text?txt=Test&txtclr=4B5E75

**Comment by alejandronanez** [comment]
I'd like to work on this @mxstbr 
Where should I start looking?

**Comment by mxstbr** [comment]
Awesome! In `src/views/thread/index.js` you'll see a `<Head>` component being rendered.

https://github.com/withspectrum/spectrum/blob/8eb1a8114dbaefa82914eb4f5cfe9523864e8d0e/src/views/thread/index.js#L380-L386

That `image` prop needs to be updated to some dynamically generated imgix link, which would ideally show:

- The Spectrum logo
- The community and channel name the thread was posted in
- The thread title
- The thread author
- Optionally: how many responses the thread has, if there are any

For example, here is what dev.to's automatically generated images look like:

<img width="591" alt="screen shot 2018-04-12 at 09 51 41" src="https://user-images.githubusercontent.com/7525670/38663487-349cc0c8-3e37-11e8-917c-bcbd6239fa90.png">

This is a quick and very dumb mockup of what ours should kinda look like with lots of information missing:

<img width="512" alt="release notes" src="https://user-images.githubusercontent.com/7525670/38663831-44e3903c-3e38-11e8-8653-2e3d38e51054.png">

@uberbryn can probably give you an actual mockup later, this should be enough to get you started though! 

> Note: I don't know whether you can tackle this without access to our imgix account, if not let me know!

**Comment by brianlovin** [comment]
That seems like an awesome starting point! We'll definitely want to trim at a certain # of chars and figure out how things like `break-word` should work :)

**Comment by mxstbr** [comment]
Yeah for sure, there's a looot of edge cases to be handled there but it could really help our click-through rate from Twitter

**Comment by alejandronanez** [comment]
Wow thanks a lot!
I’ll hit you up if I need something else :)

**Comment by uberbryn** [comment]
I'll add mockups for this to my to-do list for next week.

**Comment by alejandronanez** [comment]
Hey all!
In `spectrum/src/views/thread/index.js` around line 360 we have this conditional:

```js
if (thread.watercooler)
        return (....)
```

I don't see any `watercooler` type of thread in the default Spectrum community so I decided to create my own community to start playing with everything I need. What is happening is that I can't create a watercooler type of thread 😱

What am I missing here?

Thanks a lot!

**Comment by mxstbr** [comment]
Watercooler threads are currently an alpha experiment, you can see one in e.g. the React community: https://spectrum.chat/react

I wouldn't worry about those now, let's get those done later?

**Comment by alejandronanez** [comment]
Oh yeah! I thought this ticket was related only to Watercooler type of posts, sorry my bad.

I’ll keep working on this then :)

Thanks!

**Comment by mxstbr** [comment]
I guess let's start with only the title for now, and iterate when we figure out how to add multiple texts to images 🤷‍♂️
