### ISSUE TITLE
Composer doesn't set defaults correctly on community view

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2683]
https://spectrum.chat/thread/2d161ec7-ff9a-4106-8df3-3109f929f238

**Comment by spartDev** [comment]
Hi, 
Are you sure the bug still exists? 
Maybe I misunderstood but currently when user starts a new conversation it is by default in the community.

<img width="1674" alt="screen shot 2018-04-04 at 20 46 16" src="https://user-images.githubusercontent.com/531935/38327762-52c8241e-3849-11e8-8d18-9e274045a369.png">

**Comment by mxstbr** [comment]
Hmm, maybe it didn't default to the right channel on the channel view? /cc @probablyup

**Comment by probablyup** [comment]
Seems to primarily manifest on mobile.

**Comment by mxstbr** [comment]
Would love a PR fixing this for sure! The most likely culprit are the `composer` or `threadComposer` components. (I forget which one is used on mobile)

**Comment by spartDev** [comment]
i'm on it ! if I have questions I'll come back to you

**Comment by brianlovin** [comment]
On mobile I'm pretty sure we just push to the url `/new/thread` which removes the url params that are used to set the active community/channel - might need to modify that url in some way on mobile, or figure out how to push some state into that view if you're entering it from a community view

**Comment by mxstbr** [comment]
Oh right, that's it @brianlovin—I totally didn't consider that case when building that logic 🤔  Maybe we need to sync active community/channel to Redux or something?

**Comment by brianlovin** [comment]
Yeah, maybe something like that - although we don't want the flow of:
- viewing a community view, set active community to 'Foo'
- go to home inbox view, have active community set to 'Foo'

Going to the home inbox should always preserver the previous inbox state, or default to 'Everything'

So I think it might require new fields in the redux store if we want this to be global state?

**Comment by spartDev** [comment]
@mxstbr @brianlovin I take a look at the code. On mobile like Brian said we push to `/new/thread`.
I don't exactly understand why correct community is not set, we have the `activeCommunity` in redux with the correct uuid. 
And from what I understand the composer view subscribe to the `activeCommunity`.
Sorry if all this is unclear I just discover the app.

**Comment by mxstbr** [comment]
Huh interesting, so we already have that info! Sounds like the bug might be in the composer component not taking the `activeCommunity` from Redux correctly into account?

**Comment by spartDev** [comment]
yes we have that info.
it's weird only appears on mobile

**Comment by mxstbr** [comment]
That makes sense because on the web when you're on a community view the URL is /community, which the composer takes into account. On mobile though the URL changes to /new/thread, which means the composer can't take that into account anymore.

**Comment by spartDev** [comment]
@mxstbr OK found it ! On mounting composer call `this.handleIncomingProps(this.props)`, on mobile like you said the url change and the composer can not access to the props.

**Comment by brianlovin** [comment]
We fixed this on the community view, but now it's broken on the inbox view. I have a to-do list to fix this.
