### ISSUE TITLE
Improve DM empty state

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2684]
Reported by @webdesserts, the empty state for DMs is pretty un-explanatory rn: https://twitter.com/webdesserts/status/980789327906172928

That could certainly be improved!

**Comment by spartDev** [comment]
Hi,
Can I have more details on this. do you have any idea what you would like to see ?

**Comment by mxstbr** [comment]
Not really! /cc @uberbryn any ideas what the copy should be there?

**Comment by uberbryn** [comment]
I think I'd probably add a state similar to the locked thread state, but with a `message` icon and probably some text mentioning that these are private messages between you and anyone else on Spectrum.

The `<NullState>` component might be useful for this.

My first pass idea on copy would be something like...

Title: "Sometimes you want a little privacy..."
Copy: "We know that not everything you want to say should be public. Direct Messages are private chat conversations between you and any other user(s) on Spectrum - even groups!"
