### ISSUE TITLE
Notifications broken

### ISSUE THREAD

**Issue by denny64** [withspectrum/spectrum#2706]
I have enabled Chrome notifications and have tried sending messages to a friend. Neither of us received the notification. Also no in-app notifications (https://spectrum.chat/notifications) either. Is it broken?

**Comment by mxstbr** [comment]
Athena's very backlogged at the moment (6000 waiting jobs), so notifications are a bit delayed. Sorry for the troubles, I'm investigating!

**Comment by mxstbr** [comment]
I'm redeploying, it seems like something got stuck—athena's not processing any jobs rn.

**Comment by mxstbr** [comment]
I really need to fix #2471 so we can scale athena again...

**Comment by denny64** [comment]
@mxstbr Thanks! I'll close this since its a duplicate of #2471
