### ISSUE TITLE
Cannot load images in thread at times, blob error

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2725]
@mxstbr I opened https://spectrum.chat/?t=5fcc10ab-e5a5-4027-bf8a-cd948ff8e092 in my dashboard and got this error:

<img width="1679" alt="screenshot 2018-04-04 18 57 48" src="https://user-images.githubusercontent.com/1923260/38343699-48281c58-383a-11e8-82ab-4196cd3a04c3.png">

The blob error there is what prevented the image in the thread from loading. A refresh fixed it and the image loaded in the thread.

Will look for consistent repro steps.

**Comment by mirko77** [comment]
I do not know if this is related, but sometimes image urls do not work.

For example https://spectrum.imgix.net/threads/draft/465bfd3e-5fb0-4eca-a3e5-bb1689aabe2e-Screen%252520Shot%2525202019-02-18%252520at%25252010.05.31.png?expires=1550016000000&ixlib=js-1.2.0&s=1eab0447b543b335d79b6603257e0cb5?expires=1550016000000&ixlib=js-1.2.0&s=b7774f9d7758ac90f7e10ae3db2d0974

from [this](https://spectrum.chat/spectrum/general/show-link-previews-when-pasting-links~35e2bea8-b89a-4921-8625-f86c0729608b) thread

**Comment by brianlovin** [comment]
@mxstbr the image is getting double signed. This is most likely a bug with editing where we continually persist the previously-signed image url in the thread body.

**Comment by brianlovin** [comment]
Fixed
