### ISSUE TITLE
Profile buttons should line up

### ISSUE THREAD

**Issue by mknepprath** [withspectrum/spectrum#2733]
**Issue Type (check one)**

- [X] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** -->
<img width="354" alt="screenshot 2018-04-05 00 49 01" src="https://user-images.githubusercontent.com/1000280/38349145-4b642b56-386b-11e8-889e-ccfc4ab989a8.png">

These buttons are weirdly spaced and inconsistent widths - I'm guessing they shouldn't be?

**Comment by brianlovin** [comment]
Yikes - that section is a bit of a mess, good spot :)

**Comment by mknepprath** [comment]
I had a hunch it was something like that 😉

**Comment by Glazy** [comment]
Since you can no longer upgrade to 'Pro' (as of the Github acquisition) this is no longer a bug that we need to worry about :+1:

**Comment by mxstbr** [comment]
Good catch, thanks @Glazy!
