### ISSUE TITLE
Image is still accessible in the preview panel after deletion

### ISSUE THREAD

**Issue by satyarohith** [withspectrum/spectrum#2734]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

preview panel shows deleted images.
 
![preview panel](https://user-images.githubusercontent.com/29819102/38360930-5251d0a2-38e9-11e8-870e-831c77adbbd9.jpg)

**Comment by brianlovin** [comment]
Yikes, thanks for the report. Going to fix this asap.

**Comment by brianlovin** [comment]
Fix submitted.
