### ISSUE TITLE
Handling spam communities

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2743]
Our SEO is getting good. Which means people will start spinning up things like this: https://spectrum.chat/cbd-oil?thread=2d09eb88-434a-4c0d-8181-a47667ee5ef3 to try and get Google karma for the links. 

How do we want to handle spam communities + threads like this?

**Comment by mxstbr** [comment]
Good question, I wonder what other user-generated content sites are doing about that

**Comment by brianlovin** [comment]
Probably nothing, as a lot of other ugc sites are ad-driven, so pageviews === good.

I'm not sure there's anything here to do immediately, except watch for patterns here. If it starts to scale people will trust our content/platform less in general.

**Comment by satyarohith** [comment]
[These](https://webmasters.googleblog.com/2017/01/protect-your-site-from-user-generated.html) might be few best practices.

but there should be an efficient way to handle spam at scale.

**Comment by brianlovin** [comment]
Quick wins from that post (thanks @satyarohith!)
- rate limit # of threads that can be posted in a given time period
- rate limit # of messages that can be posted in a given time period
- add nofollow to links posted in chat messages

Bigger tasks that we need anyways:
- community option to approve all incoming threads before they are published
- implement additional spam detection systems like akismet (https://github.com/cedx/akismet.js) - we'll just need to handle false positive cases so people don't lose content they post if it is legitimate
- add ability to block user from spectrum at a system level

Biggest task that would be nice to have:
- internal admin page that collects all inbound toxicity + spam reports, with quick actions for deleting + blocking content

**Comment by mxstbr** [comment]
> add nofollow to links posted in chat messages

I think we already do this?

**Comment by mxstbr** [comment]
This ties into #2451, right?

**Comment by brianlovin** [comment]
> add nofollow to links posted in chat messages

do we? unsure

**Comment by brianlovin** [comment]
Good call on #2451 - will build on top of that

**Comment by brianlovin** [comment]
First draft to work on this going out in #2758
