### ISSUE TITLE
Fix plural '1 new messages' in email subject lines for new replies in thread

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2745]
Ref: https://spectrum.chat/?t=1028ccd2-a70c-4a81-b35c-efc03527174a

**Comment by satyarohith** [comment]
```
const preheader = `View ${newMessagesLength === 1 ? `1 new message from ` : `${newMessagesLength} new messages from `}${firstName}${preheaderSubtext}`;
```
will this work?

**Comment by brianlovin** [comment]
Looks like it!

**Comment by satyarohith** [comment]
I was in doubt because will hermes send new email for every new message or will it bundle multiple new messages (if any) from same sender and send it once?

**Comment by brianlovin** [comment]
Athena does the work of bundling up messages in a given time period. Once the job hits hermes its already gone through the bundling logic, so it just needs the content to be formatted :)

**Comment by brianlovin** [comment]
If it's helpful, think of Hermes as the last mile in the pipeline; we don't even have a db connection on that server because each email job should receive all the data it needs. So hermes just handles things like content formatting, generating unsubscribe links, and occasionally provides an escape hatch to abort sending an email.

**Comment by satyarohith** [comment]
got it! :)
