### ISSUE TITLE
@ symbols in medium urls break link detection in threads and messages

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2754]
Ref: https://spectrum.chat/thread/e5a27d8b-60a1-4c7d-a7d1-bc0d627608e7

**Comment by nnennajohn** [comment]
@brianlovin If I want to contribute, how do I make sure I am not fixing an issue someone is already fixing? Sorry for spamming here. Could not figure out another way to ask. :)

**Comment by brianlovin** [comment]
Not spamming at all! AFAIK nobody is working on this - we should have some sort of label for “claimed”

**Comment by nnennajohn** [comment]
Ok. Cool. And def yes to a label of sorts. 👍 

Thanks.

**Comment by nnennajohn** [comment]
Ok. Cool. Let me take this. It will be my first open-source contribution though, so Intentionally looking for the smallest change. :) 

Quick question. What would be the general timeline to deliver once you commit?

**Comment by brianlovin** [comment]
Not sure! But I'd say if it starts pushing past a few days just ping here and we can try answer questions or pull in more people to help :)

**Comment by nnennajohn** [comment]
Ok. Perfect. Thank you!

**Comment by nnennajohn** [comment]
Ok. Working on this. Will get it in over the weekend. 

Quick question: My thought on how to proceed with this is to actually seperate what is displayed to the user, and the underlying url. I see there are a few checks to make sure the url is valid. So I am thinking we don't really need to change/strip anything. Rather pass an encoded version to the underlying href after any linkPreview is generated, and the original linkTest as the text value. 

What do you think @brianlovin ?

**Comment by nnennajohn** [comment]
Ok. I tracked down the problem. Sorry, had to navigate my way around the code. But I think the offending thing is the MENTIONS Regex. 

I am not quite sure how you want to proceed with it though. Ignore if weburl && regex match? New regex? Extract, but retain current text if weburl and regex match? 

<img width="651" alt="screen shot 2018-04-12 at 11 50 56 pm" src="https://user-images.githubusercontent.com/1761197/38720826-8b08aeca-3eac-11e8-879d-184827e29e46.png">

**Comment by mxstbr** [comment]
I think the quickest fix would be to not match a mention if it's preceded by a `/`, if that makes sense? So the Regexp should match `@someone` `Hello @someone` but not `/@someone`.

**Comment by nnennajohn** [comment]
Ok Thanks. @mxstbr. Regex is not my strongest point. :) 

Tried with an  / test prefix, and it works for a full url, but fails for an actual mention. :) 

<img width="651" alt="screen shot 2018-04-13 at 12 34 45 am" src="https://user-images.githubusercontent.com/1761197/38722380-9b7e3efe-3eb2-11e8-8c7c-fb62c3926691.png">

**Comment by Keraito** [comment]
Hey, @nnennajohn are you still working on this? Do you need some help or could I try my hands on this?

**Comment by nnennajohn** [comment]
@Keraito , hey. For sure. Sadly, my regex skills are really bad. :(  Would love to see the final result of what you do with it. 

Thank you. I appreciate you hitting me up about this. :)

**Comment by Keraito** [comment]
@mxstbr is there a quick way to run the unit tests in https://github.com/withspectrum/spectrum/blob/alpha/shared/test/get-mentions.test.js in isolated fashion, just wanna double check my solution but can't setup the whole project right now.

**Comment by brianlovin** [comment]
@Keraito try `yarn run test` and then when jest opens up you can specify a regex path pattern (i think the key is `p`) to run only certain tests :)
