### ISSUE TITLE
Allow pasting images into chat input

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2755]
Ref: https://spectrum.chat/thread/c1381a42-30dd-4a7a-a999-54b9be1cc65a

UX considerations: we need a way to preview images before they are sent to prevent people from accidentally pasting + sending an unintended image

**Comment by brianlovin** [comment]
This shipped today! Thanks so much @StefanNemeth :D

**Comment by dandv** [comment]
How exactly does this work?

I have an image in the clipboard right now, I can paste it here in this GitHub comment with Ctrl+V (Chrome on Linux), but neither Ctrl+V nor Shift+Ins paste it in this chat (post? I've just joined Spectrum, and find it a little confusing).

![image](https://user-images.githubusercontent.com/33569/49679765-a5212b00-fa42-11e8-9919-21b25daece7f.png)

Image I wanted to paste:

![Parcel test fails](https://user-images.githubusercontent.com/33569/49679758-9b97c300-fa42-11e8-9f09-b97c22ec3a4c.png)
