### ISSUE TITLE
Cannot clone your git repository

### ISSUE THREAD

**Issue by jakesullyneytiri** [withspectrum/spectrum#2760]
Trying to run following cmd git clone git@github.com:withspectrum/spectrum.git but all i get is following error

Cloning into 'spectrum'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

It looks like you have blocked something from people to clone your git repisitory :/ could you please fix it?

/Thanks

**Comment by satyarohith** [comment]
@jakesullyneytiri use `git clone https://github.com/withspectrum/spectrum.git`.

**Comment by jakesullyneytiri** [comment]
yeah i tried that and it worked. So idk why document/instructions tells you todo  git clone git@github.com:withspectrum/spectrum.git instead :/

**Comment by jakesullyneytiri** [comment]
found another problem :/ when i try to run "node shared/install-dependencies.js" it does nothing. Any clue why? first it said node is missing so i ran apt-get install node and then when i ran cmd again that when it did nothing.

**Comment by kultism** [comment]
You need to run `apt-get install nodejs`
More here in [node.js docs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

**Comment by kultism** [comment]
Well, I'm not sure about `node` and `nodejs` in Debian-like systems, but you can try to use [nvm](https://github.com/creationix/nvm) 👌

**Comment by jakesullyneytiri** [comment]
well i tried apt-get install nodejs-legacy this time on new clean install and did other stuff. 

But now all i get is this "/root/spectrum/shared/install-dependencies.js:2
const { readdirSync, statSync } = require('fs');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
"

**Comment by mxstbr** [comment]
@jakesullyneytiri sorry for the troubles here, thank you for helping us in figuring out how to make the system work across OS's!

That last bug sounds like your version of Node doesn't have support for destructuring yet. What v of Node are you on? (`node -v`)
