### ISSUE TITLE
Use helmet to protect our Node servers

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2775]
We should use Helmet to protect our servers and users from some common attack vectors: https://expressjs.com/en/advanced/best-practice-security.html#use-helmet

**Comment by Mesod** [comment]
I am going to add it. Should I just add helmet for all the connection?

**Comment by mxstbr** [comment]
I think some of those protections will break our server, I'm not sure this will be super easy—please try though!
