### ISSUE TITLE
Implement rate limiting for our Node servers

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2776]
We should rate limit all our Node servers requests with something like https://www.npmjs.com/package/express-limiter

**Comment by brianlovin** [comment]
Also https://github.com/tj/node-ratelimiter might be a good one, backed by redis

**Comment by mxstbr** [comment]
I'd go with the user ID first, and then the IP second if it's an unauthenticated user.

**Comment by LetItRock** [comment]
What should be max amount of requests to API and in what time frame?

**Comment by mxstbr** [comment]
Not sure! Any ideas?

**Comment by LetItRock** [comment]
PR #2789
