### ISSUE TITLE
Implement rate limiting of GraphQL mutations

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2777]
We should rate limit our GraphQL mutations. Apart from the changes in #2758, mutations should have general rate limits configured in the schema to avoid excessive automatic spam from bots who call our API 20 times a second.

Those could look something like this:

```GraphQL
type Mutation {
  addMessage: Message        @rateLimit(perMinute: 20)
  publishThread: Thread      @rateLimit(perMinute: 5, perHour: 100)
  createCommunity: Community @rateLimit(perMinute: 5)
  createChannel: Community   @rateLimit(perMinute: 5)
  createDMThread: DMThread   @rateLimit(perMinute: 5)
}
```

> Note: not sure about that API just yet, gotta bikeshed it.

- Are there any packages that implement this already? Couldn't find any
- What should the API look like?
- Where do we store the counts? Redis
- There's gotta be existing non-GraphQL-specific solutions, how do those work?

**Comment by mxstbr** [comment]
We want the API to be as flexible as possible. Initially I though it'd be neat to restrict it to a single unit of time, but there is a large difference between "100 mutations per 100 minutes" and "1 mutation per minute", so for full flexibility the user has to be able to set both the time and the limit.

With that in mind, what about this API?

```GraphQL
type Mutation {
  # You can call this mutation at most 20 times per minute
  addMessage: Message @rateLimit(limit: 20, window: 60000)
  # This one at most once per 500ms
  addMessage: Message @rateLimit(limit: 1, window: 500)
}
```

Not sure whether "window" is an intuitive name, there's probably a better one I'm not thinking of. Also, calling `@rateLimit` with `limit` argument is a bit awkward, maybe that should be `amount` or `calls` instead? Not sure.

**Comment by mxstbr** [comment]
Also, not sure whether this is best implemented as a validation rule (similar to `graphql-cost-analysis`) or as a custom schema directive. Probably a validation rule.

**Comment by brianlovin** [comment]
Hm, this is for the platform as a whole? Or per user?

If it's for the platform as a whole, won't this break as we grow? E.g. we'll always be bumping into these limits as we add more users and communities, thus having to increase the limits here, thus defeating the purpose of catching one bad spam actor?

Otherwise, I know nothing about rate limiting. What about https://github.com/tj/node-ratelimiter by @tj?

**Comment by mxstbr** [comment]
Per-user. We can't use any existing rate limiting solutions because those only rate limit Express routes—but while it's fine to call the `/api` route 20 times in a second it's not fine to call `addMessage` 20 times in a second, which is why we need a GraphQL-specific solution!

**Comment by LetItRock** [comment]
Github has implemented GraphQL resource limitations and [here](https://developer.github.com/v4/guides/resource-limitations/) you can read about it, very interesting approach.

**Comment by mxstbr** [comment]
We already have something similar, we do both complexity analysis and depth limiting. (see [this blog post I wrote about it](https://dev-blog.apollodata.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b)) This issue is slightly different in that it's specific to mutations—while calling `addMessage` isn't very "expensive" (from a complexity analysis standpoint), you'd never want anybody running it 20 times a second.

**Comment by mxstbr** [comment]
Somebody's finally built this so we don't have to anymore!! https://www.npmjs.com/package/graphql-rate-limit

**Comment by garysdevil** [comment]
> Somebody's finally built this so we don't have to anymore!! https://www.npmjs.com/package/graphql-rate-limit

Do I have any ways to use graphql-rate-limit only by express-graphql ?
