### ISSUE TITLE
Validate DraftJS input

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2792]
We should validate the serialized DraftJS state that people send to the API `publishThread` and `addMessage` mutations. @flarnie are there any existing libraries/utilities that will quickly let us verify something is valid raw DraftJS content state?

**Comment by flarnie** [comment]
Hi @mxstbr - I don't know of any solutions for this off the top of my head.

**Comment by brianlovin** [comment]
This won't be needed anymore after #4629
