### ISSUE TITLE
Prevent null text from more user inputs

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2796]
<img width="1680" alt="screenshot 2018-04-09 10 09 17" src="https://user-images.githubusercontent.com/1923260/38511787-1ef8e6da-3bde-11e8-9c5b-b0d301582141.png">

Looks like it's possible to have empty:
- community name
- community description
- channel name
- channel description
- thread title
- user name

We need to validate inputs better to ensure content exists, including checks for zero width spaces

**Comment by brianlovin** [comment]
We should be checking for soft hyphens as well https://en.wikipedia.org/wiki/Soft_hyphen

**Comment by brianlovin** [comment]
And specific unicode chars like https://unicode-table.com/en/#FFF8

**Comment by brianlovin** [comment]
@cutjavascript good question, I'm still not sure how these catches were bypassed; I think it was probably just inserting some special zero width unicode chars or something

**Comment by connelle1** [comment]
@brianlovin I am brand new to github, and I want to start contributing any way I can. I noticed there are a lot of issues on this repository and I was wondering if there are any in particular that would be good for a beginner to tackle. I have a basic understanding of HTML, CSS, and JavaScript and want to know more.

**Comment by brianlovin** [comment]
@conelle1 there is a label in the issues view called “good first issue” which you can filter by 😊

**Comment by dev-drprasad** [comment]
@brianlovin one suggestion from me (If applicable). if we label issues with relevant skill (for example `ui`, `backend` etc), it will be good for people to pick/filter easily instead of going through each every issues and reading description.

**Comment by brianlovin** [comment]
cc @mxstbr - not sure if you have any thoughts on label structure here and how granular to go;

I definitely hear ya @dev-drprasad - only thing that concerns me is that a lot of tasks require a bit of a bunch of things, and might just make it super tedious. But also want to strike the balance where our labels are useful and helpful, too!

**Comment by dev-drprasad** [comment]
@brianlovin i totally agree. i have seen lot of issues with no or little description and label is not telling which kind of skills required. So, I thought beginners feel difficult to pickup issues.

**Comment by brianlovin** [comment]
For the issues with no description, most of those are probably legacy ones that we created a while back and definitely need extra context. I'll do a quick pass through the `good first issues` and see if I can help with that

**Comment by RehabHussein** [comment]
hi @brianlovin  if no one is working on this issue I would be happy to fix it !
One side question to make sure I am reproducing the same issue, does the UI changed from the above screenshot because that's how the community appears now for me 
![image](https://user-images.githubusercontent.com/15670284/62418764-d7d30000-b671-11e9-8164-90c2487e088d.png)

**Comment by brianlovin** [comment]
@RehabHussein yes the UI has since changed, but would love your help on patching this!

**Comment by taciosd** [comment]
Hi @brianlovin, I'm a experienced developer in java desktop apps trying to improve my web skills. I would like to contribute working on this issue.

**Comment by taciosd** [comment]
@brianlovin 
I added some regex to block community creation if the name or the description does not adhere to the rules. Needs more testing.
And I would like to know where should I put the two regex (whitespace, oddHyphen) to reuse them in other places, like to protect channel name, channel description, etc.
