### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by superbryntendo** [withspectrum/spectrum#2817]
- [x] Enable user to delete their data
- [x] Enable user to download their data (#3003)
- [x] Fix Google Analytics setup to be GDPR compliant (https://www.humix.be/en/blog/configure-google-analytics-for-gdpr/, #2985)
  - [x] Sign Google Analytics DPA
- [x] Fix Sentry to be GDPR compliant (https://blog.sentry.io/2018/03/14/gdpr-sentry-and-you)
  - [x] Sign Sentry DPA
- [ ] Handle consent
- [x] Terms and Privacy Policy need to be revised to be reader-friendly
- [x] Add self-service data processing agreement ([Mailchimp's](https://mailchimp.com/legal/forms/data-processing-agreement/sample-agreement/), [Sentry's](https://help.sentry.io/hc/en-us/articles/360002016354-Are-you-compliant-with-General-Data-Protection-Regulation-GDPR-))
- [ ] Maybe add cookie notice?
- [ ] Encrypt all private or user-identifiable user data on server?

**Comment by brianlovin** [comment]
> Encrypt all private or user-identifiable user data on server

Is this just email right now?

> Enable user to download and/or delete their data

Is this one or two tasks? For downloading, are there specific things that need to be included here? Or just PII (e.g. their record in our `users` table?) - or do they also need ability to download all threads, messages, etc?

> Terms and Privacy Policy need to be revised to be reader-friendly

Any gut feeling on how far off we are here? Wondering if there are templates coming out from other companies switching to GDPR that we could get insight from, or if it's worth hiring someone to knock this out in an hour versus us spending a long time worrying about it.

**Comment by mxstbr** [comment]
I think we also have to handle the ["Right to Restrict Processing"](https://gdpr-info.eu/art-18-gdpr/), which is basically just disabling your user account without deleting the data.

**Comment by mxstbr** [comment]
> I'd rather just say someone can delete their account or not. Having a disabled state is way more confusing, right?

No, that is different than the "Right to be forgotten": if you click the link above you'll see the scenarios in which a user needs to be able to disable their account.

We can probably just set `deletedAt` but keep their data and call it a day maybe?

**Comment by brianlovin** [comment]
I'm saying that we should not support that extra logic and surface area for unintentional violations of GDPR. If a user wants to restrict processing they need to delete their account. All of the cases in the link above give rights to the users to request data or fixes from us, but doesn't require us to build out extra logic to support a disabled state.

**Comment by brianlovin** [comment]
Overall all the points in that link tell me that a user can request us to halt processing (delete their account) at any time. Right?

**Comment by superbryntendo** [comment]
Completed as part of GitHub acquisition.
