### ISSUE TITLE
Add links previsualizations

### ISSUE THREAD

**Issue by Kikobeats** [withspectrum/spectrum#2820]
**Issue Type**

- [x] Feature Idea

**Description**

![eh571d15](https://user-images.githubusercontent.com/2096101/38606392-2dd18cf4-3d76-11e8-866d-f9e363ce624f.jpg)

I suggested to @mxstbr that it might be more or less easy to include preview links in threads.

I did a little demo using [Microlink SDK](https://github.com/microlinkhq/sdk) that is library ready for getting information from any link using [Microlink API](https://docs.microlink.io).

I know you have your own microservice (micro-open-graph) for getting links information, so you don't need to use the Microlink API. Actually, the SDK accept a [data](https://docs.microlink.io/sdk/getting-started/api-parameters/#data) param to allow pass your own data.

The component is built with styled-components. It ships a minimal style by default, but I suppose it should be adapted to work according to your design.

I open the issue to find the point where the code can be extended. Probably we can add links previsualizations in more part of the web but not sure 🙂

**Comment by brianlovin** [comment]
Definitely into the idea of expanding urls in messages - I'm not sure if we'd want to do that on the fly, or if we'd want to store some kind of `attachments` object for messages, similar to how we store link previews for `thread`s

**Comment by brianlovin** [comment]
We are getting started on this with #4683!
