### ISSUE TITLE
Cypress is failing to authenticate locally again

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2835]
I tried deleting the `testing` db, re migrating, and confirmed that our data is landing in the testing db. But all authentication in all tests is failing for some reason.

**Comment by mxstbr** [comment]
Yeah, it's saying "`cy.auth` is not a command". Digging in.

**Comment by mxstbr** [comment]
Welp, after restarting Cypress everything works again. Very very curious, no clue why! /cc @brian-mann

Going to close this for now, let's see if it happens again.

**Comment by brianlovin** [comment]
Kk I'll keep ya posted if I can get it to run locally with your latest changes in #2838
