### ISSUE TITLE
Switch cursor to pointer when hovering over embedded images

### ISSUE THREAD

**Issue by mknepprath** [withspectrum/spectrum#2841]
**Issue Type (check one)**

- [X] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** -->
I noticed that you can click on images to bring up a lightbox view - this isn't immediately obvious due to the cursor not changing. Perhaps it should?? Also #2624 

<img width="782" alt="screenshot 2018-04-12 14 05 58" src="https://user-images.githubusercontent.com/1000280/38698456-c003b806-3e5a-11e8-9ddd-c0ccc70c3f33.png">

**Comment by brianlovin** [comment]
Hmmm I don't think clicking on images in threads does anything right now though? See #1915

**Comment by mxstbr** [comment]
Yeah but images in messages

**Comment by brianlovin** [comment]
Ah, I thought he meant in thread. Sorry! This would be nice then for sure :)

**Comment by mknepprath** [comment]
I added an image above to clarify. Not clear on the distinction between threads and messages, but clicking on that brings up a lightbox view with all embedded images in that conversation.

**Comment by mknepprath** [comment]
@brianlovin I sure can!

**Comment by mknepprath** [comment]
PR in: #2848
