### ISSUE TITLE
Removing images in thread composer with DEL crashes app

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2842]
https://spectrum.chat/thread/557e4ed2-c2e5-43f8-bbce-ad4b7f8687e3

**Comment by lookapanda** [comment]
https://gist.github.com/lookapanda/441506569b2729d09971a0cf1417288a

**Comment by lookapanda** [comment]
https://github.com/mxstbr/draft-js-plugins/commit/db2d583d6f71d2ca8f7a51c400988be31feb15ce

Hm, seems like there was a similar bug already in the past but @mxstbr fixed that one already...but the description seems to still fit on this bug too?

**Comment by lookapanda** [comment]
Okay, can confirm now. I "fixed" it locally. What Max did to the `draft-js-image-plugin` needs to be repeated here: https://github.com/vacenz/last-draft-js-plugins/blob/master/draft-js-embed-plugin/src/index.js#L27

**Comment by mxstbr** [comment]
PR!

**Comment by lookapanda** [comment]
Done https://github.com/vacenz/last-draft-js-plugins/pull/15

**Comment by brianlovin** [comment]
Stale and irrelevant with plaintext composer, and will never be relevant when #4629 ships
