### ISSUE TITLE
DM thread crashes the app

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2853]
I just tried to DM @mogsie to get him to try alpha.spectrum.chat on Android, but when I sent the DM (I created a new thread because I couldn't be bothered to find the old one) the app crashed. Sentry log: https://sentry.io/space-program/spectrum/issues/527630247/?query=is:unresolved

On top of that, I now cannot open that DM thread anymore at all. What on earth.

**Comment by brianlovin** [comment]
Can you send me the dm thread id?

**Comment by brianlovin** [comment]
Can't repro locally

**Comment by brianlovin** [comment]
To clarify: are you able to view /messages at all? Or just only that thread is throwing an error?

**Comment by mxstbr** [comment]
I can view `/messages` if I navigate to it client-side, but when server-side rendered it always crashes. I can client-side navigate to any other DM thread.

DM thread ID in the screenshot:

<img width="1044" alt="screen shot 2018-04-13 at 14 09 26" src="https://user-images.githubusercontent.com/7525670/38739548-8f3f2382-3f35-11e8-9ba9-7ce8ba24f98e.png">

**Comment by brianlovin** [comment]
Can you paste that id pls bb

**Comment by brianlovin** [comment]
Can you also trigger the error again so it'll show up in hyperion.alpha logs?

**Comment by brianlovin** [comment]
Thanks - unfortunately we are still rate limited on Sentry so I can't get too much more info. I'm about to board a plane, so if this is totally breaking maybe you can try to run a db backup locally and debug there? sorry man!

**Comment by mogsie** [comment]
Just commenting that I've got the same issue on my end, if I open mxstbr's DMs, it goes straight to the error page.

```
SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.value (index.js:61)
    at u (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
```

unimified:

```
    const parsedMessage =
      message.messageType &&
      message.messageType === 'draftjs' &&
      toPlainText(toState(JSON.parse(message.content.body)));
```

**Comment by brianlovin** [comment]
@mxstbr could this possibly be an issue with the android text input fallback that saved invalid draft state to the db?

**Comment by mxstbr** [comment]
I don't think so, but potentially. I'll dig in today.

**Comment by mxstbr** [comment]
Hmm seems like a plaintext message slipped through somehow, it had a plaintext body but a `draftjs` type. Will see if I can repro.

**Comment by mxstbr** [comment]
Got it: #2876
