### ISSUE TITLE
Code block in chat input fixes

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2854]
Hey @mxstbr here are some bugs with the new code block stuff: https://www.dropbox.com/s/h9omj4q6bteoypi/code-blocks-chat-input.mov?dl=0

In order of appearance:
- [x] It was nice when code blocks would automatically activate with triple backticks at the start of a message. It's unobvious that you have to hit 'enter' to start the code block, and probably nobody will ever do it because 'enter' is what they expect to send the message
- ~~If the message starts with a code block it's not obvious how to exit it (it takes an extra backspace). But if I cmd + A to select all and hit backspace, I would expect it to also clear the code block~~ (moved: https://github.com/withspectrum/draft-js-markdown-plugin/issues/58)
- [x] The cursor jumping problem still exists - I ran `yarn` to get the latest packages, so this is current
- [ ] If you start a code block on the same line as other text it sends when you press enter, instead of activating the code block - in this case we have mixed the behavior of how to enter a code block vs send a message
- ~~If I completely wrap text in triple backticks it does not convert to a code block on send or automatically~~
- ~~If I completely wrap text in triple backticks and then press space, it only recognizes an inline code snippet within 2 backticks~~

**Comment by mxstbr** [comment]
These are all good points, will tackle!

**Comment by brianlovin** [comment]
Thank yoU!

**Comment by mxstbr** [comment]
Now that I think about it:

> It was nice when code blocks would automatically activate with triple backticks at the start of a message.

It would be kinda nice if code blocks would automatically activate with tripe backticks, no matter if you're at the start of a message or not, right?

**Comment by brianlovin** [comment]
Yep! It should always auto activate. Hitting enter to "activate" it feels pretty unintuitive since enter is also the send message key

**Comment by mxstbr** [comment]
> If the message starts with a code block it's not obvious how to exit it (it takes an extra backspace). But if I cmd + A to select all and hit backspace, I would expect it to also clear the code block

This is the case for all block types at the moment, including headings and lists etc.

> The cursor jumping problem still exists - I ran yarn to get the latest packages, so this is current

True that! /cc @juliankrispel

> If I completely wrap text in triple backticks it does not convert to a code block on send or automatically
> If I completely wrap text in triple backticks and then press space, it only recognizes an inline code snippet within 2 backticks

If we change the behavior for 1, both of these would be solved since it'd be obvious that you can copy+paste!

**Comment by mxstbr** [comment]
PR is up that makes ``` work with space too! withspectrum/draft-js-markdown-plugin#55

**Comment by mxstbr** [comment]
Implemented in the app here: #2863 Onwards to tackling the remaining points!

**Comment by brianlovin** [comment]
> Pressing "Space" or "Enter" there will result in a code block that's highlighted as JavaScript, not in a code block that has the text javascript.

I see - I guess I would say this is lower pri then since at least inline code renders, but might be slightly different from the person's expectations. But since we format on typing it might be a nightmare to handle someone trying to type an inline block, plus the problems you've mentioned here with language detection.
