### ISSUE TITLE
Invalid App Id for Facebook Sign In on dev

### ISSUE THREAD

**Issue by ArturKlajnerok** [withspectrum/spectrum#2858]
Sign In with Facebook doeasn't work on `dev:web` and `dev:mobile`. Seems like the FB client Id is not valid anymore.

<img width="231" alt="screen shot 2018-04-13 at 3 46 24 pm" src="https://user-images.githubusercontent.com/1889095/38743643-e86a99fa-3f3f-11e8-8b72-247556fd916a.png">

How to reproduce:
1. Run web client on dev with the dev credentials
2. Try to Sign In with Facebook

**Comment by ArturKlajnerok** [comment]
Hi @brianlovin, already tested other providers so i can confirm that sign in with Google, Twitter and Github works on dev.

**Comment by brianlovin** [comment]
Alright, thanks for double checking. I'm going to keep this low pri for now, but let's keep the issue open :)

**Comment by fullstackguyhere** [comment]
Facing the same issue for fb login

**Comment by satyarohith** [comment]
@ArturKlajnerok Did you run  `cp now-secrets.example.json now-secrets.json` ?

**Comment by fullstackguyhere** [comment]
@ArturKlajnerok What is the homepage url and authorization callback url to be used in github?

**Comment by brianlovin** [comment]
@fullstackguyhere you shouldn't need to configure either of those urls, signing in with GitHub already has those routes in the code :)

**Comment by fullstackguyhere** [comment]
so should i use existing secrets? @brianlovin

**Comment by brianlovin** [comment]
Yes, you should use what's in `now-secrets.json` :)

**Comment by brianlovin** [comment]
Stale and low-pri
