### ISSUE TITLE
Show user hover card in more places

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2859]
We've got a very nice [hover card component](https://github.com/withspectrum/spectrum/blob/alpha/src/components/avatar/hoverProfile.js) that shows a users' details when you hover over their avatar next to a message:

![screen shot 2018-04-13 at 17 36 27](https://user-images.githubusercontent.com/7525670/38744110-37604af4-3f41-11e8-8731-10060d1eef36.png)

Unfortunately, that hover card is not applied consistently at all, in fact it only exists at that one single specific location (when hovering over avatars in messages) and nowhere else. We should show that hover card in more places, when hovering over these things:

- [ ] Message author name and username
- [ ] Thread author avatar and name
- [x] Mentions
- [ ] Maybe participants heads on thread cards?

![screen shot 2018-04-13 at 17 37 33](https://user-images.githubusercontent.com/7525670/38744177-60db15b2-3f41-11e8-876c-15002190004f.png)

If you would like to contribute to Spectrum, this would be a great issue to start at! Take one of the things above, add the hover card component to it (similar to what we do for message avatars right now) and submit a PR. :100:

**Comment by fullstackguyhere** [comment]
Hey, I would like to work on this issue. Could I?

**Comment by mxstbr** [comment]
Yes please! :100:

**Comment by fullstackguyhere** [comment]
Great. I am starting to work on this issue then!

**Comment by mxstbr** [comment]
Awesome! Feel free to submit a PR once you got it in one new place, and we can merge it in small increments.

**Comment by fullstackguyhere** [comment]
@mxstbr What is the homepage url and authorization callback url to be used in github?

**Comment by mxstbr** [comment]
Sorry? Why do you need that? 🤔

**Comment by fullstackguyhere** [comment]
@mxstbr To sign in using github...so i need urls using localhost.

**Comment by fullstackguyhere** [comment]
Without signing, i am unable to do anything apparently.

**Comment by brianlovin** [comment]
@fullstackguyhere the best way to handle this will be to make a new issue with a bug report, and share any console logs or errors you're running into so we can help debug :) Thanks!

**Comment by fullstackguyhere** [comment]
@brianlovin  done that!

**Comment by fullstackguyhere** [comment]
@mxstbr regarding adding hover card for Message author name and username, i have one doubt. Can I ask you?

**Comment by mxstbr** [comment]
@fullstackguyhere instead of asking whether you can ask, just ask :wink:

**Comment by fullstackguyhere** [comment]
Sure @mxstbr So for adding hover card for Message author name and username, I check the code and found that have to add hoverprofile component in AuthorByline in index.js for messageGroup. In order to do so I would to change AuthorByline component into a class component. Is such change acceptable?

**Comment by mxstbr** [comment]
For sure @fullstackguyhere, for sure.

**Comment by fullstackguyhere** [comment]
Hi @mxstbr Just an update. I figured and completed writing code to show hover card for thread author avatars. Currently facing difficulty to do the same for username.

**Comment by mxstbr** [comment]
Don't worry about that, if it's too hard let's just do the avatar for now @fullstackguyhere!

**Comment by mxstbr** [comment]
Write anything like `@somebody`, that's it!

**Comment by fullstackguyhere** [comment]
So basically you want hover card when we hover at @somebody right? @mxstbr

**Comment by mxstbr** [comment]
Yep!

**Comment by fullstackguyhere** [comment]
I have applied hovercard over participant's heads, however, facing below issue:-
![image](https://user-images.githubusercontent.com/31564466/39008983-f21d9cc6-4427-11e8-8b04-1b2b57e9eeb6.png)

The hover card is getting cut off....any suggestions? @mxstbr

**Comment by mxstbr** [comment]
Maybe a higher z-index will help? Not sure, if you push your branch and submit a WIP PR I can take a look!

**Comment by fullstackguyhere** [comment]
@mxstbr I have only been able to make changes for thread author avatar...should i submit a pr?

**Comment by brianlovin** [comment]
Yeah, that overflow hidden is going to cause trouble there; honestly I think at this point the best approach for these hover cards is to have one single component that sits outside of the app (react portal perhaps) and we populate it with data and state when certain elements are hovered. Afaik this is how Twitter handles the same problem - they have one hover card, and add a `data-attr` to different elements that contains an `id` to tell the card where to position and what data to populate with.

Hope that makes sense; not totally necessary now, but will definitely help us avoid the problems like in the screenshot above, and may be worth thinking about as we add lots of hover profiles which might slow things down over time

**Comment by fullstackguyhere** [comment]
#2918 @mxstbr Please have a look. After doing the changes in facepile.js I am getting the above problem.

**Comment by fullstackguyhere** [comment]
@brianlovin I solved the cutting out part partially by setting overflow-y as visible for InboxThreadItem and removing the overflow-x: hidden property.. I removed the overflow-x property. However, this causing issue for uppermost thread cards on the current scroll. See below:-
![image](https://user-images.githubusercontent.com/31564466/39050939-d0719e86-44c4-11e8-956b-1b7fdab1e560.png)
For feed cards that are lower on the page, this does not happen. 
![image](https://user-images.githubusercontent.com/31564466/39051503-7913b672-44c6-11e8-96b1-67e90b1ff0ee.png)

I think this is because of overflow-y: visible that i added. Any way to fix this?

**Comment by brianlovin** [comment]
Looks like some z-index issues! Want to try tweaking the css of the hover card using the zindex scale we have in `src/components/globals`?

**Comment by fullstackguyhere** [comment]
I did that but to no avail...I tried setting it to avatar but it did affect much. Do you have any hints @brianlovin

**Comment by fullstackguyhere** [comment]
#2918 Have a look at my [preliminary changes @mxstbr

**Comment by brianlovin** [comment]
I added these *everywhere* as well as community + channel hover cards!
