### ISSUE TITLE
[Mobile] Image assets for React Native App.

### ISSUE THREAD

**Issue by ArturKlajnerok** [withspectrum/spectrum#2862]
We should figure out how to provide image assets for the mobile app, since React Native don't have out of the box support for SVG (https://react-native.canny.io/feature-requests/p/support-rendering-svg-images)  

Some options that we have :
1) Use JPG or PNG files

2) Use Expo.SVG https://docs.expo.io/versions/latest/sdk/svg , in that case we would need to create a react components with svg elements based on the content of the current svg files, as this solution don't support loading and rendering image from file

**Comment by mxstbr** [comment]
We use Imgix, so we should be able to proxy any SVGs through imgix and pass the `fm` parameter to transform them into jpgs or pngs on the fly. /cc @brianlovin who knows how our imgix setup works, how can we make that happen?

**Comment by brianlovin** [comment]
Yeah I would just need a list of which assets need to be uploaded and reformatted (https://docs.imgix.com/apis/url/format/fm) so that I can upload them manually to S3 and share back the imgix urls.

**Comment by mxstbr** [comment]
Basically just the default avatar and cover photos at this point as far as I can tell

**Comment by brianlovin** [comment]
Default avatar: https://spectrum.imgix.net/default_images/default_avatar.svg

Cover photos (we already have `png` versions):
- https://spectrum.imgix.net/default_images/cover-blue.png
- https://spectrum.imgix.net/default_images/cover-blush.png
- https://spectrum.imgix.net/default_images/cover-cool.png
- https://spectrum.imgix.net/default_images/cover-green.png
- https://spectrum.imgix.net/default_images/cover-orange.png
- https://spectrum.imgix.net/default_images/cover-peach.png
- https://spectrum.imgix.net/default_images/cover-pink.png
- https://spectrum.imgix.net/default_images/cover-red.png
- https://spectrum.imgix.net/default_images/cover-teal.png
- https://spectrum.imgix.net/default_images/cover-violet.png

Profile photos (already have `png` versions):
- https://spectrum.imgix.net/default_images/profile-blue.png
- https://spectrum.imgix.net/default_images/profile-blush.png
- https://spectrum.imgix.net/default_images/profile-cool.png
- https://spectrum.imgix.net/default_images/profile-green.png
- https://spectrum.imgix.net/default_images/profile-orange.png
- https://spectrum.imgix.net/default_images/profile-peach.png
- https://spectrum.imgix.net/default_images/profile-pink.png
- https://spectrum.imgix.net/default_images/profile-red.png
- https://spectrum.imgix.net/default_images/profile-teal.png
- https://spectrum.imgix.net/default_images/profile-violet.png

Logo:
- https://spectrum.imgix.net/default_images/logo-114x114.png
- https://spectrum.imgix.net/default_images/logomark.png

Let me know if anything else is needed here!

**Comment by mxstbr** [comment]
We definitely want to use our own icons. /cc @uberbryn do you reckon you can export the set as `.ttf`s?

**Comment by uberbryn** [comment]
We can do PNG like most apps. Should not use icon fonts.
  

  
  

  
  
>
