### ISSUE TITLE
Add markdown hints to chat input

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2864]
As soon as you type anything into Slack's chat input it shows a cheat sheet of supported markdown features:

<img width="543" alt="screen shot 2018-04-15 at 14 14 39" src="https://user-images.githubusercontent.com/7525670/38778267-6d442b64-40b7-11e8-9598-594ef2e3443a.png">

Now that our chat input also supports some markdown (the ~same subset except for quotes) we should also add a similar cheat sheet so folks are aware of that!

**Comment by Sandro1955** [comment]
**_sasasasa_**` dsdsdsdsds
dsdsdsdsdsdsdsd `sasasasasasasaas``
