### ISSUE TITLE
improve deployment

### ISSUE THREAD

**Issue by xcaptain** [withspectrum/spectrum#2873]
The readme deploy instructions are using `now-cli`, which I tried but met some problems including:
- now requires a $20/month plan to deploy
- now has an unresolved bug here https://github.com/zeit/now-cli/issues/1247 which blocks deployment
- now requires compose.io account and aws account which adds extra expense

I propose to add a manual deploy method so I can deploy spectrum to google cloud, below are the steps to achieve this goal.

- [ ] Put all the environment variables into a `.env` file using https://github.com/motdotla/dotenv
- [ ] Move all the hard coded configs like `localhost:3001`, `spectrum.chat`, oauth IDs into env file
- [ ] Write deploy instructions to the docs. 

I don't if this issue has any conflicts with https://github.com/withspectrum/spectrum/issues/2790, if you like this propose please give me a thumb and I'll work on it.

**Comment by mxstbr** [comment]
This will probably be partially resolved and will have conflicts with #2793, which should make Spectrum easier to deploy anywhere.

**Comment by brianlovin** [comment]
I'd also add that if you're working on deploying your own instance of Spectrum, definitely feel free to do whatever you need to make that work on your end! We will be sticking with our existing server setup and providers in the meantime :)
