### ISSUE TITLE
Only community owners should be able to add an administrator email

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2885]
Just needs a small api check in the backend during the administrator email setting flow to ensure the user updating the email owns the community.

**Comment by dev-drprasad** [comment]
@brianlovin I am not seeing any email field in community settings ? is it possible through only API ?

**Comment by brianlovin** [comment]
It's `administratorEmail` and `pendingAdministratorEmail`

**Comment by mxstbr** [comment]
Done
