### ISSUE TITLE
Fix channel notifications controls alignment on community view

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2886]
<img width="510" alt="screenshot 2018-04-16 18 09 23" src="https://user-images.githubusercontent.com/1923260/38843253-066a25f0-41a3-11e8-82ca-4456b4cf7467.png">

**Comment by mxstbr** [comment]
@TheMightyPenguin yes please! The code for this is in `src/views/community/components/channelList.js`: https://github.com/withspectrum/spectrum/blob/alpha/src/views/community/components/channelList.js

**Comment by TheMightyPenguin** [comment]
Alright @mxstbr, thanks 😄! I'll make a PR for this soon!

**Comment by brianlovin** [comment]
@TheMightyPenguin if it's helpful I was trying to patch this in over in #2890, but feel free to tackle separately :) https://github.com/withspectrum/spectrum/pull/2890/files#diff-372e56dd167de7d9c00603aae8413cdcR235

**Comment by dev-drprasad** [comment]
@TheMightyPenguin i can help with this issue if you are stuck

**Comment by TheMightyPenguin** [comment]
Not yet, just haven't had the time to get my hands dirty, will probably open a PR over the weekend! Will let you know if I get stuck at any point @dev-drprasad! Thanks 😄

**Comment by TheMightyPenguin** [comment]
Hey guys, this seems to be already fixed right? Did not notice that PR from @brianlovin already got merged, I'll try taking another issue ;)

**Comment by brianlovin** [comment]
@TheMightyPenguin sorry man! That one had been sort of patched in a while back, wasn't sure which would land first 🙃

**Comment by TheMightyPenguin** [comment]
@brianlovin it's fine 😉 I'll try picking other issue!
