### ISSUE TITLE
wrong port in some functionality

### ISSUE THREAD

**Issue by dev-drprasad** [withspectrum/spectrum#2896]
**Issue Type**

- [x] Bug Report

**Description**
web ui is running on a port ex. 3002. but some functionalities like siginin with google, signout are pointing to 3001 port.
![screen shot 2018-04-17 at 6 43 39 pm](https://user-images.githubusercontent.com/22687681/38871822-79a3bae6-426f-11e8-9fc2-e7327131a0c4.png)
![screen shot 2018-04-17 at 6 46 42 pm](https://user-images.githubusercontent.com/22687681/38872023-eb9d5f6c-426f-11e8-942e-25af027e9192.png)

**How to Reproduce ?**
make port `3000` busy by running some other application (not spectrum)
start spectrum web app by `yarn dev:web`, it will say
```
Something is already running on port 3000. Probably:
  node server (pid 92032)
  in /Users/user/Workspace/some-app

Would you like to run the app on another port instead? (Y/n)
```
type `Y` and press enter, application will start on some other port (3001 or 3002)
try to login or logout from application

**Comment by dev-drprasad** [comment]
@mxstbr then, its good to not to allow running on other port, right ??

**Comment by mxstbr** [comment]
Yeah true, but that's unfortunately out of our control as `create-react-app` does that, not us :blush:
