### ISSUE TITLE
Can't focus input box with mouse click

### ISSUE THREAD

**Issue by FezVrasta** [withspectrum/spectrum#2897]
If you try to focus a thread input box clicking on it with the mouse you get this error in the console.

```
TypeError: Cannot get property 'getIn' of undefined
```

It doesn't happen in private chats or while you create a new topic or if you focus it using the keyboard TAB key.

![](https://spectrum.imgix.net/threads/9a895003-b061-4d06-af70-cd4dfe1ecba9/S1_iHFmhG-Kapture%202018-04-17%20at%2016.32.27.gif)

![](https://spectrum.imgix.net/threads/9a895003-b061-4d06-af70-cd4dfe1ecba9/rJ3U6YQnf-image.png)

![](https://spectrum.imgix.net/threads/9a895003-b061-4d06-af70-cd4dfe1ecba9/HJP96Ymnf-image.png)

**Comment by mxstbr** [comment]
Yeah can repro locally, I missed this because it doesn't break focusing on Firefox. Digging in!

**Comment by mxstbr** [comment]
Hmm looks like it might be this issue? https://github.com/facebook/draft-js/issues/473 Doesn't seem like our case at all though given we don't have tables. 🤔

**Comment by juliankrispel** [comment]
I'll get back to you tomorrow, sry I've been fairly busy yesterday and today

**Comment by brianlovin** [comment]
FWIW I can't repro this on chrome - @mxstbr are you still encountering?

**Comment by asiermartinez** [comment]
@brianlovin We have encountered a similar problem on another project we are working on, that includes DraftJS, and it only happens when the editor is SSR.

If you arrived at the "screen" with the DraftJS editor for the first time and was server-side rendered, you get the error. Otherwise, you can't reproduce it. At least in our case.

Apparently more people are having the same problem when the editor is SSR. https://github.com/facebook/draft-js/issues/473#issuecomment-346242402

Maybe this can throw a bit of light.

**Comment by mxstbr** [comment]
I can repro locally in FF

**Comment by mxstbr** [comment]
Not the focussing thing, but the error in the console

**Comment by dev-drprasad** [comment]
@mxstbr even i can't repro in my chrome

**Comment by juliankrispel** [comment]
Hummm can't seem to repro this at all. Also, what exactly is the inbox view? Can anyone provide me with instructions to reproduce? ♥️

**Comment by mxstbr** [comment]
The inbox view is your logged-in homescreen/dashboard! I just have to click the chat input in the thread view and immediately get that error.

**Comment by mxstbr** [comment]
This was finally resolved with withspectrum/draft-js-markdown-plugin#82! While that's currently out in prod, it's not the best solution, @juliankrispel is working on a better one, but I'll close this for now since it's fixed either way.
