### ISSUE TITLE
While running the app locally, searching users to message personally is giving error. 

### ISSUE THREAD

**Issue by fullstackguyhere** [withspectrum/spectrum#2904]
Unable to search users to message peronsally. No users are coming as suggestion in the drop down. Also, I am getting below error in in chrome console:-
![image](https://user-images.githubusercontent.com/31564466/38914768-758d12ba-42fe-11e8-8c22-e57526c9dc84.png)

Note:- Also, I have not made code changes around this area.

**Comment by mxstbr** [comment]
Yes, to search you'll need a valid Algolia setup.

**Comment by fullstackguyhere** [comment]
Oh great!. But inorder to do setup Algolia are there steps mentioned anywhere else? Because I cant find the same in readme.md @mxstbr

**Comment by brianlovin** [comment]
AFAIK local search will never work properly because you’d have to be connected to our production algolia instance, which we definitely never want to do in case we accidentally index content on dev. So those are totally separated, which means searching will almost always return no results.

**Comment by fullstackguyhere** [comment]
@brianlovin So how would we test messaging on dev? I have to check whether my hover changes are working fine or not so for that I will have to message at least one user.

**Comment by brianlovin** [comment]
Ah, it might not be possible to be honest - we'd have to set up an entirely separate algolia instance only for local dev which might not make much sense; I think this is safe to close as it's not a breaking issue on prod :)

Although we probably do just need a safety check somewhere in there for null results

**Comment by fullstackguyhere** [comment]
ok sure thanks for the info @brianlovin

**Comment by littleStudent** [comment]
not sure what exactly you need? Just messaging a user?
For that you can go to the account page of another use `http://localhost:3000/users/<user>` and click on `Message <user` there.
