### ISSUE TITLE
Sticky community header with title on thread view

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2906]
It'd be pretty cool if the community header on the thread view was sticky, and showed the title of the thread as you scroll down. Quick two minute mockup with browser DevTools:

<img width="600px" src="https://user-images.githubusercontent.com/7525670/38938940-1244fc3a-4327-11e8-9dcb-0d065cd668db.png" />

<img width="600px" src="https://user-images.githubusercontent.com/7525670/38938943-155c4b1c-4327-11e8-9432-2ff98e9605d8.png" />

This would be especially useful for long threads.

**Comment by fullstackguyhere** [comment]
Hey @mxstbr  I would like to have a go at this!

**Comment by fullstackguyhere** [comment]
I will use the design that you have shown here using dev tools, would that be alright?

**Comment by brianlovin** [comment]
I think we'll probably want a different UI treatment to be honest, no offense Max :) How about something like this https://www.figma.com/file/YB8XJEIRgaLcnfh4wxYMBkzH/Untitled

**Comment by uberbryn** [comment]
Let's use the roundrect treatment from the thread cards for the channel name. Having the same separator twice in a row doesn't look very good (also we probably don't need it since you say "By AUTHOR" anyway).

This makes it more consistent with the treatment on thread cards: https://www.figma.com/file/N8sL0eKpe5Ka2p2fMCDhBd/Untitled-Copy

**Comment by ryota-murakami** [comment]
@mxstbr i saw draft image of sticky community header(max uploaded) that's so useful!
can i take this? if you possible:smile:

**Comment by ryota-murakami** [comment]
@mxstbr thnaks, i'll create PR as soon as possible😀

**Comment by mxstbr** [comment]
Done!
