### ISSUE TITLE
Sentry not working on prod

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2908]
I'm seeing the 'Raven not enabled locally' warning in prod - maybe I messed something up

**Comment by dev-drprasad** [comment]
@brianlovin i checked `src/helpers/events.js` that error will come when `SENTRY_DSN_CLIENT` environment variable not passed to application

**Comment by brianlovin** [comment]
@dev-drprasad I think I was really dumb and didn't realize we probably can't access env variables in the client :P 

We're trying to set ourselves up so that we only get Sentry errors from Spectrum, and not from contributors running our code locally - I'm not totally sure how to approach this now so that we can get error reports from the client without exposing a secret token from Sentry

**Comment by dev-drprasad** [comment]
@brianlovin one way to do this is to define new webpack plugin to pass server environment variables to browser's `process.env`.
**refer:** https://github.com/dev-drprasad/fetch-music/blob/master/webpack.config.js#L29-L35
