### ISSUE TITLE
Error on "start a new conversation" - fixed by clearing local storage items

### ISSUE THREAD

**Issue by edorivai** [withspectrum/spectrum#2913]
Hiya guys,

I was composing a new message, dragging/dropping images, deleting them again, and at some point the page crashed. Reloading the page got me back to the community homepage (https://spectrum.chat/graphql), but whenever I retried to start a new conversation, the page would crash. I opened up the dev-console, removed 2 fields from local storage:

```js
localStorage.removeItem('last-thread-composer-title');
localStorage.removeItem('last-thread-composer-body');
```

After that everything worked again. For reference, these were the values of the two fields:

```
"last-thread-composer-body": "{"blocks":[{"key":"foo","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"fmkjj","text":"","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"ba894","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}",
"last-thread-composer-title": "LoadableQuery for react-apollo"
```

**Comment by brianlovin** [comment]
Thanks so much for the heads up!

**Comment by cutjavascript** [comment]
@edorivai , are you facing same issue with below PR/branch
https://github.com/withspectrum/spectrum/pull/2832
local_storage_clear_2723

**Comment by edorivai** [comment]
@cutjavascript Uh, I didn't ever really run spectrum locally. Just ran into the issue on the actual website :sweat_smile:

**Comment by brianlovin** [comment]
Is that an issue with local storage or with draft js? cc @mxstbr

**Comment by edorivai** [comment]
I feel like it's an issue with draft, but the localStorage behavior creates the deadlock.

**Comment by cutjavascript** [comment]
also I cannot delete and add image again, i.e once I have deleted an image I cannot add same image again (I can add another image)
@brianlovin  do we need another issue for this? 
Above case Video: https://drive.google.com/file/d/1PheELzfVDKQ3ueFIpTnLL454LIwcc0aC/view


@edorivai agree localstorage seems to be creating a deadlock
will investigate further

**Comment by brianlovin** [comment]
Stale issue, shouldn't be a problem any more with newest editor.
