### ISSUE TITLE
Infinite loop in the Toolbar component

### ISSUE THREAD

**Issue by ondrej** [withspectrum/spectrum#2921]
Toolbar in src/components/rich-text-editor/toolbar.js seems to get itself into an infinite loop. componentDidUpdate() calls setPosition(), which calls setState(), which causes a re-render and another call to componentDidUpdate(). I see the loop get kicked off when I click the "Post your first thread" button right after first login.

React's NESTED_UPDATE_LIMIT check doesn't catch it, so the page doesn't error out, but the looping does still seem to be going on.

**Comment by mxstbr** [comment]
Interesting, thanks for the heads up! Will figure out how to fix this.
