### ISSUE TITLE
Make direct message deleteable

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2925]
We initially decided against making messages deleteable in an effort to keep a conversations history accurate, but since we now allow messages to be deleted we should also allow direct messages to be delete. (I think we actually filter those specifically from being deleted on the frontend and backend, so it should just be a matter of removing those couple guards)

**Comment by mxstbr** [comment]
@alejandronanez definitely going for it, so yes please do work on it! :100:

**Comment by alejandronanez** [comment]
I'm curious, do you have any mocks or ideas for this feature @brianlovin?

**Comment by brianlovin** [comment]
@alejandronanez - should match the same flow as deleting a message in a normal thread :)

**Comment by fullstackguyhere** [comment]
I have looked into this. The flow will be very similar to delete a message from a normal thread, however, updating the state is a challenge here. When I delete the message, the UI does not get updated. Meaning that the deleted message does not get removed from the screen. It gets removed only after a page reload. Any suggestions, @brianlovin

**Comment by alejandronanez** [comment]
Are you already working on this too @fullstackguyhere?

**Comment by fullstackguyhere** [comment]
Yes @alejandronanez i am figuring out whether this is straight forward as it looks or not.

**Comment by brianlovin** [comment]
@fullstackguyhere the ui updating happens with the apollo cache; see `shared/graphql/mutations/message/deleteMessage.js` - there's likely a bug in there that's preventing the cache from updating

**Comment by alejandronanez** [comment]
@fullstackguyhere you can grab this feature from here since you have already started working on this then. It doesn't make sense that two people work in the same problem at the time.

**Comment by fullstackguyhere** [comment]
Sure @alejandronanez

**Comment by fullstackguyhere** [comment]
@mxstbr @brianlovin  I have completed the code changes for this. Could have a look at #2977
