### ISSUE TITLE
There is no message when you don’t have any DM

### ISSUE THREAD

**Issue by alejandronanez** [withspectrum/spectrum#2927]
It should be good to see a message that informs user that he/she doesn’t have any messages yet.

![525d8d43-814d-44eb-bc10-099798cfa5a1](https://user-images.githubusercontent.com/464978/39046240-1e668350-445b-11e8-8876-a555511c9c90.png)

**Comment by alejandronanez** [comment]
I can work on this if no one is doing so.

Thanks!

**Comment by mxstbr** [comment]
Duplicate and already taken, ref #2878
