### ISSUE TITLE
Run Cypress without --record for forks

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2929]
Cypress currently fails for any collaborators because we don't provide the Cypress secret to them. (for obvious security reasons) We should just run Cypress without the `--record` option if the secret doesn't exist.

<img width="712" alt="screen shot 2018-04-20 at 16 31 24" src="https://user-images.githubusercontent.com/7525670/39056979-624c3580-44b8-11e8-8353-710e9a097032.png">

**Comment by brianlovin** [comment]
Thanks man - I reached out to the Cypress team about this and their upcoming version will fix this entirely :)
