### ISSUE TITLE
Enable notifications for watercoolers

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2956]
I think we should enable notifications for watercooler threads. Making a special exception for them sounded sensible at the time, but honestly I just miss all the messages in them because of it and I feel bad about it since it's really meant as a catch-all. It's very unexpected that the "general chat room" doesn't notify me when a new message comes in. (imagine e.g. Slack doing that...)

I think we should remove any special treatment for watercoolers apart from the visual differences on the client and have them be like any other thread, honestly.

**Comment by brianlovin** [comment]
Fair enough, and I agree; we'll just need to add in the UI control for it in the frontend
