### ISSUE TITLE
Cached assets not loading properly?

### ISSUE THREAD

**Issue by lolcoolkat** [withspectrum/spectrum#2957]
Is it just me or when I go to https://spectrum.chat and i'm on the home page (logged out).. the images load fine.. but when I reload the page.. all the assets do not get loaded...

**Note**: I am using the Chrome browser..

Tried on multiple browsers and they are all doing the same thing?

![Error](https://i.imgur.com/4IDqJOf.png)

Is anyone else experiencing this issue?

**Comment by mxstbr** [comment]
Yeah we need to cache our image assets again...

**Comment by uberbryn** [comment]
I should probably move those to s3/imgix anyway. I'm working on some new marketing pages rn and I'll see if I can tack that on.

**Comment by mxstbr** [comment]
This was fixed in #3195
