### ISSUE TITLE
Fix nested mentions

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#2963]
@alejandronanez in #2945:

If you write this in Spectrum:

```
@scoped/package
@scoped/package
@scoped/package
@scoped/package
```

You'll end up with this:

<img width="371" alt="screen shot 2018-04-26 at 4 36 00 pm" src="https://user-images.githubusercontent.com/464978/39333278-eb64b14c-496f-11e8-9621-2a591708c959.png">

**Comment by mxstbr** [comment]
I'm pretty sure this has to do with how I set the `key` prop on the mention component, which is very hacky at the minute. We gotta find a better way to do that...

**Comment by alejandronanez** [comment]
Since I just touched that piece of code, I’d like to  give this a shot.

Can you please assign it to me?

**Comment by mxstbr** [comment]
@alejandronanez that'd be great, thank you! :100:

**Comment by alejandronanez** [comment]
FWIW I already have a PR open to fix this 😸 https://github.com/withspectrum/spectrum/pull/2976
