### ISSUE TITLE
DMs force an entire refresh whenever I send a message in a thread

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2965]
Video: https://www.dropbox.com/s/8vyyj7i2j8t3e8p/buggy-dms.mov?dl=0

This is happening in all my DM threads on both Firefox and Chrome

**Comment by brianlovin** [comment]
Marking this as FIX NOW because DMs are basically unusable at this point.

**Comment by littleStudent** [comment]
i identified https://github.com/withspectrum/spectrum/commit/71a90804a3226b001c9e600b9b607798be5216ca as the commit causing the problem.
Sadly I am missing a few insights to quickly understand why this triggers the rerender?

**Comment by brianlovin** [comment]
Ahhh damn, thank you for digging in on that @littleStudent cc @mxstbr - I'm going to dig into this shortly

**Comment by littleStudent** [comment]
i tried a quick fix, but:

I am not 100% sure about the underlying problem itself.
I am not 100% sure if i create any unwanted sideeffects with this fix 🤔 

So feel free to shut down my PR if its not suited ;)
