### ISSUE TITLE
Thread composer content exceeds ActionsBar on new lines

### ISSUE THREAD

**Issue by littleStudent** [withspectrum/spectrum#2968]
I searched the issues but have not found this one, hope its no duplicate.

**Issue Type (check one)**

- [X] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

When creating a new thread with input the exceeds the visible area.
The scroll position is not correct anymore. The content are only starts scrolling on `new-lines` if it hits the bottom of the page. This should already happen when the content hits the `action bar`.

![kapture 2018-04-27 at 19 00 10](https://user-images.githubusercontent.com/815520/39375069-5202ba88-4a4d-11e8-86cb-1986dfa46879.gif)

**Comment by danedavid** [comment]
Can I work on this?

**Comment by mxstbr** [comment]
I am not sure, maybe @ThomasRoest has fixed this in #4575?

**Comment by ThomasRoest** [comment]
yes, working on this!

**Comment by brianlovin** [comment]
Fixed in #4575
