### ISSUE TITLE
Improvements to replied messages

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2969]
This is a followup to #2924 

- [x] When replying to long messages, we should truncate the reply in the chat input preview and in the reply bubble itself.
- [ ] Clicking on a reply should scroll the chat to that particular message. If the original message has not been loaded due to pagination, we should handle paginating until the original message loads
- [x] When pressing the "Reply" button, the quoted message should only be shown in the chat input in the selected thread, not everywhere else too
  ![screen shot 2018-05-02 at 12 43 36](https://user-images.githubusercontent.com/7525670/39519298-7854034c-4e06-11e8-9020-6aaa5188e7b2.png)

- [ ] Bonus: If a user highlights text of a bubble then clicks reply, it should only reply to that selected text

**Comment by brianlovin** [comment]
That'd be awesome @dev-drprasad :D

**Comment by dev-drprasad** [comment]
@brianlovin what is meaning of bubble ?

**Comment by brianlovin** [comment]
We call the individual chat messages "bubbles" :)

**Comment by dev-drprasad** [comment]
@brianlovin do we need any backend support for bonus feature or just frontend work ??

**Comment by dev-drprasad** [comment]
@brianlovin looks like little bit more work. i guess i need some more to finish.

**Comment by dev-drprasad** [comment]
@brianlovin @mxstbr 
what do think about design for quoting selected text ??
do we need to add one more action like `quote selection` in actions list beside bubble ??
or tooltip action like in image
![download](https://user-images.githubusercontent.com/22687681/40436194-13c76d94-5ed0-11e8-967e-571976fc312f.jpeg)

**Comment by ryota-murakami** [comment]
like medium?😀

**Comment by brianlovin** [comment]
I think an ideal UX here could be the same as email clients: if there is highlighted text on the message when the quote reply button is clicked, it automatically uses the highlighted text as the snippet.

**Comment by dev-drprasad** [comment]
@brianlovin where is code resided to handle dispatched actions ? i mean making api calls
i worked with only `saga` before. so, i am little confused :(

**Comment by Jae84** [comment]
Work? Nah. ?

**Comment by brianlovin** [comment]
@dev-drprasad check `src/actions` for our action dispatchers, then we have `src/reducers` directory with the store reducers

**Comment by dev-drprasad** [comment]
`window.getSelection()` method will return selected text in complete document. so we cant blindly use `window.getSelection()` to get selected text because it can be anywhere in document

we can use `window.getSelection().baseNode.parentNode.closest('div.message')` to get message wrapper. but how can we decide this message wrapper related with reply action element ??

I am thinking of adding `data-message-id` attribute to message wrapper and use react `refs` to get message id. so that we can use it to check whether reply action is associated or not with message

@mxstbr @brianlovin what do you say ??

**Comment by brianlovin** [comment]
We knocked out the core experience here for replying to threads.
