### ISSUE TITLE
Can't type on Android / unwanted text add

### ISSUE THREAD

**Issue by cpannwitz** [withspectrum/spectrum#2982]
I'm using an Android OnePlus 3, and as seen below in the gif, I try to type but the text always gets resetted to first body copy word I typed.

(Sorry for the gif quality)

![videotogif_2018 04 30_22 09 01](https://user-images.githubusercontent.com/11204231/39447924-9d7bbdca-4cc3-11e8-9a96-0d92223a77ff.gif)

**Comment by mxstbr** [comment]
Yeah, we've fixed this for the chat input but not the composer yet—sorry about the troubles, I'll try and take a look this week! Ref #2492
