### ISSUE TITLE
Ensure that all owned communities are fully downgraded if a user is banned

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#2988]
When a user is banned we need to double check that any owned communities are fully downgraded from any paid features.

**Comment by johnnynotsolucky** [comment]
@brianlovin what happens to the community if they are the only admin?

Can users be unbanned?

**Comment by brianlovin** [comment]
Yes, users can be unbanned - right now the community will still exist, just in case we unban, but we have in our terms the right to reclaim any communities owned by banned users

**Comment by brianlovin** [comment]
Actually, when we ban them we remove them as owners of their communities; this is technically restore-able because the community record will retain the `creatorId` field, but this would be an edge case of someone getting banned and we would reinstate everything

**Comment by brianlovin** [comment]
That's right, but we have `pluto` worker that has changefeeds running which will trigger events to handle that stuff; regardless it will still require a confirmation, but as long as we downgrade all private channels/mods/analytics from the community, `pluto` should handle the rest :)

**Comment by johnnynotsolucky** [comment]
Aha!

This commit added that logic: https://github.com/withspectrum/spectrum/commit/bf75cb8fe0cb6ad8ec39b621c1c6e0cc43b31812. It should be easy enough to adapt these mutations to apply to all communities owned by the banned user.

I've checked the listeners for mutations made in `cancelSubscription` in `pluto` and they all look good and are pushing to the correct queues. Although I know nothing about Stripe, but the relevant calls are being made there.

For this issue should we only update the banning-users doc to include these extra relevant queries?
