### ISSUE TITLE
Issue uploading images with special characters.

### ISSUE THREAD

**Issue by alejandronanez** [withspectrum/spectrum#3000]
If you upload an image with special characters `my-image?.png` the upload will fail

![screen shot 2018-05-02 at 1 58 44 pm](https://user-images.githubusercontent.com/464978/39543526-1766dd56-4e11-11e8-825c-97a9f0cbcca5.png)

**Comment by mxstbr** [comment]
(sidenote: this was issue #3000 :tada:)
