### ISSUE TITLE
Cannot read split of undefined in graphql error formatter

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3002]
cc @a-golovanov - I'm going to dig into this now, but just a heads up!

![screenshot 2018-05-02 14 07 13](https://user-images.githubusercontent.com/1923260/39549308-375cef00-4e12-11e8-9de7-33445233fe66.png)

**Comment by mxstbr** [comment]
@orta how could `danger.github.issue.labels` be undefined when Peril runs on `issue.edited`?! 

<img width="775" alt="screen shot 2018-05-03 at 11 32 13" src="https://user-images.githubusercontent.com/7525670/39569495-a6e56ff6-4ec5-11e8-8777-b72ef4a57401.png">

**Comment by orta** [comment]
Perhaps the issue webhook has different JSON when being edited than opened? I'd check in the advanced section of the GitHub app ( I've only used [issue.opened](https://github.com/CocoaPods/peril-settings/blob/master/settings.json#L7) so far )
