### ISSUE TITLE
Mark community channels as deleted when the community is deleted

### ISSUE THREAD

**Issue by a-golovanov** [withspectrum/spectrum#3014]
When a community is deleted its channels should be marked as deleted as well. See https://github.com/withspectrum/spectrum/issues/2950#issuecomment-385866952

**Comment by a-golovanov** [comment]
I don't have time to do PR at the moment, so the issue is up for grabs.

**Comment by brianlovin** [comment]
So I did some digging and we are actually deleting channels here. See `api/mutations/community/deleteCommunity:56-58` - I did some manual digging in the database and found a few cases where somehow a channel was not deleted (4 total). I'm going to manually sort out the data consistency there, but afaik this isn't an issue and we can close :)

**Comment by a-golovanov** [comment]
👍
I missed the code in the mutation. For some reason, I expected to see it in community model instead :).
