### ISSUE TITLE
Squashing commits.

### ISSUE THREAD

**Issue by alejandronanez** [withspectrum/spectrum#3018]
This is not a feature itself but a suggestion.
What about using `Squash and Merge` instead of the good ol' _regular_ `Merge` mechanism? If you squash your commits you'll have a clearer commit history (1 commit per feature/bug).
On the other hand, you won't have the same level of granularity in your commit history...but I think it's worth the tradeoff as long as you write good commit messages 👍

**Comment by mxstbr** [comment]
I realllly don't like squashing, it makes `git rebase` basically worthless, especially for big features. I much prefer to have the actual history in place!

**Comment by alejandronanez** [comment]
Oh well, I tried! 😝

Thanks for your response!
