### ISSUE TITLE
Hyperion build failing

### ISSUE THREAD

**Issue by mattgaunt** [withspectrum/spectrum#3032]
I had the repository working nicely on my iMac 10~ days ago, it worked great and I had no issues, setup docs are 👌! 

I've just cloned the latest version onto my laptop this morning and I've hit a few roadblocks. Building hyperion seems to be falling over, it's telling me I haven't ran `yarn run dev:web` before running `yarn run dev:hyperion`, it seems that `static/js/bundle.js` is not being created. If I switch it to production it matches with `main.js` fine and boots up.

Once I'm past that issue, it's falling over whilst rendering when I request a page.

```
Error: 
fetch is not found globally and no fetcher passed, to fix pass a fetch for
your environment like https://www.npmjs.com/package/unfetch.

For example:
import fetch from 'unfetch';
import { createHttpLink } from 'apollo-link-http';

const link = createHttpLink({ uri: '/graphql', fetch: fetch });
```

Any ideas?

**Update**
After digging around, it seems the latter issue is introduced via this PR #3009 that was merged a couple of days ago

**Comment by ryota-murakami** [comment]
I also reproduced, should we revert https://github.com/withspectrum/spectrum/pull/3009 and add explicit comment?
i'm so sorry:bow:

**Comment by mxstbr** [comment]
Yeah, that'd be great @ryota-murakami—and no worries, it's totally my bad for not adding said comment in the first place!

**Comment by ryota-murakami** [comment]
@mxstbr i created Revert PR. https://github.com/withspectrum/spectrum/pull/3033
it's ready for review.
if you have improvements in isomorphic-fetch's comment, could you edit it directly?
