### ISSUE TITLE
Thread do not work on small device (nexus 5 actually)

### ISSUE THREAD

**Issue by borovik96** [withspectrum/spectrum#3034]
**Issue Type**
- [x] Bug Report

**Description**
I can't open no one thread on my mobile device: Nexus 5. See screens below:
![image](https://user-images.githubusercontent.com/9018702/39692647-18b1dd6e-51ea-11e8-873c-5d7ba112fb1f.png)
![image](https://user-images.githubusercontent.com/9018702/39692726-564d464a-51ea-11e8-9b6f-41783727c635.png)

**Comment by brianlovin** [comment]
Could you share the url to this thread?

**Comment by borovik96** [comment]
Actually it crashes with any thread, for example with it https://spectrum.chat/thread/761b6802-46cf-4fc1-bd57-ba2cf57a8bf0

**Comment by brianlovin** [comment]
Does this resolve for you on a hard refresh @borovik96 - I think this is related to #3011 cc @mxstbr

**Comment by ryota-murakami** [comment]
this phenomenon appears to through [this code](https://github.com/withspectrum/spectrum/blob/621766f3254fbe531938767f5db8533d55535f90/src/views/thread/container.js#L548) with `hasError = true`.

I searching and found out [`hasError` variable mean](https://github.com/withspectrum/spectrum/blob/alpha/src/components/viewNetworkHandler/index.js#L68).

according to [Apollo Client doc](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-networkStatus), `data.networkStatus === 8` mean is 

> 8: error: No request is in flight for this query, but one or more errors were detected.

If this is a related service worker problem, I think it is necessary to add code to handle refetch GraqhQL using a [notifyOnNetworkStatusChange](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-notifyOnNetworkStatusChange) such as.

**Comment by borovik96** [comment]
Is problem solved? The error is still appears

**Comment by brianlovin** [comment]
@borovik96 I'm having a hard time reproducing this crash; we did make some changes shortly before your last comment which have shipped, so I'm wondering how things are working on your end now.
