### ISSUE TITLE
Encourage more social media shares from authors

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3040]
When authors published a new thread, but haven't received a reply yet, we should show a strong upsell in the empty messages area (including buttons) to share the content to other social media sites. Dumb mockup: 

![sharing upsell](https://user-images.githubusercontent.com/7525670/39748174-bbd803ea-52af-11e8-8e9d-f80e6d24e227.png)

> Note: we should probably come up with some better copy there, this was just a quick and dirty hack to show the idea. Don't use that exact copy!

This should only show to the author, not to anybody else—we mainly want to encourage other people to answer, rather than share.

**Comment by alejandronanez** [comment]
This sounds interesting, I’d like to work on it. :)

**Comment by mxstbr** [comment]
Do it @alejandronanez!
