### ISSUE TITLE
Refetch all queries on reconnect

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3043]
We should use this Apollo Client option I just now discovered (thanks to @ryota-murakami) to refetch all queries if the user disconnects, then reconnects to the network: https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-notifyOnNetworkStatusChange

**Comment by brianlovin** [comment]
YES! Have been wondering about this, especially for DMs - would be so nice and remove a lot of questioning whether I need to refresh or not.

**Comment by ryota-murakami** [comment]
related comment https://github.com/withspectrum/spectrum/issues/3034#issuecomment-387438777

**Comment by mxstbr** [comment]
No it doesn't, unfortunately. The `graphql` HoC (or the `Query` component for that matter) don't refetch just because they are re-rendered, they re-fetch when they are re-mounted if the `fetchPolicy` of the query is set to `cache-and-network`. In our case, we want to re-fetch without re-mounting, if that makes sense.

**Comment by ryota-murakami** [comment]
i see. we might be need refetch manually in 
[viewNetworkHandler](https://github.com/withspectrum/spectrum/blob/alpha/src/components/viewNetworkHandler/index.js) or somewhere🤔

like `apollo-link-error`.
https://www.apollographql.com/docs/react/features/error-handling.html#network
