### ISSUE TITLE
Nav dropdown breaks when we add people to compose new message

### ISSUE THREAD

**Issue by satyarohith** [withspectrum/spectrum#3073]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

Tested in chrome & firefox
![spectrum-nav-bug-messages](https://user-images.githubusercontent.com/29819102/39952897-0e45ac84-55be-11e8-9f56-eda23e0df1fb.gif)

**Comment by fullstackguyhere** [comment]
Hi @mxstbr I would like to work on this!

**Comment by mxstbr** [comment]
Do it!

**Comment by brianlovin** [comment]
@fullstackguyhere seems like we need to solve this problem in general for contributors; what we probably want is an escape hatch in the backend for searching against rethinkdb instead of algolia if the node_env is development.

**Comment by mike-ap** [comment]
I loaded some fake users directly into newThread.js to reproduce, and found that recipients are added as SelectedUsersPills, which has a z-index that overlaps the Notifications and User dropdowns. Removing the z-index declaration fixes the issue without side effects in Chrome, Safari, Firefox.
