### ISSUE TITLE
Can't search in "Everything"

### ISSUE THREAD

**Issue by agurtovoy** [withspectrum/spectrum#3109]
Steps to reproduce:
- Log in to https://spectrum.chat/, click "Home", then "Everything"
- Click on "Search for conversations..." field -> the focus is briefly set to the field, and then it goes somewhere else; typing anything has no effect (BUG)

![spectrum-search](https://user-images.githubusercontent.com/3394202/40141709-54906722-591c-11e8-8e21-5ed35166062c.gif)

**Comment by agurtovoy** [comment]
Hmm, it looks like it doesn't reproduce every time. The weird thing is, I refreshed a couple of times to make sure it wasn't just a temporary glitch, and it reproduced for me consistently, but after closing and reopening the window it doesn't anymore.

**Comment by ryota-murakami** [comment]
yah,strange. i followg your reproduced, but the probrem seach UI never swohown on my chrome.

![may-17-2018 05-20-55](https://user-images.githubusercontent.com/5501268/40142566-f337d91a-5993-11e8-8844-c9146209bc9c.gif)

**Comment by ryota-murakami** [comment]
@agurtovoy i'm afraind, currently no idea.
but obviously buggy,  i'd lile to fix it later🙇‍♂️

**Comment by brianlovin** [comment]
Inbox search is working fine, this was resolved
