### ISSUE TITLE
[Message] Single Emoji reply doesn't work as reply

### ISSUE THREAD

**Issue by ryota-murakami** [withspectrum/spectrum#3114]
**Issue Type (check one)**

- [x] Bug Report

## overview
 Single Emoji reply doesn't work as reply.
might be when reply text started at Emoji.

### Gif👩‍💻

![may-18-2018 20-09-55](https://user-images.githubusercontent.com/5501268/40232016-23a9a098-5ad8-11e8-8d8c-78a11afd5ec6.gif)

**Comment by brianlovin** [comment]
Not ideal, thanks for the heads up! I think GitHub checkboxes are broken right now which broke our bot and auto-closed this?

**Comment by ryota-murakami** [comment]
@brianlovin thanks reply!
I've just close manually because i prefer close less activity issue/PR.(i feel much better🤪)

But it's not ideal, i'll fix it🤗
