### ISSUE TITLE
Off-centered background-images for cover photos

### ISSUE THREAD

**Issue by tannerlinsley** [withspectrum/spectrum#3172]
Header images backgrounds (mainly in the sidebar) are not centered despite their size being set to `cover`:

![screen shot 2018-05-29 at 10 44 02 am](https://user-images.githubusercontent.com/5580297/40672906-71f5e0ba-632d-11e8-84e6-c8c054d325aa.png)

**Comment by tannerlinsley** [comment]
You bet!

**Comment by ThomasRoest** [comment]
on what page / section can I find this issue?

**Comment by tannerlinsley** [comment]
I'm unable to find this UI any more. Looks like it was changed.

**Comment by brianlovin** [comment]
Thanks for following up!
