### ISSUE TITLE
[Desktop] HIde web push notifications prompt from app

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3178]
<img width="284" alt="screenshot 2018-05-29 13 38 23" src="https://user-images.githubusercontent.com/1923260/40684199-9dd90262-6345-11e8-9028-71e96537ab46.png">

Can't enable push notifs from user settings in the desktop app - @mxstbr is there any way this will work in the future?

**Comment by mxstbr** [comment]
You don't need to enable web push notifications, those are done via Electron's own! We should hide that bar in the desktop app.

**Comment by kapillamba4** [comment]
@mxstbr, Can you please assign me this issue

**Comment by brianlovin** [comment]
Ah, that's interesting. Got it

**Comment by mxstbr** [comment]
Still gotta have this open because we should hide the prompt in the desktop app!
