### ISSUE TITLE
[Desktop] Consider migrating to BrowserView instead of BrowserWindow

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3193]
From Figma: https://blog.figma.com/introducing-browserview-for-electron-7b40b4b493d5
And why Slack switched to them: https://slack.engineering/growing-pains-migrating-slacks-desktop-app-to-browserview-2759690d9c7b

`BrowserView` is still pretty experimental, so maybe not worth switching now. But opening this up for discussion in case a stronger Electron dev had advice :)

**Comment by mxstbr** [comment]
I don't think that makes much sense for us, given that we don't have individual teams you can switch between?
