### ISSUE TITLE
[Desktop] Option to open links in browser instead of new app window

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3203]
Sometimes it'd be nice to just open links in your default browser, rather than opening our admittedly-awkward app window on top of the core experience. This could either be a setting or just make it so that option+click opens in the browser in the background.

**Comment by ryota-murakami** [comment]
totally agree, i think exact same thing😅👍

**Comment by mxstbr** [comment]
> This could either be a setting or just make it so that option+click opens in the browser in the background.

Why wouldn't we just open all links in their default browser? 🤔

**Comment by brianlovin** [comment]
Yeah, let's just do that :P
