### ISSUE TITLE
Incorrect password requires refresh

### ISSUE THREAD

**Issue by mrbrianhinton** [withspectrum/spectrum#3209]
If an incorrect password is entered it redirects the user to another Twitter sign in page, and doesn't allow logging in to occur.

1. Click to sign in with Twitter
2. Enter the wrong password
3. Redirects to another page
4. Try and enter right password
5. Nothing happens.

**Comment by brianlovin** [comment]
Yay Twitter auth! Twitter will break our flow if you go down anything but the standard auth path - e.g. if you have to change 2factor methods, they just redirect you back to twitter.com and you get stuck seeing twitter.com in the Spectrum app :P
