### ISSUE TITLE
Service worker persists after app update

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3210]
Discussion here: https://spectrum.chat/thread/4c8165c0-84b9-46a1-8757-13fe2ba5f1b9

I downloaded a fresh version of beta 2 and saw that most of the styling changes hadn't made it in. Top is what I was seeing in my beta 2 app, bottom is what I was seeing locally when running the development app:
<img width="499" alt="screenshot 2018-05-30 12 15 33" src="https://user-images.githubusercontent.com/1923260/40742933-d94b0a38-6404-11e8-916c-747c90a0c9f7.png">

I tried:
- hard refreshing the app several times
- quitting and restarting the app
- redownload the app

The problem with the styling persisted.

The fix: I opened the command tools in the beta2 app, cleared out all my localstorage/service workers/cookies/etc and re-logged in - voila, fixed:

<img width="525" alt="screenshot 2018-05-30 12 26 06" src="https://user-images.githubusercontent.com/1923260/40742955-faac16e0-6404-11e8-9f0b-020654837385.png">

**Comment by mxstbr** [comment]
Hmm that's... interesting. I'm going to have to dig into how we'll fix that 😅

**Comment by mxstbr** [comment]
Actually, I don't know if this isn't a general bug that the ServiceWorker doesn't upgrade after #3195 🤔
