### ISSUE TITLE
Overlapping traffic lights block some website nav

### ISSUE THREAD

**Issue by mrbrianhinton** [withspectrum/spectrum#3212]
In the popover window when opening a link the snazzy no border can break navigation on some websites. Dribbble is a nice example.

<img width="194" alt="screen shot 2018-05-30 at 3 36 30 pm" src="https://user-images.githubusercontent.com/2288431/40743421-78af241e-641f-11e8-9a83-deaa1be4caa8.png">

The menu isn't accessible.

1. Go to this conversation https://spectrum.chat/thread/a16e045d-aeeb-447d-9633-e3be2d521a61
2. Click the link to Dribbble 
3. Note the overlap.

I believe you can configure opening external windows to use default UI bars, or URLs could just be designated to open the default browser.

**Comment by brianlovin** [comment]
Going to close this in favor of #3213 since it's the same underlying problem :)
