### ISSUE TITLE
Desktop and mobile apps upsells

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3215]
Setting a reminder that we need to build out the in-app upsells and marketing for desktop and mobile apps! Ideally this will be in:
- user onboarding
- home page
- features page
- navbar user profile dropdown
- notifications view

**Comment by mxstbr** [comment]
All of those should link to a `/apps` page which has the links to the latest versions of all the apps, right?

**Comment by brianlovin** [comment]
Good call, yep!
