### ISSUE TITLE
Everything is linked to spectrum.chat

### ISSUE THREAD

**Issue by entrptaher** [withspectrum/spectrum#3217]
I have searched the code and saw basically everything is hardcoded to `spectrum.chat` and `localhost:3001`, which means deploying it with custom deployment url won't work.

![image](https://user-images.githubusercontent.com/8284972/40749714-b9c2ca34-6486-11e8-96dd-40bb41b39db7.png)

**Comment by mxstbr** [comment]
Yeah, we haven't optimized the source for external deployments—it's very tied to our infra and setup atm.

**Comment by mxstbr** [comment]
Going to close this since it's not something we'll be tackling anytime soon, but we would probably merge a PR that moves all of that out to a config file!
