### ISSUE TITLE
[Desktop] CD Failing

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3231]
Desktop CD fails: 
https://circleci.com/gh/withspectrum/spectrum/7674

```js
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /home/circleci/spectrum/desktop/node_modules/electron-builder-lib/node_modules/builder-util/src/wine.ts:100:13
    at Generator.throw (<anonymous>)
```

**Comment by mxstbr** [comment]
Yeah it builds Mac and Linux fine, but breaks on Windows:

![screen shot 2018-06-01 at 10 30 03](https://user-images.githubusercontent.com/7525670/40830465-cc603c20-6586-11e8-95e7-b413c3a16bba.png)

Investigating!
