### ISSUE TITLE
Chat input and join channel upsell render at the same time - how is this possible?

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3241]
Check. Out. This. Madness:
<img width="1680" alt="screenshot 2018-05-31 19 10 56" src="https://user-images.githubusercontent.com/1923260/40817270-606717d0-6506-11e8-967a-888775abd661.png">

The chat input and join channel upsell are rendering at the same time.

Okay, look at the DOM with me. There is a div with the class `JoinChannelContent` - that can only come from one component in the app, in `components/upsell/joinChannel.js`:

```js
render() {
    const { isLoading } = this.state;
    const { channel, community } = this.props;
    return (
      <JoinChannelContainer>
        <JoinChannelContent>
          <JoinChannelTitle>
            Join the {channel.name} channel in the {community.name} community
          </JoinChannelTitle>
          <JoinChannelSubtitle>
            Once you join this channel you’ll be able to post your replies here!
          </JoinChannelSubtitle>
        </JoinChannelContent>

        <Button
          loading={isLoading}
          onClick={this.toggleSubscription}
          icon="plus"
          label
          dataCy="thread-join-channel-upsell-button"
        >
          Join
        </Button>
      </JoinChannelContainer>
    );
  }
```

Note: there is no `children` or anything that could cause anything else to go inside the `JoinChannelContent` div.

Here is the code that determines whether to render the chat input or join channel upsell:

```js
renderChatInputOrUpsell = () => {
    const { isEditing } = this.state;
    const { data: { thread }, currentUser } = this.props;

    if (!thread) return null;
    if (thread.isLocked) return null;
    if (isEditing) return null;
    if (thread.channel.isArchived) return null;

    const { channelPermissions } = thread.channel;
    const { communityPermissions } = thread.community;

    const isBlockedInChannelOrCommunity =
      channelPermissions.isBlocked || communityPermissions.isBlocked;

    if (isBlockedInChannelOrCommunity) return null;

    const LS_KEY = 'last-chat-input-content';
    const LS_KEY_EXPIRE = 'last-chat-input-content-expire';
    let storedContent;
    // We persist the body and title to localStorage
    // so in case the app crashes users don't loose content
    if (localStorage) {
      try {
        storedContent = toState(JSON.parse(localStorage.getItem(LS_KEY) || ''));
      } catch (err) {
        localStorage.removeItem(LS_KEY);
        localStorage.removeItem(LS_KEY_EXPIRE);
      }
    }

    const chatInputComponent = (
      <Input>
        <ChatInputWrapper>
          <ChatInput
            threadType="story"
            threadData={thread}
            thread={thread.id}
            currentUser={currentUser}
            forceScrollToBottom={this.forceScrollToBottom}
            onRef={chatInput => (this.chatInput = chatInput)}
            refetchThread={this.props.data.refetch}
          />
        </ChatInputWrapper>
      </Input>
    );

    if (!currentUser) {
      return chatInputComponent;
    }

    if (currentUser && !currentUser.id) {
      return chatInputComponent;
    }

    if (storedContent) {
      return chatInputComponent;
    }

    if (channelPermissions.isMember) {
      return chatInputComponent;
    }

    return (
      <JoinChannel channel={thread.channel} community={thread.community} />
    );
  };
```

So how is what we see in the dom possible? Not only does the `JoinChannelContent` div not contain the title and subtitle components that we see in the `joinChannel.js` file, but also the `ChatInput` and `JoinChannel` are being rendered simultaneously out of that `renderChatInputOrUpsell` method.

Is this a react thing? I'm very tired and may have missed something obvious...

**Comment by brianlovin** [comment]
Okay, I'm thinking this is an SSR bug.

**Comment by brianlovin** [comment]
Spent tonight trying to figure out what's going on here, and I'm 99% sure it's an SSR bug. While digging in, I realized that SSR is actually broken on every page of Spectrum...we've lost all of the benefits of SSR somewhere along the way, because the client is having to do a fresh hydration on every page load. I think. 

This is hyperion locally:
<img width="841" alt="screenshot 2018-06-06 22 32 02" src="https://user-images.githubusercontent.com/1923260/41080046-73f5f4e2-69d9-11e8-8baf-8ffdf982b91b.png">

Notice the error `Warning: Did not expect server HTML to contain a <main> in <div>.` as a ssr mismatch in the render tree.

I found https://github.com/facebook/react/pull/12063#issuecomment-368380888 which was last updated 2 weeks ago and will help with debugging this, but not solving the underlying problem we have where our server is generating a different component tree than the client, so the client can't hydrate properly.

A lot of this is over my head, but may be worth prioritizing @mxstbr since this is the reason that every page has a flash when it loads. Video: https://www.dropbox.com/s/cve5c4u82zknorc/ssr-flash.mov?dl=0

**Comment by mxstbr** [comment]
Yeah we just gotta fix those HTML mismatches. I think it's got to do with the a11y fixes where we added `main`s to every page, can dig in today!

**Comment by mxstbr** [comment]
I'm going to use that PR locally to get better debugging information so that I can track down all the bits and pieces where the server markup differs from the client markup!

**Comment by mxstbr** [comment]
This was fixed with the SSR fixies
