### ISSUE TITLE
[Mobile] Refactor auth flow to not have expo steps

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3259]

**Comment by mxstbr** [comment]
Those are only in development:

> If the URL that the auth service is redirecting back to does not match the published URL for the app or the standalone app scheme (eg: exp://expo.io/@your-username/your-app-slug, or yourscheme://), then it will show a warning page before asking the user to sign in. This means that in development you will see this warning page when you sign in, a small price to pay for the convenience.

Source: https://docs.expo.io/versions/latest/sdk/auth-session

Closing!
