### ISSUE TITLE
[Mobile] New user onboarding

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3288]
When a user signs into the app for the first time we have to show them a new user onboarding.

- [x] Set username
- [ ] Explore top communities
- [ ] Create a new community

**Comment by brianlovin** [comment]
Definitely - I think implementing a lightweight community explorer + username setting component won't be *too* bad :P

**Comment by brianlovin** [comment]
How would you feel about *not* doing create community flow in this version?

**Comment by mxstbr** [comment]
The user onboarding kinda needs it?

**Comment by brianlovin** [comment]
I'm not *totally* convinced of that - I know we want it, just not sure if it should be a v1. It will add another few days of work right to build and test the community creation flow on mobile?
