### ISSUE TITLE
[Mobile] white background for placeholder in chatinput when no internet connection

### ISSUE THREAD

**Issue by dev-drprasad** [withspectrum/spectrum#3290]
**Issue Type**

- [x] Bug Report

**Description**
`Your message here` placeholder has wrong background colour in Mobile (ONLY) when no internet connection  and font-famliy looks like monospace
![screenshot_2018-06-11-11-08-22-919_com android chrome](https://user-images.githubusercontent.com/22687681/41227341-0aec57ae-6d92-11e8-8ff2-8af9b210b309.png)

**Comment by brianlovin** [comment]
cc @mxstbr running on Android :P

**Comment by brianlovin** [comment]
I believe this is fixed, closing
