### ISSUE TITLE
Only seeing old notifications, can't mark them as seen

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3296]
<img width="474" alt="screenshot 2018-06-11 21 55 33" src="https://user-images.githubusercontent.com/1923260/41270844-3ef3bae4-6dc2-11e8-9e16-8035163c5215.png">

This is starting to be reported by more and more people. I'm only seeing 3d old notifications and I can't get them to be marked as seen.

**Comment by mxstbr** [comment]
Yeah I've hit this once or twice. I wonder what that is 🤔

**Comment by mittalyashu** [comment]
There is no option to `mark them as seen` on mobile.

**Comment by brianlovin** [comment]
@mxstbr lol @uberbryn just figured this out without intending to :P

SSR broke this! To repro:
- open your dashboard
- hover over notifications dropdown
- notifications will be old (3d old for me)
- clearing notifications doesn't work

The fix that proves this is SSR:
- open your dashboard
- navigate to any page
- hover over notifications dropdown
- notifications will be new!

**Comment by brianlovin** [comment]
Also fairly sure ssr is breaking the dashboard logic that handles the `?t` query param to determine what to load

**Comment by brianlovin** [comment]
We just never realized this because SSR was broken for so long lol

**Comment by brianlovin** [comment]
Welp I was able to repro this consistently with the fix, but now i'm having trouble doing it again...regardless, this still feels like a backend caching thing because there are certain cases where I am seeing my latest notifications.

**Comment by brianlovin** [comment]
@mxstbr i'm going to look into this - we should consider this kind of issue a fix now: SSR is breaking notifications for people, breaking `?t` redirect, and causes a really harsh flash of content in the dashboard that shows the feed as it was 3 days ago.

**Comment by brianlovin** [comment]
Closing in favor of #3304 since there appear to be many bad ssr issues
