### ISSUE TITLE
Sign in button is not visible on android

### ISSUE THREAD

**Issue by dev-drprasad** [withspectrum/spectrum#3310]
**Issue Type**

- [x] Bug Report

**Description**

Sign in button is not visible in mobile (android). Bug present in both alpha and production

**Environment**

* android 7.1.2
* chrome 66.0.3359.158
* view port size: 384x800

**Screenshots**

<img src="https://user-images.githubusercontent.com/22687681/41336172-0d4e466a-6f09-11e8-9a2c-8a3f3ae9ea0d.png" width="300" height="533">

**Comment by brianlovin** [comment]
Thanks! Will try and patch this today
