### ISSUE TITLE
deleting a thread, logs out the user

### ISSUE THREAD

**Issue by itaditya** [withspectrum/spectrum#3332]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

When deleting a thread, the app logs the user out

**Comment by brianlovin** [comment]
We're no longer actively working on mobile - closing to clean up our issues, and we can search for [mobile] in the future when we get back to this :)

**Comment by brianlovin** [comment]
Stale, closing
