### ISSUE TITLE
[Mobile] Swap search tab to explore tab

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3342]
Since we're already having to build out a lot of the explore tab functionality in the onboarding, let's just make the search tab be the explore tab instead

**Comment by mxstbr** [comment]
I really liked that search interface though—maybe that just becomes a non-tab view with a global search icon at the top right or something?

**Comment by brianlovin** [comment]
Agreed - I think this is how we can simultaneously solve #3345  - basically just have a `Search` route that is a modal which can be triggered from anywhere. So home feed can trigger it, explore tab can trigger it, etc.

Not totally sure on that, but yeah, it'll definitely stick around in some form - just triggered differently

**Comment by brianlovin** [comment]
We're no longer actively working on mobile - closing to clean up our issues, and we can search for [mobile] in the future when we get back to this :)
