### ISSUE TITLE
[Mobile] Granular mobile push notification settings

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3347]
Once we have mobile push possible we definitely need the ability for people to unsub from certain types of notifications.

**Comment by mxstbr** [comment]
The newest version of Android requires us to use ["notification channels"](https://docs.expo.io/versions/v28.0.0/guides/notification-channels), which give users a unified interface in their system settings to toggle certain notification types on and off—so on that Android version we need to hide our custom settings, and also we gotta implement notification channels.

**Comment by brianlovin** [comment]
Woof. This sounds like this might be a pretty good chunk of work then

**Comment by brianlovin** [comment]
We're no longer actively working on mobile - closing to clean up our issues, and we can search for [mobile] in the future when we get back to this :)
