### ISSUE TITLE
[Mobile] Make it look good on Android

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3353]

**Comment by brianlovin** [comment]
Should be this be v1.1 - launch iOS first then do a round of cleanup and Android fast-follow?

**Comment by brianlovin** [comment]
I'm fairly concerned that the buttons in the header are going to be a big pain. There is a *lot* of behavior that `react-navigation` gives us for free with those buttons...we'll see!

**Comment by mxstbr** [comment]
Not sure I get what you're saying—we're currently just doing `import { Button } from 'react-native'`, so we just do `import { HeaderButton as Button } from '../../components/Buttons'`?

**Comment by brianlovin** [comment]
The navigation buttons do dynamic things with string truncation, arrows backwards, etc. on ios

**Comment by brianlovin** [comment]
<img width="397" alt="screenshot 2018-06-19 12 09 26" src="https://user-images.githubusercontent.com/1923260/41619018-a074a452-73b9-11e8-965c-82aa6d940bb2.png">

This is an example. If it's a back navigation button it adds the arrow back on iOS. Additionally, this will say "Messages" unless the header title is too long, in which case it will swap to "Back", like this screenshot

**Comment by mxstbr** [comment]
Sure, but I don't see why it wouldn't do that on Android too?

**Comment by brianlovin** [comment]
I'm not saying it's iOS-only, only that they might have custom button behavior in there and if we ovverride with our own custom-styled button we may lose that functionality. No use talking about it until we try and add our custom button and see what happens :)

**Comment by mxstbr** [comment]
From the `react-navigation` docs:

> `createStackNavigator` provides the platform-specific defaults for the back button. On iOS this includes a label next to the button, which shows the title of the previous screen when the title fits in the available space, otherwise it says "Back".

[From here](https://reactnavigation.org/docs/en/header-buttons.html#customizing-the-back-button), although it doesn't mention anything about Android I assume they're similarly smart about it.

**Comment by mxstbr** [comment]
It does the same thing on Android out of the box:

![screenshot_20180620-104948](https://user-images.githubusercontent.com/7525670/41647894-cbe2227c-7477-11e8-92a6-a9b32c3abb7f.jpg)

So all we gotta do is fix our own custom `headerRight` buttons, like the "Details" one here, and it won't break anything :tada:

**Comment by mxstbr** [comment]
Here's what the Material Design Spec has to say about the top app bar: https://material.io/design/components/app-bars-top.html

This gif illustrates it pretty perfectly:

![topappbars-behavior-nesting](https://user-images.githubusercontent.com/7525670/41648322-d740f6ec-7478-11e8-967d-8a7fd2c759a0.gif)

So pretty much all we gotta do is replace our `headerRight` custom text-based buttons with icons, at least on Android.
