### ISSUE TITLE
Add signin button to logged-out navbar

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3481]
Not sure when this went missing, I know for a fact we used to have that:

<img width="773" alt="screen shot 2018-07-04 at 09 44 54" src="https://user-images.githubusercontent.com/7525670/42263673-ff11600c-7f6e-11e8-80a8-53f7efa6097d.png">

We should really add it back, right now it's really hard to sign in from some views.

**Comment by dev-drprasad** [comment]
can i start working on this ?

**Comment by dev-drprasad** [comment]
where sign-in button should locate ? what about its styling ?

**Comment by mxstbr** [comment]
Yes please! On the left side of the signed out navbar, could just be some text that says "Login/Sign up" for now!

**Comment by dev-drprasad** [comment]
@mxstbr  Its review time 🧐
