### ISSUE TITLE
Show preferred aspect ratio for profile and cover photos which suits best for both mobile and desktop

### ISSUE THREAD

**Issue by satyarohith** [withspectrum/spectrum#3505]
**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** 

Showing preffered photo size might help users when they upload profile and cover photos.

E.g. When we hover
![screenshot](https://user-images.githubusercontent.com/29819102/42375990-25b47834-813b-11e8-956f-5a40fcc5328f.png)

Link to [Spectrum thread](https://spectrum.chat/thread/9e930c0d-d9af-4cda-9eda-e5d2a45d6c4f)

**Comment by brianlovin** [comment]
Honestly we aren't doing that great of a job of matching cover photo aspect ratios when we show cover photos in different contexts or on different screen sizes. I definitely agree we need this, but should also maybe align around an aspect ratio rather than pixel value. What do you think?

**Comment by satyarohith** [comment]
Aspect ratio is better than pixel value and also using [Client Hints](https://docs.imgix.com/tutorials/responsive-images-client-hints) might be helpful to serve responsive images from server. What do you think about using Client Hints?

**Comment by brianlovin** [comment]
We aren't rendering the hint, but we have made it official that 1280x384 is the correct ratio + size.
