### ISSUE TITLE
'Search for people' suggestion dropdown in private messages breaks in safari ios

### ISSUE THREAD

**Issue by satyarohith** [withspectrum/spectrum#3509]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

![img_0115](https://user-images.githubusercontent.com/29819102/42433336-7f5730ce-836c-11e8-92dc-f150242ddd67.jpg)

**Comment by brianlovin** [comment]
Can repro. Investigating.
