### ISSUE TITLE
Service worker failure reports are increasing

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3519]
https://spectrum.chat/parcel?thread=0099a3c9-79e3-4c38-8c3c-885c6312f6ec

Lots of people have been reporting increased frequency of app crashes due to broken service worker or fetching old files. I'm not sure exactly how to start diagnosing this as it's all happening on prod. cc @mxstbr if you have any guidance here I can jump in, otherwise I would like to know what we'd realistically face to disable the service worker for the time being until we come to a more stable implementation. I know it will increase load times by a certain amount, and may increase pressure on us to reduce bundle size in the short term.

**Comment by ryota-murakami** [comment]
Unregister?
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister

**Comment by brianlovin** [comment]
@mxstbr any additional thoughts here? I believe this issue is causing people to get stuck on `/auth` where the request gets processed in the client as a community, versus sending that request to the api.

**Comment by mxstbr** [comment]
Yeah let's disable it, just not sure how.

**Comment by brianlovin** [comment]
We haven't had this issue in a long time now.
