### ISSUE TITLE
Sign up with email

### ISSUE THREAD

**Issue by cbluth** [withspectrum/spectrum#3723]
I want to try spectrum chat, but I'd rather not use my social media accounts. Are there plans to allow signups via email?

**Comment by brianlovin** [comment]
We'd like to get to this sometime in the future, it's definitely a highly requested addition!

**Comment by DylanVann** [comment]
I'd like it.

- I hesitate before using anything that won't let me use an email to sign up.
- In a few years I might not be using Facebook, Google, Twitter, or GitHub.
- I also don't want to remember which of those I use to sign onto things. I'd prefer to just use a password manager.
- It's likely I'll still be using email.
- Alternatively a username is fine.

**Comment by mxstbr** [comment]
As I said in https://github.com/withspectrum/spectrum/issues/4661, this is unlikely to land anytime soon since we were acquired by GitHub!
