### ISSUE TITLE
API logs `undefined` over and over and over in production

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3746]
Not sure what's up with this, it's surely not helping our performance...

<img width="1552" alt="screen shot 2018-08-09 at 17 14 05" src="https://user-images.githubusercontent.com/7525670/43908203-ad61eede-9bf7-11e8-8d41-20e2766aa5ee.png">

I think it might potentially be in a dependency? I! couldn't find _any_ `console.log`s out of place in the entire built API, so I'm not sure what's going on.

**Comment by brianlovin** [comment]
Uh wow, that's not ideal...

**Comment by mxstbr** [comment]
This comes from `create-subscription-server.js`, the `.catch` blocks in both `onDisconnect` and `onConnect`. Digging into why these throw, but that explains why I haven't seen many online indicators recently haha
