### ISSUE TITLE
Markdown parser considering asterisks inside inline code to set bold

### ISSUE THREAD

**Issue by sergiodxa** [withspectrum/spectrum#3757]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

![](https://kap-qxrhywkyue.now.sh/)

When writing an asterisk inside an inline code and then another outside the Markdown parser transform it to bold and I need to cmd+z to undo the bold.

**Comment by mxstbr** [comment]
Hmm, strange, I thought we fixed this 🤔 Will dig in tomorrow!

**Comment by mxstbr** [comment]
This is fixed!
![screen shot 2018-08-22 at 11 26 01](https://user-images.githubusercontent.com/7525670/44455374-2ec8fc00-a5fe-11e8-85b0-360c68823bbe.png)
