### ISSUE TITLE
Store env variables in with dotenv

### ISSUE THREAD

**Issue by iamclaytonray** [withspectrum/spectrum#3813]
I know that this is open source but even with open source, I imagine you probably want to store environment variables inside of a `.env` file. Specifically, I am referring to all of the OAuth keys. Is there a reason why they are shared publicly?

**Comment by brianlovin** [comment]
We use `now-secrets.json` in combination with `now-env` to handle environment variables. In the repo we have a `now-secrets.example.json` that is used to get contributors up and running locally :)

**Comment by iamclaytonray** [comment]
Okay. So the keys in [this file](https://github.com/withspectrum/spectrum/blob/alpha/api/authentication.js) are not real keys?

**Comment by brianlovin** [comment]
Those are client keys, so fine to expose, although for consistency and clarity we could probably move those to be env variables :)

**Comment by mxstbr** [comment]
Yeah those are all handled!
