### ISSUE TITLE
Code Blocks Create Separate Instances for Every Line of Text

### ISSUE THREAD

**Issue by davidluhr** [withspectrum/spectrum#3815]
When creating a post, the code block (triple backticks) isn't working as expected. When pasting multiple lines of text into a code block, a new code block is created for each line. Additionally, even with a language selected on the initial code block, no language is set for any of the extraneous instances.

Here's a link to my post with this bug: https://spectrum.chat/?t=9441056c-9291-4138-98e6-cbb6028c1f00

Additionally, here's a screenshot of the formatting issue:
![spectrum-code-block-formatting-bug](https://user-images.githubusercontent.com/16038754/44437459-a273f600-a577-11e8-864e-96d6b3b7601f.JPG)

## Steps to Recreate
1. Create a new post
1. Start a code block with ` ``` ` 
1. Press `Enter/Return` to open a code block
1. Paste any multi-line text into the code block
1. Observe the separate code block instances for every line of pasted text.

## My setup
- Firefox 61
- Windows 10

**Comment by brianlovin** [comment]
Dug around to see if I'd opened an issue for this before, because I feel like it's been one of the worst longstanding issues we have with our editor. Thanks for resurfacing @davidluhr!

**Comment by mxstbr** [comment]
Hmm I thought we'd fixed that... 🤔 Will dig in!
