### ISSUE TITLE
Can't access spectrum.chat

### ISSUE THREAD

**Issue by LeKoArts** [withspectrum/spectrum#3823]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

So I was the guy who said that he constantly gets logged out:
https://github.com/withspectrum/spectrum/pull/3818

Well after the hotfix and ~ 24 hours later I can't access spectrum.chat anymore at all. Not only on my iPhone but also on the PC. I tried it in Incognito mode (-> no cookies) but the Twitter login doesn't redirect. The home page (logged in) only shows a loading indicator and no console errors.
On my iPhone the site doesn't even load at all.

**Comment by brianlovin** [comment]
We're currently experiencing some downtime, working on it! Sorry for the trouble :(
