### ISSUE TITLE
Channel Header displaying above Thread

### ISSUE THREAD

**Issue by pedrolucasp** [withspectrum/spectrum#3839]
Hello, when opening a Thread on the sidebar, the channel header keep displaying on top of the post header. 
![screen shot 2018-08-24 at 09 55 56](https://user-images.githubusercontent.com/861658/44585978-7ed1cb00-a784-11e8-86e4-a4852a51b4f1.png)

**Comment by brianlovin** [comment]
Thanks for the heads up! We'll get this cleaned up :)
