### ISSUE TITLE
Don't create notifications for self-thread-likes 

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3856]
https://alpha.spectrum.chat/?t=8bf4d55c-9ef6-4ba9-b27f-abca4cf00faa

**Comment by mxstbr** [comment]
Why do we let people like their own thread in the first place?!

**Comment by brianlovin** [comment]
You can retweet your own tweets? :P

**Comment by mxstbr** [comment]
Yeah but you can't favorite them can you?! I'd let people x-post their own threads once for sure though

**Comment by brianlovin** [comment]
You can favorite your own tweets, yes. And self like Fb posts. Seems to be a pretty common thing?


________________________________

**Comment by mxstbr** [comment]
Oh what. Okay then...
