### ISSUE TITLE
Inserting link in text clears all text

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3860]
Video: https://www.dropbox.com/s/pusm2x4n3ct2ik9/bad-link-insertion.mov?dl=0

cc @mxstbr this has been killing me when trying to post show notes from episodes on Spectrum 😭

**Comment by mxstbr** [comment]
Will investigate tomorrow!

**Comment by mxstbr** [comment]
Fixed by #4472 and #4564
