### ISSUE TITLE
Avatar online indicators not working anymore

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3874]
https://spectrum.chat/thread/981cf8f6-07fd-43bf-8d97-696af5b5500c

**Comment by brianlovin** [comment]
Sooo @mxstbr I *think* this might be a big with styled-components, possibly...

I spent time poking in `src/components/avatar/style` at the `Status` component we create. When that renders out, no `:after` pseudoelement hits the dom. If, however, I remove all cases where we call `${props => ...}` in that `:after { ... }` block the indicators show up.

To repro, go into that file and just paste in:

```
&:after {
      content: '';
      position: absolute;
      display: inline-block;
      width: 8px;
      height: 6px;
      background: ${theme.success.alt};
      border-radius: 100%;
      border: 2px solid ${theme.text.reverse};
      bottom: 0;
      right: 0;
      z-index: ${zIndex.avatar};
    }
```

You should now see the `:after` pseudoelement in the dom and online indicators showing up. 

Now, simply replacing the display property with:
```
display: ${props => props.isOnline ? 'inline-block' : 'none'};
```

The online indicators should break (they do for me). 

If I hard code a prop interpolation, eg: `${props => `${props.size / 8}px`}` things work. 

So I think it might be that the ternary conditionals in the prop interpolation is breaking things?

**Comment by mxstbr** [comment]
Can't repro, here's a codesandbox with our status component where it renders the after just fine with the same code: https://codesandbox.io/s/qx37pkz04q

I had to take out some of the other interpolations since I didn't have those vars, but other than that the `display` interpolation works perfectly fine?

**Comment by mxstbr** [comment]
Fixed
