### ISSUE TITLE
Denormalize expensive GraphQL fields

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#3875]
Gotta look at Engine to figure out which ones those are

**Comment by mxstbr** [comment]
This should be a solid start:

- User
  - [ ] totalReputation
  - [ ] isPro
- Thread
  - [ ] messageCount
  - [ ] maybe reactions?
- Community
  - [ ] all of metaData
    - [ ] recompute onlineMembers once an hour

Basically all the counts, and `isPro` because that's super slow and we fetch it every time.

**Comment by mxstbr** [comment]
No because engine can't cache subfields I'm 99% sure—so we'd have to cache all communities without having access to invalidation. This (which we currently have) doesn't work:

```GraphQL
type Community {
  metaData: CommunityMetaData @cacheControl(maxAge: 84600)
}

community(slug: "zeit") {
  # This will never be a cache hit because the Community object itself has a TTL of 0
  metaData {
    # ...
  }
}
```

We'd have to do this:

```GraphQL
# Cache the entire community object
type Community @cacheControl(maxAge: 84600) {
  # ...
}
```

But obviously if we do that and somebody edits the community, they won't see the changes until the TTL expires which really really sucks :confused:

 /cc @martijnwalraven for confirmation

**Comment by brianlovin** [comment]
Then let's just cache these expensive fields ourselves?

https://github.com/withspectrum/spectrum/pull/3771

Couldn't we just implement that for the 5 or 6 places we do expensive counting and call it a day?

**Comment by mxstbr** [comment]
I mean sure, yeah, sounds good

**Comment by brianlovin** [comment]
We did this.
