### ISSUE TITLE
Can't paste inside a code block with selected text

### ISSUE THREAD

**Issue by carloslfu** [withspectrum/spectrum#3877]
Follow the next steps to reproduce:
- Create a new conversation
- Add a code block with ````
- Copy some text to the clipboard
- Add some code to the code block
- Select part of the text inside the code block
- Try to paste the text from the clipboard over the selected text (press `Crtl + v` or `Cmd + v`)

As a result the paste action fails.

**Comment by brianlovin** [comment]
Thanks for the heads up! Seems like we've got a few issues cropping up with code blocks. Will dig in cc @mxstbr :)

**Comment by mxstbr** [comment]
I recently added custom paste behavior so that pasting into code blocks works at all and doesn't create a million code blocks—while that fixed the million code blocks issue, it probably broke this in the process 😅 

Will look into this soon!

**Comment by mxstbr** [comment]
This will be fixed by the upcoming move to plaintext text editing in #4564 and #4472!
