### ISSUE TITLE
CI is creating bad deploy aliases via now

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#3943]
Every alpha merge is creating an alias for `alphapispectrum.spectrum.chat` and `hyperionalphaspectrum.spectrum.chat` - the hyperion one keeps getting scaled to 4 as well, so we had a ton of old deploys that didn't do anything that were throwing some errors and chewing up sentry logging

**Comment by mxstbr** [comment]
Wat, that's super strange. It's definitely set correctly in our .circleci.yml:

https://github.com/withspectrum/spectrum/blob/da379f1c49fd6208152a6e2a8cb5e3bc0127e67c/.circleci/config.yml#L129-L137

/cc @siddharthkp did you change anything in now-cd?

**Comment by mxstbr** [comment]
Is a bug with now-cd v1.3.5: https://github.com/siddharthkp/now-cd/issues/25

**Comment by brianlovin** [comment]
This is still happening - do we need to upgrade on our end somewhere @mxstbr ?
<img width="923" alt="screenshot 2018-10-02 15 18 03" src="https://user-images.githubusercontent.com/1923260/46334396-70fe4800-c656-11e8-9f14-841cd0b17750.png">

**Comment by siddharthkp** [comment]
Can you confirm the version installed?

**Comment by mxstbr** [comment]
Here's a log: https://circleci.com/gh/withspectrum/spectrum/15114

Not sure how to tell which version is running?
