### ISSUE TITLE
Show recent message as Image/media instead of showing the image source link

### ISSUE THREAD

**Issue by satyarohith** [withspectrum/spectrum#3979]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [ ] Bug Report
- [X] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** 
When we send a photo, the recent message shows the image source link which is quite confusing whether we shared an Image or URL.
![spectrum-recent-messages](https://user-images.githubusercontent.com/29819102/46289144-cdedf580-c5a5-11e8-97fa-4a2cf170a8ee.png)

**Comment by mxstbr** [comment]
This was fixed!
