### ISSUE TITLE
Oops, something went wrong. Please try again! 

### ISSUE THREAD

**Issue by davidalekna** [withspectrum/spectrum#3991]
Hi, I can't login for some reason 🤔 I get a blank screen and this message when trying to authenticate with github 

Oops, something went wrong. Please try again! (Error ID: 47618e86bb56436ca7279d734e9ffaab)

**Comment by davidalekna** [comment]
Seems to be fixed now so I'll close it :) thanks

**Comment by mxstbr** [comment]
Awesome, great to hear!
