### ISSUE TITLE
Profile Dropdown Isn't Working as Supposed in All Pages

### ISSUE THREAD

**Issue by satyarohith** [withspectrum/spectrum#4035]
**Issue Type (check one)**

- [X] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**
Pages effected:
/faq
/support 
/features
/about
![spectrum-bug](https://user-images.githubusercontent.com/29819102/46580159-35d88c00-ca3d-11e8-8302-0e3987400f77.gif)

**Comment by brianlovin** [comment]
Thanks for the heads up! cc @superbryntendo if you're interested in snagging this one, I may have broken it when removing the pricing page link

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@brianlovin can i work on this
