### ISSUE TITLE
Updating profile photos/cover photos doesn't work

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4076]
Okay, so a few super weird things are going on here after a while of digging in. Let's talk through this a bit @mxstbr because I'm a bit stuck.

Here's what I found:

1. If you upload a cover photo, the `updateCookieUserData` function fails. Here's the error:

```js
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at passport.serializeUser (/home/nowuser/src/webpack:/api/authentication.js:56:55)
```

Weird. So I console logged what's happening at that position and the `user` object that's getting passed to the serialization is this:

```js
{
  // ... normal user object
     coverPhoto: 'https://spectrum.imgix.net/users/01p2A7kDCWUjGj6zQLlMQUOSQL42/VGLu7KguU-figma.jpg', // this is the *old* profile photo being serialized
     file: undefined, // this shouldn't be here
     coverFile: Promise { [Object], domain: [Object] } // this is weird, and seems likely to be the cause of the error above
```

So we're trying to serialize some funky stuff to a string, which breaks. If I throw a `.catch` on the `await updateCookieUserData(...)` execution, the script does continue and manages to properly upload the new file as my new cover photo. Yay! However, more problems arise on the client:

2. When I return to my user profile on the client, I almost always see the *old* cover photo. Why is that?

<img width="1439" alt="screenshot 2018-10-18 21 23 13" src="https://user-images.githubusercontent.com/1923260/47197587-0b7bae00-d31c-11e8-97bc-2011d348a2d4.png">

Notice that the *old* cover photo is being loaded from a memory cache on the client. I'm honestly not sure why that's happening. Anyways, it flashes the old one (because it was cached) and then it updates to show the new one.

As I've typed this out here's what I think is happening:
- we're executing `updateCookieUesrData` too early - it executes before we actually perform the `editUser` mutation. Therefore it's creating a new cookie with old data from the db. So on the client, the cookie has the user information containing the old cover photo url. Some other request to get the latest currentUser from the database eventually returns the new cover file.

So @mxstbr, three asks from you:
1. Could you double check the logic in `mutations/editUser`, specifically the location and sequence of when the cookie gets re-serialized?
2. Could you also double check how we should handle in-progress file uploads during this step. E.g. the error snippet above showing that we're trying to to serialize a Promise with some kind of File type.
3. Help me double check my thinking on the culprit here, and remind me if I'm missing something we're doing on the client re: image caching just in case I've forgotten something :) (I think maybe Imgix does this automatically...)

Thank you!

**Comment by brianlovin** [comment]
I uploaded a second cover photo to see if it would update to start showing my first upload (e.g. test if it's always one step behind). It's not the case. I decoded my cookie and found some interesting data there, let's talk about it in person.

**Comment by brianlovin** [comment]
Ran one more test with the following:

Moved `updateCookieUserData` to run *after* `editUser` runs and returns the DBUser record. This works better and properly sets the right information on the new cookie. However, I still the the flashing of my *original* (e.g. 3 uploads ago) cover photo as it's being loaded from memory somehow.

Progress, but let's chat about this to think through the remaining issues :)

**Comment by brianlovin** [comment]
Whoa, noticed one more thing: when I view my profile after uploading a cover photo it logs me out. I have a session cookie that contains some weird data, which I'm guessing is why. If I re-login with Twitter it crashes and redirects me to spectrum.chat (from alpha). If I then go back to alpha and refresh things are fixed and I'm logged back in. Feels reminiscent of the bug we fought through 2 weeks ago with the cookies @mxstbr

**Comment by mxstbr** [comment]
You just have to do this with `coverFile` too to resolve the JSON error:

https://github.com/withspectrum/spectrum/blob/alpha/api/mutations/user/editUser.js#L53

Not sure what's up with the caching, maybe it's S3 caching?
