### ISSUE TITLE
Firefox error "Something went wrong" with thread view

### ISSUE THREAD

**Issue by flaki** [withspectrum/spectrum#4113]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

The non-logged-in thread view seems to be broken on Firefox (tested with stable & nightly on Linux), no specific error in the console is shown, the page just notes "Something went wrong".

Can be reproduced [on this URL](https://spectrum.chat/thread/fa46c456-0d94-49d4-a905-7760285cc7e5) on all of my devices.

![screenshot from 2018-10-24 16-37-30](https://user-images.githubusercontent.com/2089432/47438817-73fadd00-d7ab-11e8-96ae-727c9595a001.png)

**Comment by flaki** [comment]
This thread is in [`spectrum.chat/clouduboy`](https://spectrum.chat/clouduboy/). This issue might be stemming from the fact that this is a "private" community -- but there's no indication or toggle of setting the community private or not anywhere in the UI. The only indication in the settings is the ability to "create a link to join a private community" box.

**Comment by brianlovin** [comment]
@flaki thanks for the note here - yeah it seems like this is a thread in a private community so it's not visible signed-out. Right now we don't have the option in the UI to convert a private community to public, for privacy reasons. If you'd like help manually switching your community to be public just let me know though :)

**Comment by flaki** [comment]
@brianlovin yes I would like the manual switch for `clouduboy`, let me know if you need anything else from my side to make that happen.

I understand the reasons why there is no user-changable affordance for the switch in the UI but I would think having this explained/exposed in the UI somewhere would save some folks from quite a bit of confusion.

**Comment by brianlovin** [comment]
Definitely @flaki :) Your community is now public.
