### ISSUE TITLE
Make it harder for channel owners to leave channel

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4114]
It's too easy for the owner of a private channel to get locked out by clicking the 'member' button on the channel view.

**Comment by mxstbr** [comment]
Clicking this "Member" button on both channel and community views removes you from them:

<img width="342" alt="screenshot 2018-11-12 at 16 52 18" src="https://user-images.githubusercontent.com/7525670/48358592-5bd7f880-e69b-11e8-9b95-1a4a442b7d1c.png">

That should require another confirmation dialog and be more obvious!

**Comment by maxparelius** [comment]
Will submit PR for this soon!

**Comment by mxstbr** [comment]
Awesome, let us know as soon as you got anything and we'll review it!

**Comment by mxstbr** [comment]
@maxparelius how are you getting along, did you get stuck somewhere?

**Comment by brianlovin** [comment]
Yeah, happy to help with this if it's going to take a while. Feels like a good win to make this a better experience for team members
