### ISSUE TITLE
Some issues found by static analyzer

### ISSUE THREAD

**Issue by woongsikchoi** [withspectrum/spectrum#4121]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

Hi, I am a developer of JavaScript static analyzer called [DeepScan](https://deepscan.io).

For benchmarking, I analyzed spectrum project's code with DeepScan and found some issues that may cause incorrect behavior and thus better to be fixed. The issues are:

- **Issue 1**: Variable 'user' has a falsy value because of the condition '!user' at line 56 . But its property is accessed at this point. (src/views/userSettings/index.js)

```javascript
    // the user is logged in but somehow a user wasnt fetched from the server prompt a refresh to reauth the user
    if ((currentUser && !user) || (currentUser && !user && !user.id)) {
```
I think the second condition should be `currentUser && user && !user.id`.

- **Issue 2**: Variable 'channel' has a falsy value because of the condition 'channel' at line 453 . But its property is accessed at this point. (src/components/threadComposer/components/composer.js)

```javascript
      activeCommunityChannels.find(channel => {
        if (channel) return null; // Here is line 453
        // If there is an active channel and we're switching back to the currently open community
        // select that channel
        if (
          this.props.activeChannel &&
          this.props.activeCommunity === newActiveCommunityData.slug
        ) {
          return channel.slug === this.props.activeChannel; // Here is the issue location
        }
        // Otherwise select the default one
        return channel.isDefault;
        // Default to the first channel if no default one can be found
      }) || activeCommunityChannels[0];
```

I think line 453 should be `if (!channel) return null;`

The full issue list can be found in this [link](https://deepscan.io/dashboard/#view=project&tid=391&pid=3507&bid=31275&subview=issues).

**Comment by brianlovin** [comment]
This is my first time seeing DeepScan - thanks so much for the notes! @mxstbr should we set this up for Spectrum?

**Comment by brianlovin** [comment]
@woongsikchoi - the following two errors don't seem quite right:

<img width="1003" alt="screenshot 2018-10-25 09 52 37" src="https://user-images.githubusercontent.com/1923260/47517008-bcfa7200-d83b-11e8-8015-03cac0ce75ec.png">

In both of those cases, `channel` is an object. I think the previous check for `if (channel)` made deepscan think that it's a falsy value?
