### ISSUE TITLE
Shut down links.spectrum.chat

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4259]
@mxstbr can you weigh in on if we're good to shut down `links.spectrum.chat`? I'm 99% we don't use it anywhere anymore (per https://github.com/withspectrum/spectrum/pull/4126) - but good to get a second brain on this :)

**Comment by mxstbr** [comment]
Doesn't look like it!

```
~/projects/withspectrum/spectrum 
❯ ag links.spectrum.chat

~/projects/withspectrum/spectrum 
```

Let's shut it down

**Comment by brianlovin** [comment]
Done
