### ISSUE TITLE
Static js file caching doesn't update in desktop app

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4287]
@mxstbr I shipped 2.4.73, which included #4274. I loaded the desktop app, and user activity indicators were working! I then noticed a bug and shipped #4285. When I reloaded the desktop app, quit and restarted, etc, it continued to load the code cached from 2.4.73. I confirmed that clearing the browser cache forced it to download the new code from #4274 and fix the bug.

I didn't have this experience in Chrome - so perhaps it's something desktop-app specific. Anyways: could you help me look into this or possibly revert js file caching so that desktop users don't get forever stuck on 2.4.73?

**Comment by mxstbr** [comment]
Hmm, that doesn't make any sense. 🤔 Only the JS files should be browser cached, which change file name on every deploy. Let's add an exception for HTML files is my hunch for fixing this?

**Comment by brianlovin** [comment]
Yeah, let's try that. Could you give it a test today?

**Comment by mxstbr** [comment]
👉 #4289
