### ISSUE TITLE
Thread preview images broke

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4310]
@brianlovin the imgix signature stuff broke thread preview images. For example, click [this link to a thread preview image that worked before](https://spectrum.imgix.net/default_images/twitter-share-card.png?blend64=aHR0cHM6Ly9hc3NldHMuaW1naXgubmV0L350ZXh0P2g9MjcwJnR4dDY0PVQzQmxiaUJ6YjNWeVkyVmtJR3hoYm1ScGJtY2djR0ZuWlNCMWMybHVaeUJvYjI5cmN5QmhibVFnYzNWemNHVnVjMlUmdHh0YWxpZ249bGVmdCxtaWRkbGUmdHh0Y2xpcD1lbmQsZWxsaXBzaXMmdHh0Y29sb3I9ZmZmZmZmJnR4dGZvbnQ9SGVsdmV0aWNhLEJvbGQmdHh0bGVhZD0xNiZ0eHRzaXplPTU2Jnc9MTIwMA&bm=normal&bx=180&by=170&mark64=aHR0cHM6Ly9hc3NldHMuaW1naXgubmV0L350ZXh0P2g9NjQmdHh0NjQ9YzNCbFkzUnlkVzB1WTJoaGRDOXlaV0ZqZEEmdHh0YWxpZ249cmlnaHQsbWlkZGxlJnR4dGNvbG9yPTQ0MDBDQyZ0eHRmb250PUhlbHZldGljYSxCb2xkJnR4dHNpemU9MzY&markalign=left,bottom&markpad=24&markx=100&w=1500)

It says "URI signature match failed". How can we quickly fix this? It's hurting the share-ability of threads quite a bit

**Comment by brianlovin** [comment]
Yep it just needs to get signed. I can't find where we generate those previews with a cursory project search, but you'd want to just pass it into our signing utility, like this: https://github.com/withspectrum/spectrum/blob/alpha/api/queries/community/coverPhoto.js#L7

**Comment by mxstbr** [comment]
Uhh, those are generated on the client dynamically... https://github.com/withspectrum/spectrum/blob/alpha/src/helpers/generate-image-from-text.js

I guess we'll just have to add a new field on the API level (Thread.metaImage?) that returns a signed URL rather than generating dynamically on the client?

**Comment by brianlovin** [comment]
> I guess we'll just have to add a new field on the API level (Thread.metaImage?) that returns a signed URL rather than generating dynamically on the client?

Yep, that sounds like the right solution - a bit of a pain, but if we have to sign everything it's the only way
