### ISSUE TITLE
No option to remove community background image

### ISSUE THREAD

**Issue by cloudrex** [withspectrum/spectrum#4385]
**Issue Type**
- [X] Feature Idea

Currently there's no way to remove a custom-set background image for communities. It would be really helpful to allow to remove the currently set background image and reset it to the default one.

![no-remove-background](https://user-images.githubusercontent.com/41349879/49319575-726bb580-f4cb-11e8-968a-26ac3d1bed3f.png)

**Comment by ThomasRoest** [comment]
I would like to try this, from what I see it should be a button / icon that resets the coverfile and coverphoto state

```
this.setState({
     coverFile: null,
     coverPhoto: '',
 });
```

**Comment by ThomasRoest** [comment]
I would like to try this, I'm guessing this should be possible in both the create new community form and  the community settings form

**Comment by brianlovin** [comment]
@ThomasRoest correct - see `api/utils/get-random-default-photo.js` for the options available and `api/models/community:createCommunity` for how this is implemented currently at community creation time

**Comment by ThomasRoest** [comment]
I'm getting `Failed to load resource: the server responded with a status of 403 ()` from imgix. When loading default cover photos e.g. `default_images/cover-violet.svg` in development

**Comment by ThomasRoest** [comment]
ok, I haven't changed anything, just exploring. 

So if I'm correct, there should be a default cover photo with a color if the user does not upload anything. Right now this does not seem to work. And the default cover is just black / empty. 

Is this expected in development ( because of the things you mentioned ) or should this work?

<img width="1277" alt="image 2018-12-21 at 11 09 25 am" src="https://user-images.githubusercontent.com/4428811/50337553-c5a4b700-0511-11e9-9118-3c9516cd141b.png">

**Comment by brianlovin** [comment]
In `src/components/profile/coverPhoto.js`, if the component receives null it sets the `background-image` property to `none` - this is why it's just rendering a black background there.

**Comment by ThomasRoest** [comment]
What do you think about this approach? In `api/models/community.js#editCommunity`

When editing a community 
` // if the coverPhoto url was deleted and no new file was added, set a default coverphoto
      if (!coverPhoto) {
        const { coverPhoto } = getRandomDefaultPhoto();
        return db
          .table('communities')
          .get(communityId)
          .update({ ...community, coverPhoto }, { returnChanges: 'always' })
          .run()
          .then(result => 
....
....etc
`

**Comment by ThomasRoest** [comment]
Would it be an idea to reset the coverPhoto url? Without actually deleting the file on s3?

so `in/api/models/community.js:editCommunity`

    // if the coverPhoto url was deleted and no new file was added, set a default coverphoto
    if (!coverPhoto) {
    const { coverPhoto } = getRandomDefaultPhoto();
    return db
      .table('communities')
      .get(communityId)
      .update({ ...community, coverPhoto }, { returnChanges: 'always' })
    .run()
    .then(result => .....etc

**Comment by brianlovin** [comment]
@ThomasRoest it seems like that could work, yes - so we'd just need to handle setting the `coverPhoto` state in the client to `null`, right?

**Comment by ThomasRoest** [comment]
yes so maybe something like this: 

![screen recording 2019-01-07 at 09 38 am](https://user-images.githubusercontent.com/4428811/50757570-116c9580-1260-11e9-9691-ae5db438fa0f.gif)

**Comment by brianlovin** [comment]
It might feel more natural to have something like this remove button on the image uploader for chat, but on top of the cover photo itself:

**Comment by brianlovin** [comment]
It might feel more natural to have something like this remove button on the image uploader for chat, but on top of the cover photo itself. GitHub isn't letting me upload a screenshot right now...

**Comment by ThomasRoest** [comment]
![addicondelete](https://user-images.githubusercontent.com/4428811/50898279-f8561700-140e-11e9-9a4d-dfd9e4d4d97a.gif)

**Comment by mxstbr** [comment]
That looks great! Want to submit a first PR so we can iterate further?

**Comment by brianlovin** [comment]
@ThomasRoest this looks great! Can you swap out the 'x' with '×' - the styles for that should all match up to the remove image button in the chat input :)
