### ISSUE TITLE
Having trouble adding profile avatar / save profile settings

### ISSUE THREAD

**Issue by thundernixon** [withspectrum/spectrum#4387]
**Issue Type (check one)**

- [x] Bug Report 🐛
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (type any text below)** -->

I'm attempting to update my profile picture, but I'm being blocked by the error `Please add a valid email address.`

However, I have tried adding this multiple times, and I have also clicked "Go to my dashboard" in the welcome email it generates. Unfortunately, I am so far unable to update the photo (or email) in a way that sticks, so I'm stuck as an astronaut icon. The image I'm trying to upload is only 512x512 px, and 23kb, so I don't think that should be blocking me. 

I get an error, so I add my email and get asked to go check it...

![image](https://user-images.githubusercontent.com/7355414/49323580-86bfaa80-f4eb-11e8-8107-10346eeb5cf6.png)

...so I do...

![image](https://user-images.githubusercontent.com/7355414/49323611-136a6880-f4ec-11e8-95b4-13de98bab717.png)

...and I come back ... and try again because I still have a blank avatar, and get the same error...

![image](https://user-images.githubusercontent.com/7355414/49323589-bb336680-f4eb-11e8-9623-42c7db350fca.png)

...and still no luck.

![image](https://user-images.githubusercontent.com/7355414/49323606-0483b600-f4ec-11e8-9c09-c4dda30211b5.png)

---

Also, Major kudos on the announcement today of joining Github, today! It may be that your servers are getting pounded with new signups, causing this issue. However, I do _think_ I've also tried to upload a photo several times in the past, so it may be something else. ¯\_(ツ)_/¯

**Comment by brianlovin** [comment]
You should be receiving an email that asks you to confirm the new email you've typed in - make sure you click the link in that email and then things should work :)

**Comment by brianlovin** [comment]
@thundernixon I'm investigating some elevated failure rates with our email provider. In the meantime could you email me (brian at spectrum dot chat) from the email address you'd like added to your Spectrum account, and I'll get you set up manually for now to unblock this :)

**Comment by brianlovin** [comment]
This has been resolved
