### ISSUE TITLE
/api is exposed (GraphQL playground)

### ISSUE THREAD

**Issue by cloudrex** [withspectrum/spectrum#4388]
**Issue Type**

- [X] Bug Report

https://spectrum.chat/api exposes a GraphQL playground. I'm pretty sure that's not intended.

![playground](https://user-images.githubusercontent.com/41349879/49324219-934a0000-f4f7-11e8-8a2a-136d4918f18d.png)

**Comment by mxstbr** [comment]
You're right, we should be disabling that! We disable introspection, so there isn't really much you can do with it though.

**Comment by dev-drprasad** [comment]
@mxstbr is it still issue ?? can i pick it ??

**Comment by mxstbr** [comment]
Yes please do @dev-drprasad! :pray:

**Comment by dev-drprasad** [comment]
@mxstbr what about completely disabling playground ?
something like:
```
  playground: process.env.NODE_ENV !== 'production' && {
    settings: {
      'editor.theme': 'light',
    },
    tabs: [
      {
        endpoint: 'http://localhost:3001/api',
        query: `{
  user(username: "mxstbr") {
    id
    username
  }
}`,
      },
    ],
  },
  introspection: process.env.NODE_ENV !== 'production',
```

introspection is disabled by default in production but i added condition for sanity.
![playground-disabled](https://user-images.githubusercontent.com/22687681/50159962-0e842200-02fe-11e9-845e-fea68ffcf525.png)
**Ref:** https://www.apollographql.com/docs/apollo-server/features/graphql-playground.html

**Comment by mxstbr** [comment]
Yes sounds great!
