### ISSUE TITLE
Websocket connection issue 

### ISSUE THREAD

**Issue by umardraz** [withspectrum/spectrum#4393]
Hello

I am running spectrum on my public server and whenever I open the url mydomain.com then after taking some time the site opened but I am getting this error in the browser

WebSocket connection to 'ws://localhost:3001/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Would you please help me how to fix this

**Comment by mxstbr** [comment]
Hey, you need to run the site with `NODE_ENV` set to `"production"`, Apollo client is trying to connect to the dev environment!

**Comment by mxstbr** [comment]
You'll have to deploy the API server (in the `api/` folder) and forward `mydomain.com/api` requests to that API server

**Comment by umardraz** [comment]
Hmm strange, after setting forward /api in nginx 

New errors appearing

OPTIONS http://localhost:3000/ net::ERR_CONNECTION_REFUSED
POST https://api.amplitude.com/ 400
OPTIONS http://localhost:3000/ net::ERR_CONNECTION_REFUSED

Is there any valid documentation available where everything is documented about how to run this app on a public domain either with apache or nginx?

**Comment by mxstbr** [comment]
Hmm, I'm not sure why it would ping localhost:3000 if `NODE_ENV` is set to `"production"` when building the frontend. You'll also need to forward OPTIONS requests to `/api` to the API server so that CORS works.

> Is there any valid documentation available where everything is documented about how to run this app on a public domain either with apache or nginx?

No, since we host everything on now.sh we don't have any experience with using Nginx or Apache unfortunately!

**Comment by umardraz** [comment]
This is not just issue of frontend end.

I had check this file build-api/main.js and there I saw this. 

**const FALLBACK_URL = IS_PROD ? 'https://spectrum.chat/home' : 'http://localhost:3000/home';**

The above clearly shows that everything is hardcoded. Now need to know how to change these.?

I tried to change the above constant but when I did **yarn run dev:api**

my changes are vanished .

**Comment by mxstbr** [comment]
Yeah you have to run `yarn run build:api` to re-build the API. `yarn run dev:api` only runs the development process!

**Comment by umardraz** [comment]
the yarn run build:api also vanished all of my settings from **build-api/main.js**

completely horrible

**Comment by brianlovin** [comment]
@umardraz I'd recommend not changing files directly in `build-api` as that gets overwritten every time the project builds. Any configuration changes should be made in the `api` directory directly, so that they can be built into `build-api` :)

**Comment by umardraz** [comment]
Ok finally I found api/index.js and changed there what I want. Now new thing

Request URL: https://api.amplitude.com/
Request Method: POST
Status Code: 400 
Remote Address: 52.89.50.99:443
Referrer Policy: no-referrer-when-downgrade

What is https://api.amplitude.com/?

**Comment by brianlovin** [comment]
Amplitude is what we use to aggregate user events for internal analytics dashboards. Feel free to remove that for your use case :)

**Comment by brianlovin** [comment]
@umardraz most of the code is in `shared/analytics` - you can just delete it. Although to close out the individual analytics events you'll want to do a project search for:
`trackQueue.add(` to find all instances where we track something in the backend
and
`track(events` to find all frontend tracking instances in the frontend.

In `src` you'll want to remove `src/helpers/analytics` and just do a directory search for `amplitude` to remove our instantiation code :)

**Comment by umardraz** [comment]
Ok Let me try and will tell you if need something more
