### ISSUE TITLE
Fallback UI For Server Crashes

### ISSUE THREAD

**Issue by iamclaytonray** [withspectrum/spectrum#4403]
It looks like the server is experiencing some problems at the moment, especially for trying to go to messages. However, the UI is not very user-friendly for displaying these errors. I'm suggesting we work on the UI to ensure that users can still use the web app regardless of errors. For the messages route, this would mean something like keeping the header at the top and maybe doing something like a vertical/horizontal centered user-friendly (actionable) error message. Doesn't have to extravagant. Thoughts?

This was when I tried to go to the messages route:

<img width="1440" alt="screen shot 2018-12-03 at 9 20 16 pm" src="https://user-images.githubusercontent.com/16495816/49414885-e4016900-f742-11e8-81d5-da4a991c9f1c.png">

**Comment by iamclaytonray** [comment]
This could also be a time to improve error handling from the server. 

This:

`Oops, something went wrong. Please try again! (Error ID: 6b61fe19fee34c4d9b5005a25881abe2)`

could become something like:

```
"error": {
  "message": "Something went wrong on our end. Please reach out to us at support@spectrum.chat",
   "errorId": "6b61fe19fee34c4d9b5005a25881abe2",
  "timestamp" // not json but don't feel like formatting: new Date(),
}
```

**Comment by mxstbr** [comment]
Yeah Raven captures the full error stuff, we should definitely make this error page nicer though, I agree!

**Comment by iamclaytonray** [comment]
If you give me a general idea of where to start, I can get a PR ready for review a little quicker. But I can figure out on my own if needed 😄

**Comment by mxstbr** [comment]
Yeah we'd love a PR!

Those errors are the last-ditch-effort errors in case _everything_ goes wrong server-side, and are created here:

https://github.com/withspectrum/spectrum/blob/244367ff9c8fd0c7a1f4f070c100f5f1ba407214/hyperion/renderer/index.js#L178-L186

I think a good first step would be to render a Spectrum-y purple gradient background with the text formatted a little bit nicer and a prompt to refresh or go home.

**Comment by iamclaytonray** [comment]
Ohh, you guys don't grab errors from a fetch response on the client? Yep, that wouldn't be too easy to implement, haha. Sounds good, I'll try to mock something up for review

**Comment by mxstbr** [comment]
Yep sounds great!

**Comment by iamclaytonray** [comment]
[Here's a basic example](https://codepen.io/iamclaytonray/pen/XyQqKG)

Feel free to make suggestions. (Ironically, design is not my strong suit)

**Comment by mxstbr** [comment]
Looking good! Probably want to use our font stack, putting a sad emoji at the top and excuse the issue ("Sorry about that :( Please refresh or go home" or something like that), then it's perfect!

**Comment by iamclaytonray** [comment]
Cool, I updated it. I'm not sure what emoji you're referring to so I added a few that I've seen commonly used. Let me know which one you want (or maybe react to this comment with the one you want and I'll add it)

**Comment by mxstbr** [comment]
Let's use 😢, that's the one we use for all our error pages!

**Comment by iamclaytonray** [comment]
Cool, will do
