### ISSUE TITLE
Throttling the community search seems to provide inconsistent intermediate results

### ISSUE THREAD

**Issue by raunofreiberg** [withspectrum/spectrum#4406]
https://github.com/withspectrum/spectrum/blob/f57c9f1674a737020feec1d6d9f45c081ed3e1a5/src/views/explore/components/search.js#L61

Searching for `react` provides me with the Reach community [for example](https://streamable.com/m75c8). This does not seem like a good experience, imho. I assume this is because of throttling since the search gets called per 500ms [(btw, the comment is also invalid since it says 200ms, but is actually 500ms)](https://github.com/withspectrum/spectrum/blob/f57c9f1674a737020feec1d6d9f45c081ed3e1a5/src/views/explore/components/search.js#L60). Maybe debounce the search instead of throttling?

**Comment by mxstbr** [comment]
Yeah this should definitely be debounced, not throttled—PR very welcome!
