### ISSUE TITLE
Creation of community left it without owner

### ISSUE THREAD

**Issue by flaki** [withspectrum/spectrum#4429]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

I tried to create a new `techspeakers` community, but Spectrum was a bit sluggish to respond, with disconnections and reconnections, so I clicked the "Create" button a few times.

At some point Spectrum displayed an error that _"A community with the `techspeakers` slug already exists."_ [Looking at the community](https://spectrum.chat/techspeakers) it looks a bit broken and I could not decide if something has gone wrong in there during creation (it asks me to "request to join"), or is that a legit community that has been there before.

**Comment by flaki** [comment]
Okay never mind the doubtful tone above, something is definitely broken, I have received the creation email:

![spectrum-create](https://user-images.githubusercontent.com/2089432/49660090-0dbdd700-fa46-11e8-8976-57e0940ae0e3.png)

**Comment by brianlovin** [comment]
That box is just an emoji that's not rendering on your machine for some reason :P 

To confirm: are you the owner of TechSpeakers and have ability to access settings?

**Comment by flaki** [comment]
I don't seem to be, as http://spectrum.chat/techspeakers informs me that "this is a private community, you can request to be added".

But I _should be_, I've received the email about the community being live on Spectrum (and now the registration form informs me that the `techspeakers` slug is taken, as it is obviously the case, as seen above.

As a thought experiment I tried requesting access but I didn't receive any email related to that (as schizophrenic it would be, receiving an email for adding myself :grin: )

_(PS: I'm on Linux, the missing emojis in the mail is not unexpected :) )_

**Comment by flaki** [comment]
Hi,

Can I please get an update on this?

I would really like to start using this community, but I'm still shown as I'm "pending for approval" to the community I registered (and of course it doesn't show up in the list of communities either).

**Comment by mxstbr** [comment]
Sorry, I am taking a look @flaki!

**Comment by mxstbr** [comment]
Very strange situation, you are marked as a `pending` member but ALSO as the creator of the community 🤔 I am not sure how you got into that position, I will try to fix it manually.

**Comment by mxstbr** [comment]
@flaki so it turns out _a lot_ of things went wrong during the creation of that community. :confused:

I have renamed it to `broken-techspeakers`, would you mind simply recreating the community with the proper slug (`techspeakers`)? That would be the easiest solution.

Super sorry for the troubles here! :pray:
