### ISSUE TITLE
Cannot login on mobile app (iOS)

### ISSUE THREAD

**Issue by Chiamaka** [withspectrum/spectrum#4448]
Hey guys, I started tinkering about with the spectrum mobile app yesterday and I've run into some problems.
When I try to sign in using any of the 'Social Sign in' (Twitter and Github) buttons, it redirects me to the social platform's page to enter my details but when it redirects back to the spectrum app, there is a warning (screenshot provied)
I did a little digging and in the code, `accessToken` is expected to be a property in the params object gotten from `${API_URL}/auth/${provider}?r=${redirectUrl}&authType=token` but it isn't available

This is the object returned
```
{
errorCode: undefined
params: { authed: "true" }
type: "success"
url: "exp://localhost:19000/--/expo-auth-session?authed=true"
}
```
<img width="382" alt="screenshot 2018-12-11 at 8 40 16 am" src="https://user-images.githubusercontent.com/2737103/49828679-64981900-fd84-11e8-978d-3f82b985cd0d.png">

**Comment by brianlovin** [comment]
Hey @Chiamaka we're currently pausing work on React Native mobile app - sorry for the trouble here!

**Comment by Chiamaka** [comment]
hey @brianlovin what apps are still in active development?

**Comment by brianlovin** [comment]
Desktop and web!
