### ISSUE TITLE
Signed out 'join community' upsell on thread views covers most of the content

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4531]
Ref: https://twitter.com/sergiodxa/status/1081745429681897472

Need to figure out how to approach this so that signed out users still have a quick way to sign-in and expose the chat input without having to scroll all the way to the bottom of chat first.

**Comment by arthurdenner** [comment]
If that's okay, I'd like to work on this issue.

**Comment by brianlovin** [comment]
@arthurdenner sure thing - want to share a couple mocks or ideas first and we can align on direction?

**Comment by arthurdenner** [comment]
Sure. I'm not on the computer right now, but I'll try to describe. I was thinking about the following behavior:

The upsell will have a "X" (close) or a large secondary "Hide" button. When this button is clicked, the action (join/sign up) becomes available through a floating button (with just an icon) on bottom right.

What do you think of this approach?

**Comment by brianlovin** [comment]
Seems like an "X" close button that simply hides all the text could do the trick, that sounds good!

**Comment by arthurdenner** [comment]
Nice. I'll start to work on it today or tomorrow.
