### ISSUE TITLE
Landing/Community page doesn't load.

### ISSUE THREAD

**Issue by Harshit369** [withspectrum/spectrum#4534]
**Issue Type**
- [ x ] Bug Report

**Description (type any text below)**

The Communities page doesn't load sometimes after I restart the app. looks like a common error to me but didn't find any open issue for this. I have tried a few hard refreshes at my end but to no use. I found out this in the developer console.

![image](https://user-images.githubusercontent.com/7912702/50954090-77b11c80-14db-11e9-993a-ad3ee6a25a1c.png)

But when a story is opened from the notification dropdown the side-pane works swiftly.

![image](https://user-images.githubusercontent.com/7912702/50954215-c19a0280-14db-11e9-890e-d32746ef3b93.png)

Also, the app keeps on reconnecting to internet quite frequently.

**Comment by Harshit369** [comment]
@brianlovin currently I don't know which community it should open by default. As the default home page doesn't load so there's no community list for me to see.

**Comment by brianlovin** [comment]
@Harshit369 to confirm if you log in at spectrum.chat, you don't see your inbox loading at all? Would love to investigate more - what's your Spectrum username? And do you see any errors in your console at all?

**Comment by Harshit369** [comment]
@brianlovin nothing loads except for the top navbar. I have added the screenshot of the console above for anybody to check.

**Comment by Harshit369** [comment]
☝🏼I actually don't know what the issue was or you guys have tighten up some screws but it works perfectly fine now.
Thanks.
