### ISSUE TITLE
Delete key while composing new direct message will remove recipient

### ISSUE THREAD

**Issue by tommoor** [withspectrum/spectrum#4553]
**Issue Type**

- [x] Bug Report

**Description**

Hitting the delete key while in a direct message to a new recipient will remove the recipient rather than delete characters in the message field.

To reproduce:

- Go to message a new person:
- https://spectrum.chat/messages/new
- Enter anyone in the field at the top
- Start writing a message and then hit the delete key twice.

**Comment by brianlovin** [comment]
Sorry about this @tommoor - mistakenly didn't pass along a couple blur and focus handlers. Pushing a fix now.
