### ISSUE TITLE
Login redirects may be broken

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4571]
Ref https://spectrum.chat/spectrum/hugs-n-bugs/no-redirect-after-sign-up-login~f80e60d1-ce77-4cd6-8d3f-bf420b93581e

**Comment by richardgill** [comment]
Reproduction process: Opened a Chrome incognito window and logged into github.com.

Went to https://spectrum.chat/function-camp (or any other spectrum.chat url with a path).

Doesn't redirect - got someone else to try - same outcome.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6640874/51730205-7c92d600-206e-11e9-9edc-c409bf0ad7e1.gif)

**Comment by richardgill** [comment]
This bug makes it very confusing for people who have never used spectrum who join a private community. Because they just get dumped on the homepage of the site rather than the community they were joining's page.

**Comment by brianlovin** [comment]
Interestingly I can't reproduce this locally, but can reproduce on the production app. Digging in more.

**Comment by brianlovin** [comment]
Found the fix, pushing shortly.

**Comment by brianlovin** [comment]
PR open, will try to land this soon - thanks so much for pushing on this @richardgill :)
