### ISSUE TITLE
Enter shouldn't submit messages while typing a codeblock

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4572]
Ref https://spectrum.chat/?t=bed7d94f-b2e9-4e44-b63e-7e494465effe

**Comment by mxstbr** [comment]
I feel like this would be really confusing behaviour. I would always expect Enter to submit a plaintext input, no matter what is in the plaintext input.

**Comment by brianlovin** [comment]
I know, it's confusing either way...I just made this issue quickly without thinking too much, so we could discuss. It just makes me think that if talking about code is such a common thing, maybe a single line input isn't the right design decision?

**Comment by ThomasRoest** [comment]
For writing longer comments, code blocks etc. A github style comment composer would be better I think. With some options, preview, does not submit on enter etc.

see also: https://spectrum.chat/spectrum/general/what-happend-to-commenting~76ba707c-c344-4110-9274-204391599410

**Comment by brianlovin** [comment]
Seems like the fix here would require a redesign of the chat input. Since this is out of scope, let's keep the current behavior and decide if we want to have a longer-form comment box instead of a chat input in the future.
