### ISSUE TITLE
Backslashes being inserted into inline code when messages are edited

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4584]
https://spectrum.chat/spectrum/hugs-n-bugs/underscores-in-comments-inside-inline-codeblocks-are-converted-to-upon-editing~6702fd99-0454-4686-a12e-b77ae55f263c

Repro:
- type inline code into the chat input, where the inline code contains an underscore
- edit the message
- see that a backslash has been inserted before the underscore
- save the message
- see that the saved message persisted the backslash

**Comment by 0188716218** [comment]
Sorry

**Comment by mxstbr** [comment]
Great catch! @_sstur is there a reason why `draft-js-export-markdown` adds backslashes in front of underscores in inline code?

**Comment by mxstbr** [comment]
Great catch! @sstur is there a reason why draft-js-export-markdown adds backslashes in front of underscores in inline code?

**Comment by sstur** [comment]
Take a peek at this for me if you would.
https://github.com/sstur/draft-js-utils/pull/160

**Comment by sstur** [comment]
Done. draft-js-export-markdown@1.3.0 is live.

**Comment by brianlovin** [comment]
Appears to work! Gonna ship today, thanks so much for the quick fix here @sstur!
