### ISSUE TITLE
Suggested mentions insert twice in sent message

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4587]
Mentions inserted by the new mentions suggestions render twice in messages. Need to fix that asap!

**Comment by brianlovin** [comment]
This is actually worse than that: it deletes any text you've typed after the mention. For example, I just typed `@username blah blah blah` and the output was `@usernameusername` without the followup text.

**Comment by brianlovin** [comment]
<img width="763" alt="screenshot 2019-01-27 18 34 39" src="https://user-images.githubusercontent.com/1923260/51811547-49b13380-2262-11e9-998c-f586272c125a.png">

The message crashes when trying to edit as well.

**Comment by brianlovin** [comment]
Ah, so the username url points is: `https://spectrum.chat/abraham-papoose)%20I%20think%20this%20thread%20might%20have%20ended%20up%20in%20the%20wrong%20community%20:` - so you can see how it just appended all of my text to the url. It seems like this might be a problem with the markdown link stuff?

**Comment by mxstbr** [comment]
No this is a problem with the `react-mentions` `markup` option :confused: Will dig into this now!
