### ISSUE TITLE
Multiple links in a message breaks the message

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4592]
Ref: https://spectrum.chat/spectrum/general/spectrum-v2-6-0-a-much-less-buggy-chat-input~84352ff4-9feb-4cce-ab05-575617ad5176?m=MTU0NzkxMDE4NDMwOA==

Can repro this easily by trying to send the following as a message:
`[link 1](https://google.com) and [link 2](https://google.com)` will output `link1`

**Comment by mxstbr** [comment]
This is an issue with `draft-js-import-markdown` I think, digging in.

**Comment by mxstbr** [comment]
Fixed in this PR: https://github.com/sstur/draft-js-utils/pull/161 Once that is merged and published we have to update `draft-js-import-markdown` and this will be resolved.

**Comment by brianlovin** [comment]
Looks like it shipped with v 1.3.0 - updating our package and pushing shortly
