### ISSUE TITLE
Do not submit message on enter if typing a mention

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4595]
I just hit Enter to add a mention, but mistyped the name so I sent a message that just contained `@halfanam`. We should block enter-to-submit if the text ends with `@xyz` maybe?

**Comment by brianlovin** [comment]
> We should block enter-to-submit if the text ends with @xyz maybe?

I think this is sort of expected behavior, no? The person can just edit the message to fix this, right?

**Comment by mxstbr** [comment]
Okay!
