### ISSUE TITLE
Extensibility through plugin system

### ISSUE THREAD

**Issue by nicolad** [withspectrum/spectrum#4609]
It would be really handy to extend spectrum to some specific community need.
I've seen this been done via plugin architecture in another full-stack js project => https://strapi.io/documentation/3.x.x/concepts/concepts.html#plugin
Is this something that can be added on roadmap ?

**Comment by mxstbr** [comment]
That does not really make sense for Spectrum as 99% of the communities using it are not hosting their own instance.  If anything, we will build integrations like Slack!
