### ISSUE TITLE
Invite users in bulk

### ISSUE THREAD

**Issue by mirko77** [withspectrum/spectrum#4611]
**Issue Type**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description**

Hi, 
I have a list of ~1000 members to invite from a community I currently have on Google+ (which is shutting down).

Is there any way to invite them in bulk, for example uploading a .csv file with the email addresses?

see https://spectrum.chat/spectrum/general/invite-users-in-bulk~17ae92bf-9a6e-42a2-b1b4-cfe19ebdd807

**Comment by shtefcs** [comment]
That would be great new feature for community owners, where they could bring more members easier and migrate from other platforms.

**Comment by mxstbr** [comment]
A quick way to do this would be to allow input of `.json` files from the frontend, which would auto-fill the existing inputs in the community settings. (`.json` instead of `.csv` because then we do not need to ship a parser)

If anybody wants to tackle this,

**Comment by mxstbr** [comment]
If anybody wants to tackle this, the relevant code is in [src/components/emailInvitationForm](https://github.com/withspectrum/spectrum/blob/alpha/src/components/emailInvitationForm/index.js). It renders this part of the community settings:

<img width="601" alt="screenshot 2019-02-06 at 19 44 50" src="https://user-images.githubusercontent.com/7525670/52365510-f308de00-2a47-11e9-9763-33930c74c683.png">

1. Add an `<input type="file" />` that only accepts `.json` files in the bottom left
2. Parse the input JSON and make sure it is in the format `['email@bla.com', 'email2@bla2.com']` or `[{ email: 'email@bla.com' }]`
3. Add the emails from the JSON file to `this.state.contacts`

That should be it! If anybody can build the functionality, we can make it look nice and that should be it 👍

**Comment by brianlovin** [comment]
We could put a csv => json parse on the api server though!

**Comment by mirko77** [comment]
I have always used [PapaParse](https://www.papaparse.com/) for csv => json

**Comment by mxstbr** [comment]
@brianlovin as a v2 for sure, but as a quick win it would be nice to keep the changes frontend-only and not upload massive files to our server! :+1:

**Comment by mxstbr** [comment]
Here is a first prototype: https://codesandbox.io/s/2x8jly1v4y

This should be a relatively simple change, will see if I can land this tomorrow.

**Comment by shtefcs** [comment]
Hey, wondering why it's closed? Did you make it work or smth else? @mxstbr

**Comment by mxstbr** [comment]
Yes we built this feature, it will go live today! I will ping y'all here when it is live 👍

**Comment by mirko77** [comment]
Is there a limit on the number of invitations we can send?

**Comment by shtefcs** [comment]
Awesome.

**Comment by mxstbr** [comment]
I do not think we have a limit at the moment—now that you ask me that though, we should probably add one... 🙈

**Comment by mxstbr** [comment]
This is live, you can now bulk-invite emails in your member settings!

![spectrum-import-emails](https://user-images.githubusercontent.com/7525670/52714373-fc3f0100-2f99-11e9-9d51-b4929128b2ee.gif)

**Comment by shtefcs** [comment]
Looks nice great Max.

Just wondering the same about the limit? Can we import 1k members ?

**Comment by mirko77** [comment]
I tried 2K and it went through.

I have not got any invitation email yet though

**Comment by shtefcs** [comment]
Let's see, maybe emails are in quee. Let us know how it went Mirko
vanila.io

**Comment by mxstbr** [comment]
We definitely see them in our analytics 😅 

![screenshot 2019-02-13 at 14 47 32](https://user-images.githubusercontent.com/7525670/52716128-678ad200-2f9e-11e9-92e5-460a6d12b9e2.png)

It does not look like any of them failed, as far as I can tell!

**Comment by mirko77** [comment]
Awesome!

**Comment by shtefcs** [comment]
> We definitely see them in our analytics 😅
> 
> Email invites per day:
> 
> ![screenshot 2019-02-13 at 14 47 32](https://user-images.githubusercontent.com/7525670/52716128-678ad200-2f9e-11e9-92e5-460a6d12b9e2.png)
> 
> It does not look like any of them failed so far, afaict!

Nice. Is that Sendgrid Analytics or something else ?

**Comment by mirko77** [comment]
We have a few new members already, looks like everything is working properly

Good job!

**Comment by mxstbr** [comment]
> Nice. Is that Sendgrid Analytics or something else ?

https://amplitude.com! We use GitHub's SendGrid account, so it's a bit hard to see just our emails in their analytics. 

> We have a few new members already, looks like everything is working properly

Awesome, more than happy to hear that!

**Comment by mirko77** [comment]
@mxstbr still I am not getting the invites I tried to send to my personal emails (to see how the invitation looks like)

nothing in my spam folder either.

Any thoughts?

**Comment by mxstbr** [comment]
That is very strange. Can you DM me your email address on Spectrum, and I will double check what happened with your email in our records?

**Comment by mirko77** [comment]
Done, and I found another bug on the way ;)
