### ISSUE TITLE
Clean up thread search on community profile

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4626]
The placeholder text also doesn't make much sense and we should follow the pattern from #4408.

<img width="669" alt="screenshot 2019-02-11 17 47 37" src="https://user-images.githubusercontent.com/1923260/52605818-2e7b2200-2e25-11e9-836a-7b8a12a95cd8.png">

**Comment by nainarazz** [comment]
Hello, has this issue been taken? I want to work on it if it is still not yet resolved.

**Comment by brianlovin** [comment]
@nainarazz this will be resolved in #4798 so yes, we can preemptively close this :)
