### ISSUE TITLE
Add log out button to mobile

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4634]
We have to add a log out button to mobile which is a link to `/auth/logout`.

This should probably be on the user profile view below the "Settings" button for compatibility with the web location in the profile dropdown.

**Comment by abdiG** [comment]
Hi @mxstbr, this is my first time contributing to open-source. i would like to contribute to this project.

**Comment by brianlovin** [comment]
@abdiG that'd be great, this is definitely a solid first issue to tackle! It'd be great to put this button in the settings view, and not on the profile view.

**Comment by mxstbr** [comment]
> It'd be great to put this button in the settings view, and not on the profile view.

That seems way too hidden. If I am on mobile, and I want to log out I do not think to go to my settings, right?

I would much rather put it on my profile below the "Settings" button, that is also a similar pattern to the web version.

**Comment by tuoxiansp** [comment]
> > It'd be great to put this button in the settings view, and not on the profile view.

> That seems way too hidden. If I am on mobile, and I want to log out I do not think to go to my settings, right?

I don't think so. this is general, I think. 

eg, the WeChat App: 

Me -> Settings -> Log Out

![image](https://user-images.githubusercontent.com/3960056/52908766-36204800-32b7-11e9-85cc-e27c12549a74.png)
