### ISSUE TITLE
Signin without social login

### ISSUE THREAD

**Issue by carlosjeurissen** [withspectrum/spectrum#4661]
Will it be possible to sign in without any Social account like Google, Facebook, or Twitter in the future?

**Comment by mxstbr** [comment]
This would be a fair amount of effort, which is why we have not prioritized it. Since we were acquired by GitHub, it is more likely we will spend our time making Spectrum work really well with GitHub rather than adding more authentication methods. I hope that makes sense! :pray:

**Comment by carlosjeurissen** [comment]
I respect that. Thanks for taking the time to explain this in detail @mxstbr!

**Comment by gurgunday** [comment]
This makes sense but what about casual people that don't have GitHub? I mean Spectrum is an amazing Reddit alternative and not every community is made for developers, maybe you could also add password-free login with mail or something for other type users?

**Comment by brianlovin** [comment]
We're focusing primarily on developer communities going forward, I hope there are other tools out there that can be great for non-developer communities :)
