### ISSUE TITLE
Add rate limiting to community email invites

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4665]
My feature was merged to graphql-rate-limit: https://github.com/teamplanes/graphql-rate-limit/issues/24

We need to add rate limits to the community email invites mutation. Probably something ridiculously big and long, just to avoid people sending 100,000,000 spam emails using our SendGrid account. Maybe `5000 / 1w`?

**Comment by brianlovin** [comment]
No clue on what an appropriate limit here would be, but yeah probably something like 5,000 or 10,000 per upload, and maybe once per week just so we can catch bad actors

**Comment by brianlovin** [comment]
It might also be worth triggering an email similar to our adminSlackNotification email so that we get notified about communities and users who invite in bulk.
