### ISSUE TITLE
Image uploads with parenthesis break on render

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4666]
If you upload a file with the filename `foo.jpg` everything works. If you upload `foo (7).jpg` it breaks the markdown parser and renders a broken image.

**Comment by brianlovin** [comment]
Per #4667 I think the issue is any filename with a space is breaking

**Comment by mxstbr** [comment]
Both file names with spaces and file names with parenthesis work for me locally in development. That means it is not a markdown parser issue, it is a S3 issue—although I am not sure how that could be the case.

Any ideas?

**Comment by brianlovin** [comment]
I see, okay perhaps it's the way we're encoding images in the `s3` file upload path in `api` - I'll try to poke around here, but this is going to be really hard to backfill. Ideally we'll just be able to fix future uploads with spaces

**Comment by brianlovin** [comment]
This was an issue with double signing filenames that had spaces. Resolved.
