### ISSUE TITLE
Image uploads are getting double-signed

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4667]
Thread: https://spectrum.chat/spectrum/general/spectrum-weekly-digest-has-discover-more-communities-three-times~92dce549-a8ce-4799-8768-a917840688d6

Url being returned to frontend: `https://spectrum.imgix.net/threads/draft/e2901881-59b8-40be-aa85-fba96cbc9c8d-Screen%252520Shot%2525202019-02-18%252520at%25252019.34.00%252520.png?expires=1550188800000&ixlib=js-1.2.0&s=80c038d824883a2c9a3b7bfc0c91c49b?expires=1550534400000&ixlib=js-1.2.0&s=5d15750dc25f8439d1bb62cf44f47c47`

**Comment by brianlovin** [comment]
While this double signing is bad, the actual underlying issue is that any uploads with a space in the filename aren't getting encoded correctly and break when rendered (but work when previewed). Super weird...

**Comment by brianlovin** [comment]
This might be a pain because we need to support old draftjs posts as well as new plaintext posts. Open to ideas on this @mxstbr, I'm really not sure how to handle this

**Comment by mxstbr** [comment]
I think the right solution would be to handle already signed URLs correctly in the `shared/imgix/sign.js` method. That way all images will keep working and we do not double-sign, right?

**Comment by brianlovin** [comment]
@mxstbr I think that's probably the right approach, we just need to renew the signature as noted in #4673

**Comment by brianlovin** [comment]
Our s3 flow is totally busted @mxstbr. We're basically now dumping every upload in s3 into `/threads/draft/{filename}` and persisting a signed version of that url to the db `thread` object.

I guess I don't care that much about the path where it's getting stored in s3, but the signing flow is a problem.

Here's roughly what we need, I think:

1. User uploads image, we return a *signed* url to the client so that it can be previewed
2. User publishes thread, we parse the incoming text and look for image urls and strip out any query parameters
3. Frontend requests thread, we parse the `thread.content.body` and look for image urls. If there is an existing signature, we replace the url with a new signature query param (to backfill old ones). If there is not an existing signature, we sign the url.
4. If the user edits the thread, we parse the incoming `thread.content.body` and look for image urls. If there are image urls, we ensure that the url saved to the database is stripped of all query parameters.

I think that sounds right, can you double check my logic here? If that sounds right, I can tackle this tomorrow. Spent some time this afternoon looking into this and our code is a bit all over the place...
