### ISSUE TITLE
Render nice embeds for thread links in messages

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4669]
When a message contains a link to a thread on Spectrum of any kind we should render a nice preview of that thread and, on click, open the thread slider.

**Comment by brianlovin** [comment]
If we're going to do this, it might be worth expanding the regex to include community urls, channel urls, and user urls. It'd be cool to have the attachments loosely render the same thing in message or threads, so that if you linked to a community in a thread we can generate a rich preview (with a join button, or something!)

**Comment by brianlovin** [comment]
Oh, one idea for this @mxstbr would be to build out views that we could just iframe in. Something like embed.spectrum.chat/thread/:id or something...the positive side effect of this would be that we could help people build iframes for their communities/threads/channels/user profiles that could be embedded anywhere else on the web!

And it would play nicely with how `add-embeds-to-draft-js.js` file works.

**Comment by mxstbr** [comment]
I think iframing a thread would look very different from the way we are envisioning this rendering, right?

I do agree that embed.spectrum.chat would be nice to have in the future, but I think it's a bit out of scope of this one.

----

Good points about embedding other stuff too, let's start with threads and then expand to all types of Spectrum content down the line!

**Comment by brianlovin** [comment]
> I think iframing a thread would look very different from the way we are envisioning this rendering, right?

yeah, probably - not fully fleshed out thought here. Let's start with rendering dynamic react components and go from there.
