### ISSUE TITLE
Add back image focus state on images while editing a thread

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4675]
https://github.com/withspectrum/spectrum/pull/4619

We removed the focused state because the new plaintext editor preview looked weird with a focus state that didn't do anything...but we actually need that focus state while editing a thread, because the thread editor uses draftjs wysiwyg

**Comment by mxstbr** [comment]
As soon as we merge #4629, which moves thread editing to plaintext, this will be fixed-seems like we should rather get that shippable than implement this?

**Comment by brianlovin** [comment]
Fair enough. @mxstbr I'll leave that up to you, since #4629 has tons of failing e2e tests 💜
