### ISSUE TITLE
Support code syntax highlighting in message code blocks

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4677]
We support this in thread code blocks, is it possible to get consistent behavior in message code blocks now that we're plain-text across the board?

**Comment by mxstbr** [comment]
Yeah I implemented this for the thread renderer in #4629 so really now its just a matter of copy-and-pasting that implementation to the message renderer!

**Comment by brianlovin** [comment]
💜

**Comment by lookapanda** [comment]
I just tried looking into this and I don't think it's that easy. The API is returning the messages already as parsed code blocks and they lack the language data attribute. So the renderer cannot know which language was used for a code block and thus is unable to add syntax highlighting.

Meaning, this would not just be copy & paste, it would also require some additional (yet small) API changes.

I already tried some changes locally and it seems to work, too. Yet I only changed the addition of messages so far, not the editing but that should really be just copy & paste then. 

But before I might attempt a PR, the question remains what's about the already posted messages that contain code blocks?

**Comment by lookapanda** [comment]
That being said, of course it would not be that much of an issue. Just unstyled code blocks and if users want, they can edit it and add the language.

**Comment by mxstbr** [comment]
@lookapanda they should not lack the language attribute if you do this: ```markdown, the `code-block` blocks should have `block.data.language` or something like that?

Already posted messages that do not have the language after the triple backticks just won't show syntax highlighting, that's fine!

**Comment by lookapanda** [comment]
Done!

**Comment by lookapanda** [comment]
I tried to reuse some code, but I'm sure it some things could be refactored in a better way, but I'm not 100% familiar with your code structure and didn't want to interfere with it too much.
