### ISSUE TITLE
Send higher quality cover photos to large screens

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4685]
This should be doable with imgix I think: https://spectrum.chat/spectrum/general/header-image-low-quality~b51bd603-c78d-4a40-a8c9-ba108443ccc4

**Comment by brianlovin** [comment]
Definitely possible since we sign cover photos with their own options entirely. Will take a look!

**Comment by mxstbr** [comment]
My first idea would be to return a more complex object from the API:

```JS
thread: {
  coverPhoto: {
    small: url1,
    medium: url2,
    large: url3
  }
}
```

and then use CSS media queries on the frontend to switch out the images based on screen size?
