### ISSUE TITLE
Thread rendering unclickable links (without href)

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4701]
It's possible this thread was corrupted at some point, but the bug here is this:
- renders the list items with the appearance of links, including wrapping the dom nodes in anchor elements
- in the database `content.body` the nodes have a key type of `unordered-list-item`

https://spectrum.chat/brian/general/product-design-portfolios-updated~bf114297-6ff3-4ec4-be3e-34b3e7498c31

So I'm confused how the `unordered-list-item` keys are getting rendered as links, and I don't know where the `href`s went - if they are unrecoverable I can edit the thread later to fix it, but I'll leave things as-is while we investigate.

**Comment by mxstbr** [comment]
The links would be stored in the `entityMap`, and those entities would be referred to by the `inlineEntityRanges` of each `unordered-list-item` block! Will look at that body in detail tomorrow.

**Comment by mxstbr** [comment]
Fixed in #4629
