### ISSUE TITLE
Community cover image upload is broken

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4711]
Fails with an error, see https://spectrum.chat/spectrum/general/cant-upload-a-community-cover-image~704b94df-be65-4848-8c9b-ae2bd9c94715 for user bug report and  https://sentry.io/share/issue/96cdbfec840644c8aa44abe4526752c3/ for corresponding stack trace.

```
Invalid JSON in the ‘operations’ multipart field (https://github.com/jaydenseric/graphql-multipart-request-spec).
```

**Comment by tuoxiansp** [comment]
#4664
