### ISSUE TITLE
DM thread subscriptions not updating properly

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4764]
@mxstbr check this video: https://www.dropbox.com/s/9tm6xve92krfj71/dm-not-updating.mov?dl=0

I was investigating why the `messages_spec.js` seems to fail so much in CI. Well, it turns out it actually is failing - some of the time https://circleci.com/gh/withspectrum/spectrum/22310?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

In that video you can see that sometimes when I send a DM it updates the order of the thread list, and sometimes it doesn't. I spent 2 hours on this tonight investigating and I'm totally stuck...I feel like I haven't made any progress today. Could I get your eye on this?

**Comment by mxstbr** [comment]
I can replicate. This seems to be a bug with subscriptions, if you look at this websocket log you can clearly see how the server pings the client with `directMessageThreadUpdated` after each message except for the last one:

![screenshot 2019-03-01 at 09 09 19](https://user-images.githubusercontent.com/7525670/53624886-f552f800-3c01-11e9-8a16-4cd12eee22e6.png)

That of course means the DM thread list does not update. Once you refresh it is totally fine though, so the data is being written correctly.

I am going to dig into why this happens with some logging, but I am not sure there is a quick fix here.

**Comment by mxstbr** [comment]
The plot thickens. I wrote messages in the same thread twice, the first time the list did not update, the second time it did. These were the logs:

![screenshot 2019-03-01 at 09 14 53](https://user-images.githubusercontent.com/7525670/53625114-86c26a00-3c02-11e9-9871-84d73a5cb34d.png)

Note how the first time, it only got passed the usersDMThreads record of _one_ user (that is not me), but the second time it got passed the records of _both_ users.

Digging in to try and figure out how that can happen!
