### ISSUE TITLE
Cannot start hyperion locally any more

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4769]
@mxstbr was doing some testing tonight and got this for the first time when running hyperion:

<img width="720" alt="screenshot 2019-02-28 20 53 15" src="https://user-images.githubusercontent.com/1923260/53611019-087ead00-3b9b-11e9-976d-9574a7331f76.png">

I've never seen this before, but a cursory glance says it's something about React Router in SSR. Perhaps it's good I found this before we tried a prod cut? Let me know if you can repro

**Comment by mxstbr** [comment]
This was broken in #4742 because I imported `history` somewhere. Digging in to figure out why and how I can resolve it!

**Comment by mxstbr** [comment]
Yeah it's this change: https://github.com/withspectrum/spectrum/pull/4742/files#diff-28da8dc4041249a1ed601fa58f4c8c5d

Not sure right now why I did that, digging in.
