### ISSUE TITLE
Provide GitHub url attachments in messages

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4801]
We should use https://github.com/jonschlinkert/parse-github-url to intelligently unfurl GitHub urls into attachments that render inline in messages.

**Comment by mxstbr** [comment]
This would be done similarly to what we are doing for thread URLs in `message/view.js`: 

https://github.com/withspectrum/spectrum/blob/d51957bd084b079f19ca5c79c608a4accfaddc5a/src/components/message/view.js#L62-L87

Would need to fetch additional information from the GitHub public API somehow, and then render a nice card like we do for the Spectrum threads.

**Comment by brianlovin** [comment]
Yup. In reality we should just build on top of the existing urls regex we have for adding embeds to threads. Eg. you link to a youtube video in chat and we unfurl the video.

**Comment by mxstbr** [comment]
As of #4827 the thread embeds are moved to the automatic embed system, so this feature should actually be implemented in `shared/draft-utils/add-embeds-to-draft-js.js`!

**Comment by segmentationfaulter** [comment]
@brianlovin Do we have mocks or an example of how the github attachments/embeds should look like? I want to work on this feature. Thanks

**Comment by citisolo** [comment]
I've been working on this and I've come up with the following ;

![Imgur](https://i.imgur.com/KSJcXgn.png)

I wanted to ask if the look of the attachment what you guys had in mind ? and also I've had issues rendering multiple inline attachments where the first attachment is duplicated after refreshing the page, and it seems like the last attachment overwrites the previous one/s.

![Imgur](https://i.imgur.com/6EqzQ6v.png)

This seems to happening down in 'redraft' where the` ContentNode `seems to be getting duplicated but I have no idea why. Any thoughts on this ?

![Screenshot from 2019-05-21 18-43-43.png](https://spectrum.imgix.net/threads/draft/db16f7de-f934-4d78-b3d6-699a55adf043-Screenshot%2520from%25202019-05-21%252018-43-43.png?expires=1558137600000&ixlib=js-1.3.0&s=011b093014a4b84eeb67dbe21956b9dc)

**Comment by brianlovin** [comment]
@segmentationfaulter I don't have mocks, but I think if you re-used the current thread attachments, we could remove the avatar, then swap out the title and subtitle content. Maybe if we started with just issue + pull request links, we could do:

**Issue**
title: `Issue title · #${issue number} (${issue open/closed status})`
subtitle: `${issue org}/${issue repo} · ${issue author full name}`

**PR**
title: `PR title · #${PR number} (${pr open/merged/closed status})`
subtitle: `${pr org}/${pr repo} · ${pr opener full name}`

Here's how they current thread attachments look:
<img width="885" alt="Screenshot 2019-05-23 14 45 27" src="https://user-images.githubusercontent.com/1923260/58278188-72a58900-7d69-11e9-8037-ec438577a8d5.png">

So we'd remove the user avatar, and instead of having the like/comment counts, we'd just have subtext for the above.

Does this seem okay to you?

**Comment by mahaveer0496** [comment]
Hmm if not done yet, can i take it ? @brianlovin

**Comment by mahaveer0496** [comment]
hehe sorry if its a weird question but does :+1:  mean i can go ahead and do it? :sweat_smile:  @brianlovin

**Comment by brianlovin** [comment]
Of course, open to ideas here too!

**Comment by johnletey** [comment]
@mahaveer0496 Correct me if I'm wrong, but it doesn't appear that there is much progress on this ... can I take over?

**Comment by mahaveer0496** [comment]
@johnletey I'm actually trying, just having a hard time making sense of code 😓 
If I don't finish by this week, can I ping you?

**Comment by johnletey** [comment]
> @johnletey I'm actually trying, just having a hard time making sense of code 😓

Let me know if you need any help!

> If I don't finish by this week, can I ping you?

@mahaveer0496 Of course you can!

**Comment by mahaveer0496** [comment]
@johnletey sorry man i couldn't finish, i need more training before contributing to open source..... please go ahead and take it.

**Comment by johnletey** [comment]
@mahaveer0496 Sounds good ... I will start working on this now!

**Comment by dhruvdutt** [comment]
@johnletey Any update?
Can I pick this up? ✋

**Comment by el1f** [comment]
Is this still up for grabs?

**Comment by ashiskumar-1999** [comment]
Hey @brianlovin, Is this feature still in progress?

**Comment by brianlovin** [comment]
It is not, we don't plan to accept any more community contributions as we move towards our read-only sunset next week.
