### ISSUE TITLE
Add thread link embeds to thread bodies

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4802]
We have added embeds for thread links in messages in #4669. We should add the same capability to threads themselves, if a thread is linked from another thread it should show a nice embed!

**Comment by brianlovin** [comment]
I'm not totally sure I understand this one, could you clarify?

**Comment by mxstbr** [comment]
If a thread is linked from another thread it should also show a nice preview like we do when it's linked in messages.

**Comment by brianlovin** [comment]
Oooh, in the thread body. Yup, good call!
