### ISSUE TITLE
Post new threads to watercoolers v2

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4815]
We experimented with posting new threads to watercoolers with a new "Spectrumbot" bot account in #4684. 

**Results of the MVP**

After deploying the MVP to production, many busy communities ended up with a watercooler that was nothing but "XYZ posted a new thread" bot messages for pages upon pages, making the watercooler chat useless. People asked how they could turn it off! 😕 

We also got the feedback that getting millions of emails for messages by a bot sucks (especially if one already gets new threads as emails), and that they weren't even sure whether it was a real account or a spammer at first.

Given the work we are doing in #4798 and #4721, hanging out in the watercooler will (hopefully) be a lot more common soon, and the threads lists will be a secondary concern. So, we do want to highlight new threads being posted in the watercooler to make sure folks see them.

**Going forward**

The important question for the next iteration is: how do we make it so that the watercoolers do not end up being useless due to overwhelming bot messages? A couple ideas:

1. Post the automatic messages as the author of the threads ("XYZ posted a new thread"), but still make it clear they were automatically posted with a `bot` label. For example on Slack when an app posts as a person it has an `App` label in the UI, we could do a similar thing:
  ![screenshot 2019-03-05 at 09 28 30](https://user-images.githubusercontent.com/7525670/53791182-16c92200-3f29-11e9-995d-03e53221b899.png)
2. Group many threads together in a single message, something like "Peter, Lukas, Stephan, and Alex posted new threads:" and then limit the amount of embeds per message (group until a human posts a message, and then start a new message?) (we should probably limit the amount of embeds per message generally)
3. Give these automatic messages a different, less important treatment to make them less overwhelming, potentially something like the "XYZ joined" automatic messages in Slack, which are greyed out:
  ![screenshot 2019-03-05 at 09 33 38](https://user-images.githubusercontent.com/7525670/53791464-c605f900-3f29-11e9-9668-b74f12e79e57.png)

Other ideas?

---- 

Out of these three, option 1 is my favorite. Contrary to posts by "Spectrumbot" it does not make it seem like the watercooler is devoid of humans, it makes it seem like it's full of humans and activity. It also allows us to continue experimenting with embed treatments, potentially putting an input inline or other "Reply" affordances—which would not be possible if we remove the embeds with option two or three.
 
Thoughts?

**Comment by ThomasRoest** [comment]
it depends on how much threads are posted and what information / embed is added. Like you said, it can become overwhelming quite fast. 
I wouldn't mind seeing a daily summary posted by the bot to start with, this might be easier to manage.  Just a few links with authors / thread titles

**Comment by brianlovin** [comment]
Thanks for the thought out note @mxstbr - I agree that 1 is my favorite option, and probably with some combination of not getting email notifications (maybe in-app badges are fine, though). 

> potentially putting an input inline or other "Reply" affordances

Would definitely like to try this!
