### ISSUE TITLE
Clicking on two notifications breaks the app

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/spectrum#4841]
First reported in #4825, happens in production today.

![](https://user-images.githubusercontent.com/1923260/53959456-ae597c80-40b1-11e9-9a86-25fa4ab71813.png)

![](https://user-images.githubusercontent.com/1923260/53959457-ae597c80-40b1-11e9-92e7-19b320e2b042.png)

Repro:

- have two recent notifications about someone replying in a thread
- open the first notification - opens the slider correctly
- close
- open the second notification - crashes

**Comment by michaelgichia** [comment]
The Spectrum is a great platform for our communities. The opportunity to improve the platform will be an honor to me. @mxstbr can I take this one?

**Comment by fmihal** [comment]
I think I can grab this one for investigation and fix. Thanks in advance.

**Comment by brianlovin** [comment]
@fmihal this one is safe to ignore for now, thanks for jumping in though!

**Comment by fmihal** [comment]
@brianlovin  Thanks for the reply. If you think that there is something worth picking up, I would like to help. Please link the issue below.
