### ISSUE TITLE
Allow moderators to edit any threads/comments

### ISSUE THREAD

**Issue by schickling** [withspectrum/spectrum#4856]
It's an essential moderation tool to be able to edit any kind of thread/comment (including thread title) to clarify formatting, phrasing (etc). This is especially important since threads are indexed for SEO and therefore not just read once but by many more people in the future.

This is already possible on most other (comparable) platforms like Discourse, GitHub issues...

**Comment by mxstbr** [comment]
The hardest bit is exposing who edited a thread/message in the UI, we do not want to make it seem like a user edited a thread if it was really a mod.

/cc @brianlovin any ideas for the UI around that?

**Comment by brianlovin** [comment]
Maybe just a tooltip with `edited by Foo`? We do store each edited state, so we could also show a modal with previous edits, if that's useful (and adds to transparency)
