### ISSUE TITLE
codeblocks in thread replies cannot be scrolled horizontally on mobile

### ISSUE THREAD

**Issue by ThomasRoest** [withspectrum/spectrum#4857]
- [x] Bug Report

see one of the answers in this tread
https://spectrum.chat/styled-components/general/using-classes-in-styled-components-bad-practice~e4bfaa44-62c0-42bf-8d3f-d47f775b832b

<img width="391" alt="spectrumbug2" src="https://user-images.githubusercontent.com/4428811/54115564-f992c880-43ec-11e9-8694-de131f4b8e92.png">

**Comment by styfle** [comment]
And it’s not just the code block that prevents scrolling horizontally, it’s the entire page. 

This makes spectrum unusable on mobile because nearly all threads have a code block 😢

**Comment by brianlovin** [comment]
Thanks for the heads up, this is definitely not ideal. Open to PRs that can help with this, as well!
