### ISSUE TITLE
Can't see any channels or conversations in `Prisma` chat

### ISSUE THREAD

**Issue by nikolasburk** [withspectrum/spectrum#4868]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** 

I have tried logging in with Twitter and GitHub but it's always empty:

![image](https://user-images.githubusercontent.com/4058327/54341882-54216400-463b-11e9-89e9-6ada37d69f45.png)

When I try to open a direct link (e.g. [this](https://spectrum.chat/prisma/general/prisma-admin-beta-a-modern-ui-to-manage-your-data~7ecf9013-bb40-4013-8ba4-91c8c1594880) one), I only see this:

![image](https://user-images.githubusercontent.com/4058327/54341917-6e5b4200-463b-11e9-9124-4f9d0676223c.png)

**Comment by mxstbr** [comment]
I can see everything. You were probably blocked by one of the admins of the community?! /cc @schickling

**Comment by brianlovin** [comment]
He access to settings, probably not blocked. This seems worth investigating. I’ll take a look

**Comment by brianlovin** [comment]
@nikolasburk can you confirm:
- does the feed load for your on mobile?
- in incognito?

**Comment by nikolasburk** [comment]
It works in incognito and on mobile as long as I'm not logged in. Once I log in, I don't see anything any more.

**Comment by nikolasburk** [comment]
In my Desktop version, I can also see the conversations but never can access their content:

![image](https://user-images.githubusercontent.com/4058327/54613454-0356a480-4a5b-11e9-9f08-c95c68d75725.png)

Frontpage is still empty:

![image](https://user-images.githubusercontent.com/4058327/54613469-0baedf80-4a5b-11e9-9301-df71b5c78eb2.png)

I think @schickling said that he initially blocked me by accident but then unblocked me again. Is there a way to completely "reset" my account?

**Comment by brianlovin** [comment]
@nikolasburk this should be fixed - really sorry for the slow fix time here. Can you confirm you can see all threads now?

**Comment by nikolasburk** [comment]
Yeah it works now, thanks a lot folks! 🙏
