### ISSUE TITLE
Make sure user hover profiles don't break the viewport boundary

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4899]

**Comment by segmentationfaulter** [comment]
I am claiming this issue and working on it.

**Comment by TruptiM18** [comment]
@brianlovin,
Can I work on this issue?

**Comment by brianlovin** [comment]
Please do!

**Comment by TruptiM18** [comment]
Thanks @brianlovin. I will start working on it.

**Comment by henrykempo** [comment]
Im looking at good first issue -labeled. And this is top of the list ;). Been around for a while, simple things often aint so simple! Happy to help/pair/please add learnings from issue so we can break it down. h

**Comment by dhruvdutt** [comment]
@TruptiM18 Any update?
Can I pick this up? ✋

**Comment by dhananjaysinghsengar** [comment]
@brianlovin brianlovin I would like to pick this issue. Does it still exist?

**Comment by brianlovin** [comment]
It does, but this issue is safe to ignore.

**Comment by Jans999** [comment]
Is this still open?

**Comment by brianlovin** [comment]
Yes, but it's safe to ignore.
