### ISSUE TITLE
DM thread does not scroll back to bottom if you leave and then return

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4920]
@mxstbr this is generally just a problem with how we approached scroll behavior in the entire app: if a thing loads for the first time, we handle the scroll properly. But then if the user leaves and comes back, the effect or method doesn't fire because it doesn't think anything is new (reads from cache) and so the scroll handler never fires...this applies to chat tab, thread messages, dm messages

**Comment by mxstbr** [comment]
I actually fixed this for thread messages, have to fix it for DMs too!  This is an issue with `getSnapshotBeforeUpdate` not firing on mount (which is intended behaviour but just unexpected).
