### ISSUE TITLE
codeblocks break mobile thread layout

### ISSUE THREAD

**Issue by ThomasRoest** [withspectrum/spectrum#4930]
- [x] Bug Report

Codeblocks seem to break the mobile layout. 

example thread: https://spectrum.chat/js/general/object-or-just-single-property-as-argument-to-function~c2822c7b-a5e5-49e4-8786-d3fdc20fd047

<img width="398" alt="Image 2019-03-22 at 9 55 02 AM" src="https://user-images.githubusercontent.com/4428811/54811504-1e0e6080-4c89-11e9-8ad7-7cb20818a7f3.png">

**Comment by brianlovin** [comment]
should be fixed in https://github.com/withspectrum/spectrum/pull/4922 - can you confirm you're seeing this fixed?

**Comment by ThomasRoest** [comment]
yes looks ok now!
