### ISSUE TITLE
Visual Bug in /settings

### ISSUE THREAD

**Issue by mihaitaba** [withspectrum/spectrum#4982]
Hey guys, very nice app you've made, kudos for that!

I'm having a visual bug on my machine:

![image](https://user-images.githubusercontent.com/45386599/55151978-16066300-5158-11e9-9e79-bd7716e46493.png)

Maybe you weren't aware of this. If you need any other details, I'll be more than happy to tell you. 

Cheers!

**Comment by brianlovin** [comment]
@mihaitaba - it appears those inputs are matching the width of the longest channel name available in the dropdown. Do you have some long channel names in your Slack team? Either way, I'll set a max width there

**Comment by mihaitaba** [comment]
@brianlovin Hey Brian! 

Oh, yes, in fact, we do. It's a group containing like 6 names, didn't even see that. 

Cheers!
