### ISSUE TITLE
User autocomplete should appear dynamically relative to the viewport

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#4997]
If you @ mention someone in the mini composer, the autocomplete list appears upwards and gets clipped by the top of the page. This should dynamically appear downwards, while the chat input autocomplete list appears upwards.

**Comment by jzabala** [comment]
I'll like to take this one 🙂

**Comment by brianlovin** [comment]
@jzabala thanks for the comment here! We won't be able to prioritize shipping this, unfortunately.
