### ISSUE TITLE
Can't type an asterisk at the end of a word in editor

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#5001]
Imagine you made a typo like:
`sounds goood`

And you wanted to quickly just send a second message without editing the original message:
`good*`

Our editor swallows the trailing asterisk

**Comment by jzabala** [comment]
Is this still a problem?

![Jul-22-2020 20-56-08](https://user-images.githubusercontent.com/1315054/88243047-256ac300-cc5d-11ea-83f1-d7b52d3fc310.gif)

What I see is that the `*` disappears until the request is done.

**Comment by brianlovin** [comment]
That's a bit strange, but it's good that it eventually shows up. I assume this is something to do with markdown parsing trying to see if that asterisk is trying to italicize something.
