### ISSUE TITLE
Can't unpin a post in a private channel

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/spectrum#5061]
https://spectrum.chat/spectrum/support/how-do-you-unpin-a-thread~923ec78f-e116-4834-82b8-e6ea3823b285

I can't remember if you should even be allowed to pin a thread in a private channel in the first place or not...

**Comment by tanmoyopenroot** [comment]
![Screenshot from 2019-05-22 11-41-03](https://user-images.githubusercontent.com/25791025/58151262-be333680-7c86-11e9-941d-d37d2bc32d9c.png)

Only threads in public channels can be pinned.

**Comment by brianlovin** [comment]
We can close this: the problem was that the post was pinned, and then moved into a private channel. We fixed this by automatically un-pinning threads if they are moved into a private channel.
