### ISSUE TITLE
500 on spectrum.chat

### ISSUE THREAD

**Issue by chmaltsp** [withspectrum/spectrum#5092]
**Issue Type (check one)**

- [X] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** -->
Spectrum.chat looks down right now. I'm sure you guys know by now.

<img width="1569" alt="Screen Shot 2019-05-08 at 8 13 06 PM" src="https://user-images.githubusercontent.com/10981965/57416325-d5295180-71cd-11e9-9535-34524b00179b.png">

**Comment by brianlovin** [comment]
We're currently experiencing an upstream provider outage. We'll be sharing updates at https://twitter.com/withspectrum going forward.
