### ISSUE TITLE
Chat popup doesn't have scrollbar instead uses main screen's scrollbar.

### ISSUE THREAD

**Issue by prvnbist** [withspectrum/spectrum#5108]
#### Issue 
The chat popup with a scrollable content doesn't have it's own scrollbar instead uses the main screen's scrollbar which is inaccessible when using mouse click to drag.

[Screenshot for reference]
![2019-05-15_170937](https://user-images.githubusercontent.com/17105682/57772984-90a13700-7734-11e9-9227-b6fbff4437f4.png)

#### Recommended solution
Introduce a scrollbar for popup itself if it has a scrollable content and disable the main screen's scrollbar.

**Comment by brianlovin** [comment]
Agreed on the solution, thanks for flagging this @prvnbist

**Comment by prvnbist** [comment]
Happy to help!
