### ISSUE TITLE
Feat req: Respect newlines in code snippets

### ISSUE THREAD

**Issue by corysimmons** [withspectrum/spectrum#5165]
**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

Currently Spectrum destroys empty newlines in code snippets. This is bad because empty newlines are really helpful for readability.

**Comment by johnletey** [comment]
@brianlovin @mxstbr @corysimmons Would be more than happy to work on this! Would love to be pointed in the right direction ... say ... a file?

**Comment by corysimmons** [comment]
Grepped project for `\n` (for newlines regex) and found nothing 🤷‍♂️. Grepped for `code` suspecting the filename would have something to do with "code" and stumbled upon https://github.com/withspectrum/draft-js-code-editor-plugin and https://github.com/withspectrum/draft-js-prism-plugin

The problem is probably within one of those plugins.

**Comment by johnletey** [comment]
Thanks, @corysimmons ... I will take a look!
