### ISSUE TITLE
Highlight like icon in list of posts

### ISSUE THREAD

**Issue by fanny** [withspectrum/spectrum#5196]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [ ] Bug Report
- [X] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** 

Current, when a user like a post, the like icon only have a highlight when the thread is open, as you see in the images below:

1. I liked the post, but it's not clear that i made this.
![Captura de tela_2019-07-16_21-26-02](https://user-images.githubusercontent.com/14113480/61338550-84a72380-a810-11e9-8f01-0af573ffc385.png)

2. When i open the post, i can see that i liked
![Captura de tela_2019-07-16_21-26-22](https://user-images.githubusercontent.com/14113480/61338557-8bce3180-a810-11e9-8448-d9a67c99a58c.png)

I thought in implement this highlight feature, in posts list, in the case of user liked.

**The solution:**

Analysing the code, i see that the component responsible for this is [InboxThread](https://github.com/withspectrum/spectrum/blob/alpha/src/components/inboxThread/activity.js)

And it's contains the information necessary to know if a current session user likes the post, i'm based on [this](https://github.com/withspectrum/spectrum/blob/931d85aed61a1b645f32ebfe847f886524c87c77/src/components/threadLikes/index.js#L53)

Since it has `thread`, it can do. What the community think?

**Comment by fanny** [comment]
cc @brianlovin

**Comment by thobhanifreddy** [comment]
![Screenshot 2019-08-20 at 12 05 09 PM](https://user-images.githubusercontent.com/12369649/63323695-0c1e1000-c344-11e9-9250-8606d9c63bb4.png)


Can do something like this?

**Comment by brianlovin** [comment]
@thobhanifreddy that would be a fantastic PR to open if you're up for it!

**Comment by thobhanifreddy** [comment]
@brianlovin I have opened a PR, but 1 test is failing. Not sure why is it failing. My commit should bot effect it. 
Can you please have a look. Thanks.
