### ISSUE TITLE
Unable to signup/login at all, 500 errors

### ISSUE THREAD

**Issue by johncomposed** [withspectrum/spectrum#5204]
**Issue Type (check one)**

- [X] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**
I appear to be unable to signup/login at all.

When I tried to login with google I got stuck with every page redirecting to `https://spectrum.chat/new/user` which just displays a sad emoji, "Oops something went wrong" ,and "Please refresh or go home".  Network inspector shows it as a 500 error. I was able to click "go home" and wasn't logged in.  

With github signup it loaded up `/home?authed=true` (500 error) and then always redirected to `/`,  with a 500 error.  I then couldn't access any part of the site until I cleared local site data.

Tried on latest chrome for windows and an older chrome on osx, with adblock+extensions and without. I am able to oauth into other sites with the accounts I tried. 

Hope this is helpful. 

- John

**Comment by cherewaty** [comment]
I can confirm the same problem today on Safari Mac. Clicking "go home" goes to to the domain root but with the same UI.

<img width="634" alt="Screen Shot 2019-07-26 at 2 59 11 PM" src="https://user-images.githubusercontent.com/230597/61978185-30d9ce80-afb6-11e9-8d9e-4e88962d9ca0.png">

**Comment by fabgilson** [comment]
Same problem on Linux (Firefox and Chromium) and Windows (Firefox, Chrome and Edge).

**Comment by nicobgts** [comment]
Same issue on Chrome + Firefox. 
I tried to revoke access to spectrum on Github and tried to sign up again but same issue...

**Comment by brianlovin** [comment]
This was fixed yesterday, sorry for the trouble everyone.
