### ISSUE TITLE
Text input covers publish button

### ISSUE THREAD

**Issue by wolverineks** [withspectrum/spectrum#5268]
When in mobile, text input extends over the publish button making it impossible to publish.

![858e0888-dcf8-422e-83af-fbda11c7e107-Screenshot_20190909-064500](https://user-images.githubusercontent.com/8462274/64618195-a64a0480-d394-11e9-89b1-c1be1e9a578b.png)

**Comment by abhishekakade** [comment]
Can I work on this issue if no one is already on it?

**Comment by zivanovicb1** [comment]
@wolverineks, Can you publish when the keyboard is closed(worked for me)? I tried bringing up a keyboard in Devtools(Nexus 5x) in local setup and was able to publish.

**Comment by gabrielatricak** [comment]
Hi, I would like to work on this issue for a school project. Can I be assigned to this?

**Comment by divyanx** [comment]
Yes, the bug is still there, when there is a long text spanning multiple pages the this happens even when the keyboard is closed.
Checked on chrome for android.

**Comment by brianlovin** [comment]
This is safe to close as we move towards a sunset read-only version of Spectrum next week.
