### ISSUE TITLE
Sign up page does not have other social logins 

### ISSUE THREAD

**Issue by praecantatio** [withspectrum/spectrum#5285]
When inviting a person without a spectrum account to a private channel, the link redirects to sign up page which does not contain most of the social accounts available on the login page.

**Comment by mxstbr** [comment]
When we were acquired by GitHub, we removed all other sign up options. To ensure existing users could continue to login other options are still shown on the "Log in" page, however new users have to use GitHub.

Sorry for any troubles this causes!
