### ISSUE TITLE
Gmail Login redirects to Github login

### ISSUE THREAD

**Issue by rakesh-intelligaia** [withspectrum/spectrum#5287]
Trying to login from a different computer using Gmail login is taking me back to Github login. I haven't even linked my GitHub to my spectrum account.

**Comment by jmgaya** [comment]
Hi @rakesh-intelligaia,

I've tried to login with my Gmail account too (without being registered with it before), and you're right:

![Only GitHub sign up](https://i.ibb.co/gVrtJVP/Screenshot-2020-01-10-at-17-07-29.png)

Looks like you're only allowed to sign up using *GitHub*, but you could still keep using *Facebook*, *Twitter* or *Google* if you've created your account some time ago 😜

**Comment by brianlovin** [comment]
Yes, only new accounts can be created with GitHub. Sorry for any troubles here!
