### ISSUE TITLE
Wrong favicon.ico in admin/public/index.html

### ISSUE THREAD

**Issue by jmgaya** [withspectrum/spectrum#5310]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)**

Seems [here](https://github.com/withspectrum/spectrum/blob/181cf90f8d1c49aeb97f0dbb80359daa0a1343a3/admin/public/index.html#L12) the **favicon.ico** points to https://spectrum.chat/favicon.ico, instead of https://spectrum.chat/img/favicon.ico

If you agree, I could submit a PR fixing this 👍

**Comment by brianlovin** [comment]
Hm, I'm not sure because the favicon is definitely loading for me – is it failing to render on your end?

**Comment by jmgaya** [comment]
Hi @brianlovin ,

You're completely right! Because there's a *public* folder inside the *admin* folder, sorry!

Meanwhile, I'm having issues while running the *admin site* locally, while receiving the following error:

```
Failed to compile.

./src/views/communities/components/search/index.js
  Line 152:  'ENTER' is not defined  no-undef

Search for the keywords to learn more about each error.
```

I know it's completely unrelated with this issue, so feel free to close it. However, if you're OK, I could fix this just by merging [this PR](), WDYT?

**Comment by jmgaya** [comment]
As mentioned [here](https://github.com/withspectrum/spectrum/issues/5310#issuecomment-573406114), the *favicon* is right 👍
