### ISSUE TITLE
Spectrum shows wrong number of online users

### ISSUE THREAD

**Issue by alvinseville7cf** [withspectrum/spectrum#5325]
Consider [this](https://spectrum.chat/spectrum/hugs-n-bugs/the-amount-of-online-users-is-wrong~16b86e2e-2060-4ef2-8e92-a3bd694a7d3c) post please

**Comment by sidoosh** [comment]
Hi @Alvin-Seville,
Can I work on this issue?

**Comment by Alvin-Seville** [comment]
Yes, of course you can.

**Comment by riiniii** [comment]
@alvinseville7cf is this one finished/still going? Am interested

**Comment by sidoosh** [comment]
@riiniii I am unable to finish it. Can you please pick it up?

**Comment by riiniii** [comment]
yes, thanks!

**Comment by alvinseville7cf** [comment]
@riiniii, I can't test it right now because I've got this error: It looks like Spectrum is very busy right now, please try again in a minute.

**Comment by alvinseville7cf** [comment]
@riiniii, it is still going.

**Comment by brianlovin** [comment]
This isn't a priority for us to fix right now, but thanks everyone for reaching out 😊
