### ISSUE TITLE
Dark theme or night theme

### ISSUE THREAD

**Issue by ghost** [withspectrum/spectrum#5336]

**Comment by Gizmotronn** [comment]
That would be nice

**Comment by soumalyatheking22012001** [comment]
Is anyone working on this feature I would like to work on it

**Comment by ashiskumar-1999** [comment]
@brianlovin Can you share your thought about implementing it? I am planning to create a dark mode for each component starting from the Button component.

**Comment by brianlovin** [comment]
We won't be supporting dark mode, as Spectrum is going into a read-only sunset mode next week.
