### ISSUE TITLE
Redirecting issue because of a moved community 

### ISSUE THREAD

**Issue by umitkucuk** [withspectrum/spectrum#5344]
Hi there. I want to mention an annoying issue that I am having currently.

My first channel on the sidebar is **spectrum.chat/next-js** and it is currently redirecting me to outside of **spectrum.chat**. Whenever I try to reach **spectrum.chat**, I am redirecting.

**Comment by brianlovin** [comment]
Fixing in https://github.com/withspectrum/spectrum/pull/5345 - thanks for the heads up!
