### ISSUE TITLE
Cannot login with all social media account 

### ISSUE THREAD

**Issue by itokun99** [withspectrum/spectrum#5357]
<img width="1440" alt="Screen Shot 2020-05-26 at 09 33 41" src="https://user-images.githubusercontent.com/45938169/82854944-194fd700-9f34-11ea-8e34-3e5c86d6263e.png">

**Comment by pavanmehta91** [comment]
same error. It's so disappointing.

**Comment by brianlovin** [comment]
We had some API downtime this morning, sorry for the trouble here folks!
