### ISSUE TITLE
Directs to Figma

### ISSUE THREAD

**Issue by AbhigyanKumar** [withspectrum/spectrum#5373]
# The page goes to Figma
The Spectrum website **always goes to _Figma_** even if I have no interest in it and **haven't even joined** the _Figma community_. 

# Slow 🔴 page
The **pages also load very slowly** 😒. This wastes my time and even stops **at times of writing posts**.

**Comment by judicaelandria** [comment]
Hey @AbhigyanKumar ,
The spectrum pages is slow ? I just open it now, and it's load quickly
Can you tell us more about your issue ?

**Comment by brianlovin** [comment]
I can't reproduce a Figma redirect, are you still experiencing this?

**Comment by AbhigyanKumar** [comment]
No. Now it's all right. I just figured it out. It was a problem with my VPN Provide. Sorry BTW.

**Comment by AbhigyanKumar** [comment]
However, it still redirects to Figma community whenever I open it.

**Comment by brianlovin** [comment]
@AbhigyanKumar can you share a gif or screen share video of this behavior?

**Comment by AbhigyanKumar** [comment]
I just figured it out! I cleared the cache, local storage and logged out and then logged in again. And it works!
