### ISSUE TITLE
Open API for Notifications in MS Teams

### ISSUE THREAD

**Issue by AlexTeusz** [withspectrum/spectrum#5374]
**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion
- [ ] Question (these will be auto-closed, please ask them on Spectrum instead https://spectrum.chat/spectrum/open)

**Description (type any text below)** 

Hello,

Providing an open API to connect spectrum with services such as Microsoft Teams would improve the usage significantly. Therefore, spectrum would inject a push notification as soon as a new question was asked in your community. 

Did you think about this idea before or would it be possible to add this to your pipeline?

Thank you very much!
Alex

**Comment by brianlovin** [comment]
This isn't something we will prioritize as we continue integrating deeper into GitHub with the upcoming Discussions feature. Thank you for sharing this idea though!
