### ISSUE TITLE
Question about some libs

### ISSUE THREAD

**Issue by MrTierrin** [withspectrum/spectrum#5405]
**Issue Type**

- [ ] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [x] Question

**Description**

Hi! I have been looking at the source code of the application and I have noticed that old versions of both `apollo-x` and `react-helmet-async` are used and I am wondering why.

But more important, is Spectrum still maintained and in development?

**Comment by brianlovin** [comment]
We have not been actively updating dependencies while we continue to move towards GitHub Discussions in the future - thanks for the question though!
