### ISSUE TITLE
Font size is being declared twice in the same variable

### ISSUE THREAD

**Issue by knowledgeReignsSupreme** [withspectrum/spectrum#5428]
Hello everybody, while scrolling through the project file In  [spectrum/src/views/login/style.js](https://github.com/withspectrum/spectrum/blob/913be0c166b7f6367589cf5113dc9a0b9afc55c5/src/views/login/style.js) I found that the font-size is being declared twice in the same variable, I'm a newbie to open source so I don't really know how to handle it by myself.
But anyway, is there any reason to use px instead of rem when declaring font sizes?
The style:
export const Title = styled.h1`
  color: ${theme.text.default};
  width: 100%;
  font-weight: 800;
  **font-size: 24px;**
  line-height: 1.25;
  margin-bottom: 8px;
  padding: 0;
  **font-size: 24px;**
  text-align: center;
  letter-spacing: 0.2px;
`;
Thanks

**Comment by up16** [comment]
Hi, You can issue a pull request with the changes that you would like to propose. Do mention in the comments what functionality/fix is added. Additionally, you can also link your pull request to this issue, for reviewers to have a better understanding. To have a better understanding of contributions do read the README file at the root directory. It will help you to get yourself acquainted with the code base and running the project locally on your system.
About the font-size being declared twice, I see no harm in getting rid of any one of those.

**Comment by Sagnik-Chaudhuri** [comment]
Hey, can I pick this up? This would be a start for me, and i'd also get to be familiar with open source development.

**Comment by knowledgeReignsSupreme** [comment]
> Hey, can I pick this up? This would be a start for me, and i'd also get to be familiar with open source development.


HI Sagnik-Chaudhuri. It's fine by me

**Comment by brianlovin** [comment]
We aren't actively merging community contributions to the repo right now while we work towards a sunset in August. Thanks for the conversation here 😊
